### ISSUE TITLE
TMA

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#101]
https://www.nma-fallout.com/threads/fallout-et-tu-release-v1-6.218045/page-64#post-4440071

1) Three stupid mutants in a waterworks in Necropolis - They have their own dialogues and their own "tell me about" texts, but both is unused.
(Although it may be remnants of unused texts from the original game.)
2) Bouty hunter Chriss - His "tell me about" texts will give you errors.
3) Seth in Shady Sands - He uses generic "tell me about" texts, instead of his own, original ones.
4) Water Guard in Vault 13 - He uses generic "tell me about" texts, instead of his own, original ones.
(But in his defense, his own "tell me about" texts are not very extensive.)

**Comment by FakelsHub** [comment]
I wanted to ask how long ago it started to glitch the mouse cursor graphics, when you click on the TMA button, a gray rectangle is formed under the cursor for a fraction of seconds.
I have never seen such a graphical glitch before. Do you have such a thing?

**Comment by Lexx2k** [comment]
This is the first time I hear about this.

**Comment by FakelsHub** [comment]
Now, you know that there is such a problem. ):(

**Comment by Lexx2k** [comment]
I tried it with a few versions back, but it seems like this issue exists for a very long time now? (if not since ever even??). I can barely see it on my computer, though. It's just a very faint flicker and I probably would never have seen it on my own.

**Comment by FakelsHub** [comment]
Fix glitch.
https://github.com/rotators/Fo1in2/blob/18461d51aa34a6537bbdf1b67ef62f4c4fc5c303/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_tma.ssl#L303-L306
Replace to
```
create_win_flags("tellme_interface", (Scr_Width), (Scr_Height + 290), 640, 190, WIN_FLAG_HIDDEN + WIN_FLAG_MOVEONTOP);
SelectWin("tellme_interface");
// FillWin(0, 0, 0);  senselessly - send to trash!
```

https://github.com/rotators/Fo1in2/blob/18461d51aa34a6537bbdf1b67ef62f4c4fc5c303/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_tma.ssl#L336
replace to `show_window` macro.

**Comment by Lexx2k** [comment]
Looks like it works. At least I don't see it flickering anymore.

**Comment by FakelsHub** [comment]
> I can barely see it on my computer, though. It's just a very faint flicker

I also used to have this flickering faintly noticeable, but now it was VERY noticeable.
