### ISSUE TITLE
Stuck in Basic Graphics Mode

### ISSUE THREAD

**Issue by darious24555** [rotators/Fo1in2#103]
I have no idea why it doesn't actually match the ini like it should. It is only Et tu that does this for me.
![Untitled](https://user-images.githubusercontent.com/89959958/131783976-20a630bc-c64f-4542-9717-cfcefd7054d3.png)

**Comment by Lexx2k** [comment]
Can't really help with the High-Res patch stuff, as we didn't made it. Also you gave too little information about your operation system, etc. which makes it even harder to help.

**Comment by FakelsHub** [comment]
Sfall dx9 is enabled, so hrp does not work.
