### ISSUE TITLE
Deckers Jobs

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#104]
NovaRain
 — 
Yesterday at 4:29 PM
About Et Tu, after I killed Decker, the "dispose of merchant" quest still doesn't get crossed out, maybe killing Jain is the same.

**Comment by HappyJarek** [comment]
Btw both quests weren't crossed out in my game too until I double-crossed him to the police and helped to storm  hideout with resulting Decker's untimely desease :)
