### ISSUE TITLE
Military base - crash

### ISSUE THREAD

**Issue by JSh-git** [rotators/Fo1in2#105]
I was captured in the military base, put into a cell and no trying to break free
Ian and Tycho are in the other cells, Ian can be rescued, but talking to Tycho creates an memory access violation and the game crashes every time

**Comment by Lexx2k** [comment]
Copy this file into `\mods\fo1_base\scripts` and overwrite the one that is already there. Then try again.

[TYCHO.zip](https://github.com/rotators/Fo1in2/files/7111063/TYCHO.zip)

**Comment by JSh-git** [comment]
That worked nicely
