### ISSUE TITLE
Green asphalt graphic bug

### ISSUE THREAD

**Issue by yooksi** [rotators/Fo1in2#107]
I have a graphic glitch that is very noticeable in The Hub where the asphalt appears like it is covered in moss:

![scr00001](https://user-images.githubusercontent.com/16436920/133195767-c075d98d-8c39-49b7-9f49-708df04f2fb4.png)

The graphic glitch is not present in a small radius around the player as he moves around probably due to lighting updates:

![scr00002](https://user-images.githubusercontent.com/16436920/133195890-8f28cedc-397d-4902-bf4a-eccbd5eae47a.png)

This happens on a fresh install of FO1 Et Tu, with no custom configurations. However I am unable to replicate this bug as when I reloaded an older save and traveled to The Hub the roads looked normal again.

Here is the [save file](https://github.com/rotators/Fo1in2/files/7158916/fo1_the_hub_mossy_roads_bug_save.zip) that has the mossy roads graphic glitch if that will help in any way.

**Comment by Lexx2k** [comment]
This is caused by the current daytime / light level. Not a bug.

**Comment by yooksi** [comment]
Is there any way to mitigate this through configurations?

**Comment by Lexx2k** [comment]
Fallout is an old game with only ~250 available colors. There is nothing that can be done about it. Just wait 30 ingame minutes and the effect is gone ...
