### ISSUE TITLE
Kill the Mother Deathclaw don't get crossed out on Pip-Boy

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#110]
If you kill her before getting the quest. You complete the quest and get the reward but it still shows on Pip-Boy.

**Comment by Lexx2k** [comment]
No idea why the quest was showing up anyways. This should not happen unless you talk with Gabriel and actually get the quest.

In any case, I've added a fail-safe to that now ... https://github.com/rotators/Fo1in2/commit/1241e02d4689bcf7240914f532ca0ea4d2909c13
