### ISSUE TITLE
Bike out of power behaves like I've reached the destination

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#111]
I can enter the Hub like if I was there, if I exit I'm back where the bike was (and I move it with me wherever I go?)
![Sem título](https://user-images.githubusercontent.com/83250053/138086546-070db20b-a12c-4acc-9272-d40dfd06a79e.png)

**Comment by Lexx2k** [comment]
Can't reproduce / check without savegame. Probably a hiccup in the gl script processing. Not much we can do here.
