### ISSUE TITLE
Should Kill Neal be this mess?

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#115]
This is weird because I did a "clean" Kill Neal before with this same character (just killed Neal and Trish then combat ended) but I decided to re-do Junk Town and now tried several times already and the combat never ends, sometimes they drawn aggro from that hobo south, sometimes it's red shirt guy northwest that enters the fight, and as Skulz get near other NPCs they all go joining the fight, so end up drawing aggro from Casino NPCs... I didn't have the patience to go through in any of the tries but looks like I'd have to clear the map to finally close combat.

Also a tweak that I think would be nice is that Skulz were on player's team to avoid followers turning on them for friendly fire...
![Sem título](https://user-images.githubusercontent.com/83250053/138566291-20f4f94b-600b-4a7b-9f40-c38095d0d4a6.png)

**Comment by Lexx2k** [comment]
Not much I can do about any of this. It's simply Fo1 being what it is. 

Tycho has a special role in that if you kill any "good" person in Junktown, he will get hostile to you. Civs run away if you kill guards, etc. etc. It's kinda supposed to be like that. 

The first issue above is simply some damage / hostile check going haywire. It just needs a team mate to get damaged by accident and all hell breaks lose. Again, impossible for us to fix without huge (and questionable) rewrites.
