### ISSUE TITLE
Inspecting Floating Eye closes the game

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#116]
The one added by the mod. No error message nor anything, just closes.

ps: I added Party Orders and Fo2Tweaks to the game

**Comment by Lexx2k** [comment]
Can't reproduce. Need to know at what stage you are trying to inspect the critter.

**Comment by PxHC** [comment]
At all stage (power off, power on movements on, power on movements off, and outside the hole), I don't have the saves anymore but I did two playthroughs and it only happened in the first one, but in both I couldn't power it up outside, using both Small Energy Cell and Microfusion Cell did nothing - I posted it on the Et Tu thread on NMA at the time

**Comment by Lexx2k** [comment]
Still can't reproduce. Probably an issue that was already fixed before.
