### ISSUE TITLE
Blood pools cover some items

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#117]
Pickable but very hard (it was hard to find the pixel)... thinking about it again... nevermind lol
Edited because I thought it was unclickable
![Sem título](https://user-images.githubusercontent.com/83250053/139105353-fa8d9e1a-38a7-48c6-9064-3e3bd7f9fa84.png)

**Comment by burner1024** [comment]
Meanwhile, use [Party Orders](https://github.com/BGforgeNet/Fallout2_Party_Orders) to pick up stuff.

**Comment by Lexx2k** [comment]
Well, nothing we can do here.
