### ISSUE TITLE
Unresponsive black screen after getting dipped in the vats

### ISSUE THREAD

**Issue by alvarocastro** [rotators/Fo1in2#119]
I was in the military base getting interrogated by the lieutenant and got dipped into the mutant vats, after watching the cinematic where the vault is invaded, the game got back to what I believe is the 4th floor and everything is black (red dots are the alarms) and unresponsive, not even ALT-F4, ESC or F7 to quick load works, had to kill the process.

![image](https://user-images.githubusercontent.com/708381/142293590-11424eb6-6d67-41a3-b91e-f6cf46977e21.png)

**Comment by Lexx2k** [comment]
Did you wait a while? Seems there is a 35 ticks timer. Though that never caused issues for me, so dunno.

**Comment by Lexx2k** [comment]
Can't reproduce.
