### ISSUE TITLE
stuck in basic graphics mode

### ISSUE THREAD

**Issue by nr1995** [rotators/Fo1in2#120]
Hi, noob here.
I'm not very technically minded,
but the in-game graphics mode doesn't seem to want to follow the .ini graphics mode.
As such I'm stuck in basic mode, i.e. “0”.
I **am** using the Hi-Res patch though.
Is there any way to reconcile these two?  I'd love to play in a window.
I could do it in both regular Fallout 1 and 2.
I'm using Windows 10 64-bit.

**Comment by NovaRain** [comment]
If you just want to play in a windowed mode. Set `Mode=0` in [Graphics] section in ddraw.ini, and set `GRAPHICS_MODE=2` and `WINDOWED=1` in f2_res.ini.

**Comment by nr1995** [comment]
> If you just want to play in a windowed mode, set `Mode=0` in [Graphics] section in ddraw.ini, and set `GRAPHICS_MODE=2` and `WINDOWED=1` in f2_res.ini.

You pointed me in the right direction.
You can consider this problem resolved.
