### ISSUE TITLE
Does this mod influence the Fallout 2 installation folder / files / structure ?

### ISSUE THREAD

**Issue by JohnnySixPistols** [rotators/Fo1in2#121]
1. I installed the Fo1in2 in my Fallout 2 folder, it worked as intended, I beat F1 without any issue.
2. Now I wanted to play F2 and I installed Restoration Project on it.
3. Now I play the F2 and get crashes (I forgot to remove F1in2 / make a clean install before playing F2 w/ restoration patch)

Could it be the source of my crashes? Sorry for a dumb question!

Thank you for your great mod!

**Comment by Lexx2k** [comment]
Fo1in2 is in its own folder, it has no influence on the original Fo2 installation and its mods. Your crash is likely related to the RP.
