### ISSUE TITLE
Crash When Closing Talking Heads

### ISSUE THREAD

**Issue by CoganTheDestroyer** [rotators/Fo1in2#122]
When closing the window for talking heads the game will crash more often than not. I'm not sure what exactly could be causing this but I've never had it before installing this mod. I am using interface upscaled if the would maybe have something to do with it.

**Comment by Lexx2k** [comment]
Talking heads is a vanilla function, we have no influence about this.

**Comment by CoganTheDestroyer** [comment]
> Talking heads is a vanilla function, we have no influence about this.

Ok sorry to bother then. I must have changed something in the settings that's breaking it.

**Comment by Lexx2k** [comment]
That's unlikely related to some setting. If the dialog crashes when closing the talking heads window, something is seriously wrong. 

You suggested the interface upscaled mod - this is highly unlikely, as it does not touch those interfaces.

**Comment by FakelsHub** [comment]
TMA Может глючить.

**Comment by Lexx2k** [comment]
But it hasn't changed in a long time now.
