### ISSUE TITLE
Request: Scrapheap?

### ISSUE THREAD

**Issue by Dark-Jaguar** [rotators/Fo1in2#125]
Would restoring the Fallout Demo town of Scrapheap and it's quests be a possible addition down the line?  Considering the town's similar layout to Junktown, maybe it's better left as optional, but it would be nice to have that otherwise missing content available.

**Comment by Lexx2k** [comment]
The demo is already in the game. There's a computer terminal in Necropolis that will boot it up.

**Comment by Dark-Jaguar** [comment]
That's amazing, thank you!  I had no idea that was there.  Was it added by this mod or actually in the original and I somehow missed it?  If added by the mod, a note indicating as such in the mod's description might be helpful.

**Comment by Lexx2k** [comment]
We added it as secret / easteregg.

**Comment by Dark-Jaguar** [comment]
Whoops, didn't mean to spoil the surprise!!  But, thank you very much for putting it in there.  I can delete the demo from my PC now.  Can Github readme's have spoiler tags?  In any case consider this closed!

**Comment by wipe2238** [comment]
> Can Github readme's have spoiler tags?

On GitHub itself? [Yes. Kinda.](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287)
