### ISSUE TITLE
Caravan leader missing text

### ISSUE THREAD

**Issue by Thrax-x** [rotators/Fo1in2#128]
First line in file HGENCVAN.MSG:
{100}{}{ERROR}
Right text:
{100}{}{You see a caravan driver.}

https://fallout.fandom.com/wiki/HGENCVAN.MSG

**Comment by Lexx2k** [comment]
Need to know where you found that NPC in the game.

**Comment by Thrax-x** [comment]
Nowhere, I inserted it with Mapper. I checked the file in original Fallout 1 and text is there, texts in German and French translations are OK, only in English it's missing.

**Comment by Lexx2k** [comment]
As far as I can tell, the line is unused. Nothing to actually fix here.

**Comment by Thrax-x** [comment]
NPC Mat, Luke and John use this file in their scripts.
Line 100 is unused. Probably it was supposed to be seen when you don't know name of NPC and after first talk you have to see line 200 or 300 or 400. Many NPC in game use this logic. But original authors of Fallout forgot of this in this case.
If this text was present in original Fallout 1 and it is present in your French and German translations, why not add it in English too?  :-)

**Comment by Lexx2k** [comment]
Yes, multiple NPCs are using the file, but the line itself is unused. As I said, the description was moved to line 500+.

Re-adding it to the english line is pointless. Sduibek likely added the "ERROR" to identify characters in the game that still use the old line.

**Comment by Thrax-x** [comment]
I'm sorry for this discussion, I don't want to be annoying, but this was surprise for me, because in FIXT this line has correct text. I checked Sduibek's repo and found out, that he fixed the line 100 from ERROR to right text in 2015.

https://github.com/Sduibek/fixtlang/commit/d366e337f380d973b44313eb93b28818ab11d288#diff-5cde6483d4874ee27a61230d9dce62388d4c38860c74baf6af602582cbc6a167
