### ISSUE TITLE
Caravan encounter not abiding F2 critters setting

### ISSUE THREAD

**Issue by Saltra** [rotators/Fo1in2#133]
Went with a caravan from the Crimson Caravan to the Brotherhood, on the way back to the Hub (with the caravan) I got an encounter with some golden geckos despite the option in fo1_settings to enable F2 critters being set to 0, i had not gotten any encounters involving geckos or other F2 critters before so i suspect it's something to do with the caravan drives in particular.
fecking loving the mod btw, cheerio

**Comment by Lexx2k** [comment]
Well, the setting is for "encounters" - caravan stuff is something else entirely. I will add some conditions for them which will revert it back to Fo1 default critters, but then you will get huge groups of ghouls and deathclaws and stuff like that instead (always hated those, I don't know why they thought it's a good addition or that it makes any sense at all).
