### ISSUE TITLE
mouse slow?

### ISSUE THREAD

**Issue by ihavetubes** [rotators/Fo1in2#134]
is it normal for the mouse to be so slow? especially when picking a new tile. Feels like the fps drop. thanks for any help

**Comment by Lexx2k** [comment]
Try changing mode= in the ddraw.ini to something else.

**Comment by ihavetubes** [comment]
> Try changing mode= in the ddraw.ini to something else.

do you mean?

[Graphics]
;Set to 0 for 8 bit fullscreen
;Set to 4 for DX9 fullscreen
;Set to 5 for DX9 windowed
;Set to 6 for DX9 fullscreen windowed (the resolution in f2_res.ini should be set to the same aspect ratio as your desktop resolution)
;A DX9 mode is required for any graphics related script extender functions to work (i.e. fullscreen shaders)
;Modes 1, 2 and 3 are no longer supported
Mode=4

**Comment by ihavetubes** [comment]
ok changing [Graphics] Mode=6 now I get a fps of 1000 lol. game works great now thanks for the help

**Comment by ihavetubes** [comment]
I found a new problem, anytime I get killed in Mode=6 the game freezes than I get the game over death screen. This doesn't happen in mode-4

**Comment by ihavetubes** [comment]
I think the problem is the frame limit it seems at 144 is too slow for the game to run at full speed. Not sure if I can uncap it like Mode=6

**Comment by ihavetubes** [comment]
game runs perfect in windows 7 mode-4

**Comment by ihavetubes** [comment]
Ok I fixed the problem from windows 10, you have to turn off Vertical sync off.
