### ISSUE TITLE
Warning tab for crippled characters

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [rotators/Fo1in2#136]
Correct me if I’m wrong, but doesn’t _Fallout 2_ display little warning tabs whenever the main character or the party members have a crippled limb? I was expecting to see one after my character took a fall down a mountain, but I had to keep checking her character sheet instead to see if I healed all of them.

**Comment by NovaRain** [comment]
The game itself doesn't show any warning tabs for being crippled. The thing you got in RP is from a script mod, and et tu doesn't have it.
