### ISSUE TITLE
Strange looking coyote

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [rotators/Fo1in2#137]
Somewhere in a desert to the northwest of the Deathclaw Lair, I encountered this ‘coyote’ that happens to be in the shape of a Centaur. It refused to attack my party no matter how closely I approached it.
![coyote](https://user-images.githubusercontent.com/51846125/185876537-afa53fc7-31db-4c3d-b41c-5752755096c4.png)
I would post a save, but unfortunately I overwrote it by accident, and retriggering this encounter is proving to be very time‐consuming. I hope that one won’t be necessary.

**Comment by Lexx2k** [comment]
Not all critters attack on sight. Bug here is that it shows coyote. Will fix later.

**Comment by HappyJarek** [comment]
> Somewhere in a desert to the northwest of the Deathclaw Lair, I encountered this ‘coyote’ that happens to be in the shape of a Centaur. It refused to attack my party no matter how closely I approached it. ![coyote](https://user-images.githubusercontent.com/51846125/185876537-afa53fc7-31db-4c3d-b41c-5752755096c4.png) I would post a save, but unfortunately I overwrote it by accident, and retriggering this encounter is proving to be very time‐consuming. I hope that one won’t be necessary.

I confirm this issue 100%, I met this strange coyote too (pls see below)!

![scr00122](https://user-images.githubusercontent.com/114113403/191798211-c7e67be4-18b5-4c41-9849-a18a9aec5cac.png)

**Comment by Lexx2k** [comment]
This is already fixed.

**Comment by HappyJarek** [comment]
Ok, it's good to know.
I just wanted to confirm the existence of the issue.
