### ISSUE TITLE
The entrance from vault 12 to the city is bugged

### ISSUE THREAD

**Issue by DrBabbage** [rotators/Fo1in2#138]
You get teleported into the wall. Tried it again with another safe. I got the chip, when you want to go back you are stuck in the wall of the sewer system with no way to go back

**Comment by Lexx2k** [comment]
Need safe for repro.

**Comment by DrBabbage** [comment]
Yes newest repository version and the gog version.

https://anonfiles.com/k7V5Q551yc/SLOT31_rar

Here you go. Go down the hole to the vault and then go back in the sewers. Lmk if you need anything else.

**Comment by Lexx2k** [comment]
Fixed with https://github.com/rotators/Fo1in2/commit/e80b50ccb9836644714bcb5a9a90308330a6d983

If you redownload the scripts, it should work with your save.
