### ISSUE TITLE
The Master - Animation issue

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#14]
This is a bug that is also present in Fallout 1.

When entering the map with the Master for the very first time, his graphic is shown on the wrong position. It is necessary to run `animate_stand_obj(self_obj)` on map_enter to correct this (Fallout 1 is doing it this way). However, this takes a few seconds and if the player gets moved to him via (as example) Morpheus, it is very visible and ugly. 

![The Master bug](https://i.imgur.com/h7hw8ql.png)

He will also correct himself after a while without running animate_stand_obj() but that takes even longer.

Thought about adding an extended black-fade period to fake it away, but script-wise I really don't want to, because it can lead to some horrible shit. :x Besides, the fade isn't necessary the same speed for every player anyway.

I'm assuming this is a "simple" animation issue, but after toying with the *.frm offsets for a couple hours I felt defeated and gave up.

At this point I don't know how to fix this. It's not super important, but maybe some day...

**Comment by burner1024** [comment]
What's ugly about it?

**Comment by Lexx2k** [comment]
Well, the obvious position-teleport when you enter the map via Morpheus.

**Comment by burner1024** [comment]
Sorry, I don't remember the location that well. Teleport isn't obvious to me from screenshots. Is there no actual "stand-up" animation, just an instance switch from one to another?

**Comment by Lexx2k** [comment]
Yes, it looks exactly like in my screenshot above. Enter the location and Master is dislocated. Script runs "animate_stand_obj(self_obj)" and after two or three seconds, the Master sits in correct position.

I don't know why this transition takes so long. I'm assuming it's an idle animation that first has to play through. I've tried setting a frame directly, and avoiding the animate_stand_obj(), but that didn't really change a thing.

**Comment by burner1024** [comment]
Strange, I vaguely remember seeing to stand up, but I could be mistaken.
Well, worst case, you can just copy standing animation to idle, so that they are the same...

**Comment by Lexx2k** [comment]
Ok, as always the solution to mankinds problems was fairly simple.

The thing with animate_stand_obj() is that it apparently plays the full animation before something happens... well, usually because you want to play the full "stand up" animation.

So what I did now was... to remove it and replace it with a generic animation call. reg_anim_begin() etc... because that one doesn't have the critter wait until it plays till the end, it happens instantaneously. 

Result: Master gets moved to his correct position right on the first frame and thus the issue is solved.

**Comment by wipe2238** [comment]
That was quick :D

**Comment by Lexx2k** [comment]
Well, wish I had thought of that before spending hours on shifting offsets in frm files.
