### ISSUE TITLE
*Error* line instead of description of all killed critters

### ISSUE THREAD

**Issue by HappyJarek** [rotators/Fo1in2#140]
![scr00007](https://user-images.githubusercontent.com/114113403/191616192-1e397a1f-2e17-4a6a-a675-28fb2e86ac91.png)

**Comment by Lexx2k** [comment]
Can't reproduce, everything is fine.

**Comment by Lexx2k** [comment]
Missing text files. Don't know why, there is too little information.

**Comment by HappyJarek** [comment]
> Missing text files. Don't know why, there is too little information.

Strange... I thoroughly followed installation instruction. Win 7 Pro x64, both games installed from Steam.
Could you please tell me what information you need?

**Comment by Lexx2k** [comment]
Language version, any other mods installed, any other changes done, etc.

**Comment by HappyJarek** [comment]
> Language version, any other mods installed, any other changes done, etc.

EN, no other mods except the ones provided with Et Tu (like ShowLootWeight etc), and I changed some settings in  fo1_settings.ini and ddraw.ini files. That's all.

**Comment by Lexx2k** [comment]
Can you open the files \mods\fo1_base\text\english\game\proto.msg and tell me how many lines it has? Last entry should be 1487

**Comment by NovaRain** [comment]
Why you enabled `ExtraKillTypes` option in ddraw.ini? It doesn't really add anything to the game, and because you enable it without extra descriptions in proto.msg , you have all kill types missing their description.

**Comment by Lexx2k** [comment]
Ettu doesn't have more kill types, and the description clearly says that it only works if the proto.msg file is written for it (which it is not in ettu):
`;If you use this, you need to provide the extra descriptions in proto.msg (entries from 1450 to 1487 are names and 1488 to 1525 are descriptions)`

... should not change game settings if you don't know what you're doing.
