### ISSUE TITLE
Silent Dogmeat

### ISSUE THREAD

**Issue by HappyJarek** [rotators/Fo1in2#141]
By some reason it doesn't bark when attacking or being attacked.
Savegame for the release, v1.8.3032 provided.
[SLOT9985.zip](https://github.com/rotators/Fo1in2/files/9620674/SLOT9985.zip)

**Comment by Lexx2k** [comment]
Same as with the other ticket, issue must be on your end.

**Comment by HappyJarek** [comment]
> Same as with the other ticket, issue must be on your end.

Sorry, did my savegame worked for you and the issue didn't appear?

**Comment by NovaRain** [comment]
The red Dogmeat lacks corresponding sfx due to his unique appearance, extract the attached zip to your `data\sound\sfx\` folder.
[red_dogmeat_sfx.zip](https://github.com/rotators/Fo1in2/files/9621965/red_dogmeat_sfx.zip)

**Comment by Lexx2k** [comment]
Thanks, added the files to git.

**Comment by HappyJarek** [comment]
> The red Dogmeat lacks corresponding sfx due to his unique appearance, extract the attached zip to your `data\sound\sfx\` folder. [red_dogmeat_sfx.zip](https://github.com/rotators/Fo1in2/files/9621965/red_dogmeat_sfx.zip)

Thank you for your reply, everything works just fine now!
