### ISSUE TITLE
TMA Loxley

### ISSUE THREAD

**Issue by HappyJarek** [rotators/Fo1in2#142]
Half of his responses are not sounded (but I remember that wasn't an issue before, in FIXT 1.0 at least) while the other half is mixed up.
[SLOT24.zip](https://github.com/rotators/Fo1in2/files/9627756/SLOT24.zip)

I used thisTMA list: https://fallout.fandom.com/wiki/Loxley#Tell_me_about

**Comment by HappyJarek** [comment]
I'm sorry, this means it'll be fixed in the next release or what?
Or I missed something?

**Comment by NovaRain** [comment]
Will be available in the next release, or you can wait for daily autobuild.

**Comment by HappyJarek** [comment]
Do you upfate it **_daily_**? Oh my

**Comment by NovaRain** [comment]
> Do you update it **_daily_**? Oh my

https://github.com/rotators/Fo1in2/commits/master
If you check the commit history, you can see there are "Progress every day" commits which script changes/fixes are compiled by automated process. Just download the snapshot of the repo and update your game with its content.
If you don't know how, better just wait till next formal release.

**Comment by HappyJarek** [comment]
I think I'll better wait for the release, thank you.
