### ISSUE TITLE
Combat training in BoS

### ISSUE THREAD

**Issue by HappyJarek** [rotators/Fo1in2#144]
It seems this training adds only to Unarmed skill since my Melee stayed at the same level as before (it was tagged and being >100%).

Savegame:
[SLOT20.zip](https://github.com/rotators/Fo1in2/files/9627899/SLOT20.zip)

**Comment by Lexx2k** [comment]
Has something to do with tag skills. Can't fix.

**Comment by Lexx2k** [comment]
NovaRain gave me an idea for how to fix this. Now it works as in Fo1 again and also shows the correct Skill+ message in the log (in Fo1 it only says +1... even though the player actually got +2 points).

**Comment by HappyJarek** [comment]
You're welcome!
Thank you.
