### ISSUE TITLE
Vendors not restocking their inventory (?)

### ISSUE THREAD

**Issue by Mr-Dredgen** [rotators/Fo1in2#147]
Hi. I'm on my "second" playthrough of Fallout 1 using this mod (it's quite amazing, btw. makes the experience much better).

On my first playthrough I made some poor choices regarding character creation and ended up having to buy Vance's entire buffout stock. I bought it then went out to do some stuff. More than a month passed when I returned, but his inventory never restocked. As far as I was concerned I was locked out of an "easy" and direct way to buy buffout.

Hadn't gotten that far so I ditched that character, made a better one just a couple days ago. At level 5 or 6 I bought Jake's entire AR ammo supply. I went and did a couple of side quests, returned the water chip and did a couple caravan escort jobs. Now I'm level 8, I'm pretty sure that close to two months have passed (maybe more), and he still hasn't restocked. I still have plenty of ammo left and haven't met the Gun Runners or gone to The Glow to explore, but I'd like to know if this restock thing is an actual bug/issue or just how the game is meant to work. Maybe I'm doing something wrong? or missing something? perhaps I need to wait a bit more? 

I have the restock option active in my fo1_settings.ini. GVAR_ENABLE_FO2_MERCHANT_RESTOCK=1. Have had it since I installed the mod, and I haven't messed around with other config options that could mess the restock up (as far as I know).

Sorry for the long post. Any help would be much appreciated. Thanks!

**Comment by Lexx2k** [comment]
Need a savegame for repro. Jake restocks randomly after 1 to 3 days.

**Comment by Mr-Dredgen** [comment]
Here you go. Let me know if it's the wrong file or if you need anything else. Thanks!

[SLOT17.zip](https://github.com/rotators/Fo1in2/files/9638120/SLOT17.zip)

**Comment by Lexx2k** [comment]
![scr00001](https://user-images.githubusercontent.com/4844938/192087017-1f8dcfb1-1d13-4b56-8d8e-1041c37d3880.png)

You have to leave the map for the merchant to restock.

**Comment by Mr-Dredgen** [comment]
Forgive my ignorance, but what does leaving the map mean? In the save I sent I had just returned from killing the deathclaws and visiting the Gun Runners down in Boneyard; after that I went back to the Hub so I could save right on Jake's doorstep. I exited the Hub map just now, went into the desert, waited 4 days and came back: still no AR ammo. Sorry, but I'm at a loss :(

**Comment by Lexx2k** [comment]
After loading your savegame, I left Old Town to the west, then returned to the shop and the 5mm ammo restocked.

**Comment by Mr-Dredgen** [comment]
I just did that and nothing happened. I'm by no means the expert here, but perhaps something else is going on? I also bought some rad x and radaway from Vance before leaving for Boneyard. Did what you said after loading the save; same thing, he still hasn't restocked.

**Comment by Lexx2k** [comment]
Are you using any other mods? And are you 100% sure the restocking option is actually enabled?

**Comment by Mr-Dredgen** [comment]
I installed FIXT after Vance didn't restock in my first playthrough, but... that's the thing, the restock was already not working on my first playthrough. No shilling, but FIXT doesn't hold a candle to this, so I went back and checked that everything was configured properly before starting my new character. Again, GVAR_ENABLE_FO2_MERCHANT_RESTOCK=1 is set to 1 and has been since I downloaded the mod, before I even played it for the first time. 
I don't know what else could be wrong. Here's my fo1_settings.ini (in text form)

[fo1_settings(1).txt](https://github.com/rotators/Fo1in2/files/9638270/fo1_settings.1.txt)

**Comment by Lexx2k** [comment]
Uh... you what? Ettu is a Fo2 mod and Fixt is for Fo1. If you install that over the files, you are breaking the game.

**Comment by Mr-Dredgen** [comment]
No offense, but I'm not that stupid.
Yeah, I meant I installed fixt as you normally would (in the fallout 1 folder or whatever) and et tu as you normally would (in the fallout 2 folder, following the instructions on the mod page to the letter). Other than that, I didn't install anything for either game. 
I just nuked both games from my hard drive and made a clean install of Vanilla F1, Vanilla F2 and et tu. I don't know if I could or should restore my progress, as I backed up the save files. I probably don't have what it takes to start a new game for the third fucking time over the course of a week; doing the exact same shit over and over gets old pretty damn quick. What's worse, I wouldn't even be able to immediately tell if doing this fresh install fixed whatever was happening.
I guess I'll find out one way or another

**Comment by Lexx2k** [comment]
If the setting doesn't work, other settings shouldn't work either. In any case, I can't reproduce the issue, as you can see in the screenshot above from your savegame.

**Comment by Mr-Dredgen** [comment]
>other settings shouldn't work either

Now that you mention that... there were a couple of weird things happening. 
For example, the timer to save the Vault was "infinite" (there wasn't a counter in the PipBoy, it just said "Get the Water Chip "infinite symbol" days left", even though the settings file clearly said 150. I don't know if I actually had infinite time, as I didn't take that long to get the thing. The Shady Sands merchant wasn't there, even tho I had him enabled; Agatha, however, was there (and I obviously had her enabled).

I literally have no idea what went wrong. Right now I'll just tweak the fo1_settings.ini file to change a couple things, see if that works. I guess I'll be able to tell if things work by looking at the chip timer. If it still acts weird, then I literally don't know what's going on.

I'm playing on the steam version of the games btw. The steam library install folder is not in program files (normal or x86), it's on its own drive, in its own folder. Just thought I'd mention it.

**Comment by Lexx2k** [comment]
Your old savegame should still be compatible with this. There's no need to start a new game unless you played with a different version of ettu before.

**Comment by Mr-Dredgen** [comment]
Well, just tried the old save and it indeed works (was afraid it wouldn't because of the different config settings used). Most importantly, Jake has finally restocked! Apparently Vance did too (just left Old Town and came back, like you said).
I guess that's it.

Again, thank you so much for your help! Sorry for being ignorant when it comes to this things and sorry if I came off as rude a few comments ago :P Have a nice day
