### ISSUE TITLE
Can't fix the Necropolis water pump under Garret's supervision

### ISSUE THREAD

**Issue by Bilgamesh** [rotators/Fo1in2#149]
If you take the water chip without fixing the pump, have junk in your inventory and talk to Set, you can convince him to let you keep the water chip in exchange for fixing the water pump. You are supposed to be escorted by Garret to the water pump, where he's supposed to make sure you won't leave without fixing the pump. However in Et Tu while Garret is correctly teleported near the water pump, my character gets teleported outside the building and Garret goes hostile immediately. 

Recording: https://user-images.githubusercontent.com/24696613/194406447-019a77eb-9138-49da-9932-5062abcf9e2d.mp4

My save slot: [SLOT05.zip](https://github.com/rotators/Fo1in2/files/9728172/SLOT05.zip)

**Comment by Bilgamesh** [comment]
I did clean installation of Fallout 1 and 2 and then Et Tu mod on 28th of September. Then I installed the following mods :
- Inventory Filter 2.0 (I unchecked Sfall)
- fo2tweaks_v12.10
- party_orders_v1.12
Then I started a new game. I never updated or overwrote anything during the playthrough. I might have changed some settings in fo1_settings.ini during the playthrough though, namely the GVAR_ENABLE_FO2_WORLDMAP and GVAR_ENABLE_FO2_CRITTERS if I remember correctly. 
Could one of the mods above modify the map? I know the installer of Inventory Filter tends to modify ddraw.ini

**Comment by Lexx2k** [comment]
Likely not. 

You can recognize the old map if you just try to scroll to the top right of the map. This will be visible:

![scr00011](https://user-images.githubusercontent.com/4844938/194415694-4e91e6df-c0d9-4053-a770-94b5172031d0.png)

As you can see.. that ain't right.

**Comment by Bilgamesh** [comment]
Top right corner of the map looks fine in my game when I load the same save. I have also just re-installed 1.8, loaded my save there and the map looks fine.
![image](https://user-images.githubusercontent.com/24696613/194417419-db47b325-6304-467c-a646-0e130b14ea0a.png)

**Comment by Lexx2k** [comment]
Fixed https://github.com/rotators/Fo1in2/commit/e80b50ccb9836644714bcb5a9a90308330a6d983
