### ISSUE TITLE
Wrong mods for 10mm AP?

### ISSUE THREAD

**Issue by burner1024** [rotators/Fo1in2#15]
So I tried setting `DamageFormula=0` to get F2 defaults, but somehow 10mm AP parameters all all wrong:

![Captura de pantalla de 2020-01-05 02-53-57](https://user-images.githubusercontent.com/1279852/71770986-acc54300-2f66-11ea-888e-327b0b07548b.png)

That's the latest release.

**Comment by Lexx2k** [comment]
Ugh. I'm guessing this is another Fixt change that went past the radar. Now I wouldn't be surprised if other ammo stats were changed as well.

**Comment by burner1024** [comment]
Fixt? Did you start from it? I thought it was a fresh one.
Either way, I think there's probably no need to ship weapon/ammo/armor protos in the first place, as they are pretty much the same in both games (maybe except that turbo plasma rifle).

**Comment by Lexx2k** [comment]
This mod is based on the last available Fo1in2 sources, somewhere around 2015, which included or was based on Sduibek's Fixt2 which is pretty much just converted Fo1 files as far as I am aware now.

I'll sort through the item protos once I have some more time. I know that some were tweaked in other patches / fixes and they should remain in the game.

**Comment by Lexx2k** [comment]
Did some cleanup on the proto files. https://github.com/rotators/Fo1in2/commit/b17a43da6584a664ac5955d799a7bf45ee647ff1
