### ISSUE TITLE
Missing party members checks

### ISSUE THREAD

**Issue by Thrax-x** [rotators/Fo1in2#150]
party.h, there is missing line:
                                                    How_Many_Party_Members_Are_Injured+=1;      \
between lines 86-87:
                                                if (Is_Injured(Rae_ptr)) then                   \
                                            if (Vasquez_In_Party) then                          \

V13CAVE.ssl, line 130:
There are checks for Ian, Katja, Tycho, Dog and MrHandyC, but there are missing checks for Eyebot, Tandi, Rae and Vasquez

MBVATS.ssl, line 105:
There are checks for Ian, Dog, Tycho, Katja, Tandi, MrHandyC, Eyebot and Vasquez but there is missing check for Rae

GARL.ssl, line 332:
There are checks for Ian, Katja, Tycho, Dog, Tandi, MrHandyC and Eyebot but there are missing checks for Rae and Vasquez 

HHOOKERA.ssl, line 337:
There are checks for Ian, Dog, Tycho, Katja and Tandi but there are missing checks for MrHandyC, Eyebot, Rae and Vasquez

Rae/Vasquez are limited to Cathedral/Junktown, so they don't belong to any of these ssl files ?

**Comment by Lexx2k** [comment]
Rae and Vasquez are temporary followers, they will never be in those situations.

V13Cave doesn't matter, the current party members are only there to make stuff a bit more pretty.

HHOOKERA is borderline, but I think it doesn't really matter.

**Comment by Thrax-x** [comment]
party.h - I've found another missing check for Eyebot being in invasion location - lines 558-574

V13CAVE.ssl - Code seems to be used for hiding party members during final final conversation with overseer. You can complete game with Tandi in party, co check for her can be here.
MBVATS.ssl - Check for Vasquez is obsole here, because he can't get to Military base?
GARL.ssl - OK
HHOOKERA.ssl - Eyebot and MRHandy aren't human, probably OK

**Comment by Lexx2k** [comment]
The code in V13Cave just puts them into a nicer place, that's all it does. If a party member isn't mentioned there, he will just pop up around the player like they usually do (and how they are doing it in vanilla Fo1).

**Comment by Lexx2k** [comment]
Fixed https://github.com/rotators/Fo1in2/commit/b5ae77c5b354c59e348fe0fef370d39a4aefb11c
