### ISSUE TITLE
Resting until 08:00 (Fo2-style) doesn't seem to work?

### ISSUE THREAD

**Issue by Lrflx** [rotators/Fo1in2#154]
At least after enabling it, creating a character and starting a new game I still have only old "until 6:00" option present

**Comment by Lexx2k** [comment]
You need to restart the game after saving. Once you load the savegame, it will be there. There is no other way to do this right now.

**Comment by Lrflx** [comment]
I think I got it, thanks for the tip! Though cause it's kinda not 100% straightforward maybe it'd be better to add some adititional info about it to the config file in next versions
