### ISSUE TITLE
Can't get into the Vault 13 armory after giving the water chip

### ISSUE THREAD

**Issue by phobos2077** [rotators/Fo1in2#155]
Before talking to the overseer, there's an option to convince Vault 13 officer to let you have the weapons. After though, the dialogue just ends with her thanking you without any options. 

Not sure if this can be considered a bug though, maybe a design oversight :)

**Comment by Lexx2k** [comment]
I wouldn't call it a bug, since the only reason you get access to the armory in the first place is for your task to find the water chip.
