### ISSUE TITLE
Robot parts weight issue

### ISSUE THREAD

**Issue by phobos2077** [rotators/Fo1in2#156]
Something really weird happened. After clearing up the Glow I took one Robot Parts item from one of the robots (each big robot had one). When picking up this item, it weighted 10 pounds. I put it in Ian's inventory and went on. Later I realized I can't put anything into Ian's inventory, because he has around 400 pounds of weight! It turns out this item now weighs 300 pounds.

 Looking at the proto files, it seems it indeed weighs 300 and the mod doesn't even change this file. So how did it weight 10 pounds before and how did it change? Script issue?

**Comment by Lexx2k** [comment]
Uhhh, what robot parts?

**Comment by phobos2077** [comment]
Lol, nevermind. This is a bug of CorpseDrop mod. It modifies proto value by script, but only when something is killed. But it should be done on load also.
