### ISSUE TITLE
Yellow forcefields re-enable after re-load (Military Base)

### ISSUE THREAD

**Issue by phobos2077** [rotators/Fo1in2#158]
In Military Base:
After loading a save where I disabled yellow force fields, they are enabled again.

**Comment by Lexx2k** [comment]
That's normal, you can't permanently disable them.

**Comment by phobos2077** [comment]
I mean I disabled them via console on level 1, it seem to be permanent until I reload.

**Comment by Lexx2k** [comment]
Fixed https://github.com/rotators/Fo1in2/commit/4619e1faff8ebef49889a901b50eace1343e6d5f
