### ISSUE TITLE
Pickup-able part of cabinet in Hub - Merchants map

### ISSUE THREAD

**Issue by abiel0530** [rotators/Fo1in2#159]
First building on the right has a bookshelf with seemingly two parts, one a normal container, and one is able to be put into inventory.

![unmodified](https://user-images.githubusercontent.com/38668028/208499982-b6b2735e-e59f-4117-aa69-eace0905b5c3.png)
![pickup cabinet](https://user-images.githubusercontent.com/38668028/208499953-92b32907-7194-4b00-b9fb-0922cfcaf22a.png)
![ta-da](https://user-images.githubusercontent.com/38668028/208499968-ed08cbe5-3ead-49c2-968d-662705819670.png)
![inventory](https://user-images.githubusercontent.com/38668028/208499918-82c68fda-1def-4476-90d6-d3dc83c2f64f.png)

**Comment by Lexx2k** [comment]
Can't reproduce. Likely an issue in your savegame.

**Comment by Lexx2k** [comment]
I'm guessing you are using some cheat mod that increases inventory size? That would explain why you can pick up those objects.

**Comment by abiel0530** [comment]
Ah yeah, using the one in FO2Tweaks for expanded inventory. 

Acknowledged, and thank you for the explanation!
