### ISSUE TITLE
wrong number of ranks for Night Vision

### ISSUE THREAD

**Issue by FyiurAmron** [rotators/Fo1in2#160]
see https://fallout.fandom.com/wiki/Night_Vision - supposedly, it's 3 ranks in FO1

yet we have https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/config/Perks.ini#L75 - which is 1 rank (just as in FO2, so basically the default anyway)

**Comment by FyiurAmron** [comment]
@Lexx2k FWIW, there's one thing more, can't say if the current voodoo handles that right or wrong. According to wiki:

>Also only in Fallout, in dark indoor areas or outdoor areas at night-time, this results in an increase in monitor brightness and ranged weapon accuracy. The perk increases ranged accuracy by 15%, and possessing all three levels increases ranged accuracy by 30% in total.

I'm not sure if that should be "The perk increases ranged accuracy [in dark] by 10%, and possessing all three levels increases ranged accuracy by 30% in total." instead, but I guess this effect is present only in FO1 and is parallel to the usual darkness reduction present also in FO2.

And then there's this discussion about it: https://steamcommunity.com/app/38410/discussions/0/154644045360931328/

I'd be more than grateful for someone more knowledgeable than me clarifying this one.

**Comment by Lexx2k** [comment]
The wiki is stupid (as it often is). There is no extra accuracy or indoor/outdoor differentiation. All the perk does is make the night brigther, which in return means you get a better hit chance.
