### ISSUE TITLE
Problems with GOG version?

### ISSUE THREAD

**Issue by junglized** [rotators/Fo1in2#161]
Hi all,

I installed both Fallout 1 and 2 from GOG in Luris (Linux Mint). Ot their own they work just as expected.

Then I unpacked Fallout1in2 to Fallout 2 installation folder, run undat.exe through Wine interface in Lutris and chose appriopriate paths as per manual.

I chose fallout2.exe residing in Fallout1in2 folder as game launching file.

After game starts I get intro and then this:

![image](https://user-images.githubusercontent.com/26525585/209221077-31330ceb-3717-477a-a7ad-59158f4e12ad.png)

When I choose New Game Fallout 2 starts as per ususal, no sign of Fallout 1.

Is there anyting I'm doing wrong?

Cheers.

**Comment by Lexx2k** [comment]
GOG version runs fine, I used it in the past. Your issue is likely related to linux/wine and Sfall. Not much I can help with that, but you should be able to find information about it via google.

**Comment by junglized** [comment]
> GOG version runs fine, I used it in the past. Your issue is related to linux/wine and Sfall. Not much I can help with that, but you should be able to find information about it via google.

I must have made Fallout installation "dirty" by installing Fallout Fixt first and then uninstalling it before installing Fallout1in2. I uninstalled everuthing, performed fresh installs of both Fallout 1 and 2 et voila, works as expected.

Sorry for bothering you!
