### ISSUE TITLE
Autistic supermutant at Master's base entrance?

### ISSUE THREAD

**Issue by phobos2077** [rotators/Fo1in2#162]
He's not attacking, has no description and is not talking.

![scr00004](https://user-images.githubusercontent.com/4744345/209407150-516fa65d-9e43-4a52-8609-64f6df5fbf46.jpg)

**Comment by Lexx2k** [comment]
Can't reproduce, works fine for me. 
![scr00003](https://user-images.githubusercontent.com/4844938/209408353-881a21dc-86df-4ef9-b054-411b96516e3f.png)
