### ISSUE TITLE
Couldn't find/load text fonts

### ISSUE THREAD

**Issue by dangorochimaru** [rotators/Fo1in2#163]
I have fresh installs of FO1, FO2, and FO 1in2 from Epic Games, and all of them are able to launch except FO 1in2, which gives a "Couldn't find/load text fonts" error. Is this a fixable problem, or is it a problem with my installation being from Epic Games? Thank you.

**Comment by dangorochimaru** [comment]
> I have fresh installs of FO1, FO2, and FO 1in2 from Epic Games, and all of them are able to launch except FO 1in2, which gives a "Couldn't find/load text fonts" error. Is this a fixable problem, and if so, please help, or is it a problem with my installation being from Epic Games? Thank you.

**Comment by Lexx2k** [comment]
Epic fucked up the folder structure. 
https://www.reddit.com/r/classicfallout/comments/ztx369/fallout_et_tufallout1in2_could_not_findload_text/

**Comment by dangorochimaru** [comment]
Thank you so much for the fast response, and yes it does work now!
