### ISSUE TITLE
Radscorpion poison damage

### ISSUE THREAD

**Issue by Thrax-x** [rotators/Fo1in2#164]
Radscorpion damage was changed in this commit:
https://github.com/rotators/Fo1in2/commit/cec1cdba59da883da8c57f63d23d353862f25b96

It seems the damage in script is swapped. The small radscorpions do 12-24 poison, all greater radscorpions do 1-6.
I don't know how exactly test this, I put the small scorpion in V13cave map, got poisoned once, went out, travelled 3-5 hours and then I checked the HP. I did this few times and then I tested it again with normal radscorpion.

**Comment by Lexx2k** [comment]
That's on purpose. The smaller scorpions have less hp, but much stronger poison.

**Comment by Thrax-x** [comment]
I know this happens in the real world that the young ones don't know how much poison to use. I didn't know this game keeps the reality so much. :-)

**Comment by Lexx2k** [comment]
Well, it's mainly just to make them a little special. I didn't want to replace the shady sands scorpions, and when you meet them out in the wild, even normal rad scorpions aren't much a big deal anymore, so introducing another, weaker variant becomes kinda pointless. Additionally to that, poison damage in the vanilla game is so weak, you can just ignore it at all times, so it's a good moment to add (optional) content that packs a bit more of a punch.
