### ISSUE TITLE
point-blank party member attack distance?

### ISSUE THREAD

**Issue by Owyn** [rotators/Fo1in2#165]
not sure if bug but it looks like it, my party member has a pistol but only shoots enemies point-blank, he refuses to attack from the distance for some reason so he first comes point-blank to the enemy then shoots his pistol

![image](https://user-images.githubusercontent.com/1309656/214852524-52841baa-29aa-4d68-9147-49a9f8081d48.png)

**Comment by Lexx2k** [comment]
It's too dark there and the hit chance is too low, so they get closer. Not a bug.

**Comment by Owyn** [comment]
But I myself can shoot from a distance just fine there in the dark tho? Why is my NPC so different?

**Comment by Lexx2k** [comment]
The NPC has different skill and special stats than you.

**Comment by Owyn** [comment]
I've set him to "Snipe" in Combat Controls and now he shoots just fine even at night, even more accurate & far than me

It's just the default is weird for some reason I think

Tho "always burst" option doesn't seem to work, he still mostly shoots with singles

**Comment by Lexx2k** [comment]
AI stuff is engine related, it works exactly as in Fo2 base game - we didn't do any changes there.
