### ISSUE TITLE
NPCs in Maltese Falcon join Lorenzo in combat

### ISSUE THREAD

**Issue by jvs3** [rotators/Fo1in2#166]
This occurs in the Hub after attacking Decker and Kane with the Sherrif. If you talk to Lorenzo from the Friendly Lending Company twice after killing Decker he attacks you.

The problem is that the people in the Maltese Falcon join the fight on the side of the Friendly Lending Company. This was not the case in the original game as far as I remember. Story wise it also doesn't make a lot of sense since even the non employees join and the employees don't have much incentive with Kane and Decker gone.

An additional problem is that after you end combat the people in the locked rooms of the Maltese Falcon keep immediately restarting combat. This happens only sometimes and seems dependent on if you came close enough in the initial fight. Unless you have a lockpick you can't unlock the doors and the map becomes  unplayable.

I would expect the NPCs in the Maltese Falcon to only turn hostile if directly attacked. Even if you attack Kane in the original game the NPCs used to ignore this.

Savegame after killing Decker and before attacking Lorenzo:
[SLOT10.zip](https://github.com/rotators/Fo1in2/files/10519030/SLOT10.zip)

**Comment by Lexx2k** [comment]
Is fixed in the next release.
