### ISSUE TITLE
Gifted trait disables tag-skill starting items

### ISSUE THREAD

**Issue by lean-mog** [rotators/Fo1in2#167]
I was trying to make an OP HtH character with the Gifted trait, but I noticed I wasn't starting with my brass knuckles (or lockpicks, for that matter). Tried making the same character without Gifted and the tag-skill items appeared as normal.

Tested this some more by making several different characters and even loaded up original FO1 to make sure this wasn't vanilla behavior I wasn't aware of.

GVAR_IRONMAN_MODE=0 is set in fo1_settings.ini so that shouldn't be affecting it either.

**Comment by Lexx2k** [comment]
It has nothing to do with the giftet trait, but the way the inventory item loads. This is also already fixed in the next version.

**Comment by Lexx2k** [comment]
Gifted trait reduces your skill %, thus you likely landed under the threshold for the tag-items (just tagging a skill isn't enough).

**Comment by Lexx2k** [comment]
Actually Fixt changed the skill formula. Will fix it.
