### ISSUE TITLE
death screen subtitles are blocky and arroyo message still present

### ISSUE THREAD

**Issue by jvs3** [rotators/Fo1in2#169]
I found two issues with the death screen.

The death screen can still show the message about Arroyo, this is the first screenshot below. The second screenshot shows a message about Vault 13 so the newly added messages also work.

The subtitles in the death screen are shown blocky. This is the case with DeathScreenFontPatch=1 (first two screenshots) or DeathScreenFontPatch=0 (last screenshot) in ddraw.ini

Some other settings which may be related:
ddraw.ini
HiResMode=1
Mode=4 (tested with 0 and didn't change anything)

f2_res.ini
GRAPHICS_MODE=2 (tested with 0 and didn't change anything)
SCR_WIDTH=1920
SCR_HEIGHT=1080
SCALE_2X=1 (tested with 0 and didn't change anything)
COLOUR_BITS=32 (tested with 8 and didn't change anything)

![Screenshot_20230129_175646](https://user-images.githubusercontent.com/3510562/215342995-5b29d3a9-21ff-479b-91bf-5464b686bbc2.png)
![Screenshot_20230129_175736](https://user-images.githubusercontent.com/3510562/215343008-519bcf39-96d0-4243-a25e-538f881601a4.png)
![Screenshot_20230129_175901](https://user-images.githubusercontent.com/3510562/215343010-46351aa5-08f6-4888-9388-f5fb24273fbd.png)

**Comment by Lexx2k** [comment]
Already fixed with the next update.
