### ISSUE TITLE
Changing "player encounter"-map

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#17]
In Fo2 when the player is on the worldmap and enters a local map on his own, the game will always load map [000] (from [Maps.txt](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/mods/fo1_base/data/Maps.txt)), which is a desert terrain.

To get the intended Fo1 behavior, I have added a map script to map 0 that checks the current terrain and then teleports the player into the correct terrain-based map (desert, mountains, etc). This works, but on some hardware the transition between these maps is noticable.

It would be good if we could override the default map 0 with a custom one (read/write byte?) to circumvent this and move the player into the correct map right from the beginning.

We are already tracking the player on the worldmap in gl_worldmap.ssl, so additionally overriding the default "player encounter"-map on the run would be a non-issue. We just need to be able to override it.

(If current terrain == mountains then set map 000 to mountains, etc)

**Comment by FakelsHub** [comment]
It is necessary to issue it in the form of a script hook.  Which I have in the [TODO](https://github.com/FakelsHub/sFall-Extended/projects/2) sheet.

**Comment by Lexx2k** [comment]
This is implemented now with https://github.com/rotators/Fo1in2/commit/592b5c10bce332e66233ba0763a9bb9058362be6
