### ISSUE TITLE
The Military Base issues

### ISSUE THREAD

**Issue by Owyn** [rotators/Fo1in2#170]
blowing up a yellow forcefield with an explosive just makes it flicker for 0.5 sec while saying that it was temporarily disabled

hacking 1st floor computer and setting AI to exterminate large pests doesn't make robots attack mutants

"Flip" mutant (lover of Sarah in the jail cell) attacks you on sight (not sure about this but probably shouldn't be so)

**Comment by Lexx2k** [comment]
1. Need to know what force field.

2. Normal. However, this is improved with the next release.

3. Normal.

**Comment by Owyn** [comment]
1. I tried it on this yellow forcefield with my white (C4?) explosive 
![image](https://user-images.githubusercontent.com/1309656/215543809-2ac388b8-1e22-4d9f-83d5-b101e0707470.png)

**Comment by Lexx2k** [comment]
Your traps skill isn't high enough. The skill-roll failed and you just temporarily disabled the force field.

**Comment by Lexx2k** [comment]
Scripts were changed with the v1.9 release.
