### ISSUE TITLE
Super Sledge item missing from the shop

### ISSUE THREAD

**Issue by Owyn** [rotators/Fo1in2#171]
I checked Jackob's shop multiple times and it wasn't being sold there

I have F2 restock option enabled if it's affecting anything

https://fallout.fandom.com/wiki/Super_sledge_(Fallout)

**Comment by NovaRain** [comment]
Not a bug, in et tu merchants don't put their own equipped weapons into the shop list when entering the barter.

**Comment by Lexx2k** [comment]
Yes, the Sledge being sold in the Hub is a bug that got fixed. The only way to get it is from the Brotherhood of Steel.
