### ISSUE TITLE
Robodog healing

### ISSUE THREAD

**Issue by Thrax-x** [rotators/Fo1in2#172]
Robodog mod changes Dogmeat's model only.
Dogmeat can still be healed by FA and Doctor skill, but not by the Repair skill.
Healing by Tool is functional.
FA and Doctor skills can be blocked in script, but Dogmeat can't be targeted with the Repair skill.

There is also bug in Procedure Heal_Robo, Skill_speech check instead of Skill_repair.

**Comment by Lexx2k** [comment]
Robodog is technically not a robot. You can use tools on him to trigger healing, but the skill-healing is only via first aid / doctor. It's the same in vanilla Fo2 with the Cyberdog.

Why it's using the repair skill as base is odd and I have no idea why. Isn't necessarily a bug, but still... Changing it to repair feels to make more sense.
