### ISSUE TITLE
Starting game with Unarmed tagged doesn't give brass knuckles

### ISSUE THREAD

**Issue by mutantant** [rotators/Fo1in2#174]
As far as I can tell, brass knuckles are provided in vanilla by default when Unarmed is tagged. As of now, I don't see that happening in Fo1in2. Unarmed tag just spawns the default general items, no brass knuckles, making an unarmed run quite difficult to start.

**Comment by Lexx2k** [comment]
https://github.com/rotators/Fo1in2/issues/167
