### ISSUE TITLE
Forcing credits music to play earlier

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#18]
The game title track ("A Kiss to build a dream on" / AKISS.acm in Fo2) will start playing once the credit screen is visible. However, in Fo1 the music starts earlier: once the vault dweller movies are playing.

[Example here](https://www.youtube.com/watch?v=J4D-x2jSLmA&feature=youtu.be&t=283).

As far as I am aware, there currently is no way of playing music earlier - and if there is, then it likely will collide with the music from the credits... because it would have to blend into the next following ambient music track.

No idea what to do about it. It's not a super serious issue, but watching the player character walk away with nothing but silence over it is kinda shitty.

**Comment by FakelsHub** [comment]
Me need saved game before the end. There is?

**Comment by Lexx2k** [comment]
This should work:
[SLOT01.zip](https://github.com/rotators/Fo1in2/files/4075035/SLOT01.zip)

Just exit the map and the Cathedral will blow up. Walk a bit on the worldmap and you get teleported back to V13.

**Comment by FakelsHub** [comment]
> Best case scenario would be if we could add in a play_music("akiss.acm") before playing the videos with play_gmovie() and everything else happens on its own. :>

Try sfall play_sound for mp3 miusic.

**Comment by Lexx2k** [comment]
`play_sfall_sound` gives me a warning message about ActiveMovie Window: "The file c\Windows\ehome\ehtrace.dll" is invalid" etc. After that a memory error closes the game.

**Comment by NovaRain** [comment]
AFAIK EAX support has been removed since 2.1a, `set_eax_environment()` doesn't exist in sfall anymore.

**Comment by FakelsHub** [comment]
>play_sfall_sound() gives me a warning message about ActiveMovie Window: "The file c:\Windows\ehome\ehtrace.dll" is invalid" etc. After that a memory error closes the game.

Need repair your system. :-)

**Comment by FakelsHub** [comment]
In which script does End Game occur?

**Comment by FakelsHub** [comment]
I found the end macro.

**Comment by FakelsHub** [comment]
Will need to make F1 implementation for the `endgame_movie' function.
Wait....

**Comment by FakelsHub** [comment]
Will need to make own (F1) implementation for the `endgame_movie' function.
Wait....

**Comment by Lexx2k** [comment]
Ok. Thanks.

**Comment by FakelsHub** [comment]
Did as in F1, this will need to be removed.
```                                    if (dude_is_male) then
                                       play_gmovie(WALKM_MOVIE);
                                    else 
                                       play_gmovie(WALKW_MOVIE);```

**Comment by Lexx2k** [comment]
This is implemented now with commit https://github.com/rotators/Fo1in2/commit/37377bb3bb74a266e36865b23175f6f4c2ef4914
https://github.com/phobos2077/sfall/commit/f57564c9ed76cdbe0ca908fe49232702c07b1a3d
