### ISSUE TITLE
"Game initialization failed!" after vanilla installation without config changes

### ISSUE THREAD

**Issue by Tojaw** [rotators/Fo1in2#181]
I am using Windows 11 (10.0.22631 Build 22631). The games were purchased on Steam.

After a fresh install of the mod following the ReadMe, I tried starting it using the Fallout2.exe. Upon first starting it, I was asked whether I want to disable Mash's patch. The choice doesn't matter. Afterwards, the game opened in fullscreen and the "Please stand by" screen appeared. After a few seconds, I got a black screen with a loading cursor. Only after Alt-Tabbing I was able to access a small error message window saying "Game initialization failed!" and was able to close it and the game.

So far I was unable to find the root of the issue.

**Comment by Lexx2k** [comment]
What language version are you using?

**Comment by Tojaw** [comment]
Sorry for the delay, I wasn't at home. I haven't tried to manually set a language yet. The vanilla Fallout might be set to German since I'm in Germany, but I haven't tried starting it yet, I immediatly tried using F@2 instead.

Changing the graphics mode to Windowed (usually the most stable) didn't help either, now the error simply appears in front of the game. I also tried disabling the sfall high-res mode, but to no avail.

**Comment by Lexx2k** [comment]
If you are using the german version, you have to change language to "german" in the fallout2.cfg and also enable the fo1_german mod. Else the game will probably crash on startup because it can't find necessary text files.

**Comment by Tojaw** [comment]
I'm sorry, I only kinda realized I should check the language of my base game when you mentioned it. Apparently it was the German version, because now it works flawlessly. I might look up how to change languages for Steam games (if that's possible at all). Thank you very much.

I'd also suggest adding a line after the install instructions that the mod language needs to match the game language. Currently it's not mentioned anywhere in the ReadMe that the language packs are obligatory.
