### ISSUE TITLE
Can't progress further than "Accepted" Reputation in Junktown

### ISSUE THREAD

**Issue by Apoqalipto** [rotators/Fo1in2#184]
Did all the quests by following "honorable" approach. Brought down Gizmo, brought Skullz Gang to justice without violence etc. No matter what, cant progress further than "Accepted" reputation in Junktown.

**Comment by ThatGuyFromReZero** [comment]
Same. It's probably because there aren't enough worthwhile sidequests to get lots of positive karma. It is what it is.

**Comment by Lexx2k** [comment]
Town reputation is more of a side thing. I've added it only in few places and there was no balance pass done on anything related to it.

**Comment by NovaRain** [comment]
According to the script source it should be possible to get the "Idolized" town reputation in Junktown.
From the outcome of town quests/events:
* Kill Gizmo: +10
* Bust the Skulz gang with violence (bar fight): +5
* Rescue Sinthia: +5
* Help the relationship between Saul and Trish: +1

Without the action of killing NPCs itself involved, one can get 21 town rep points, which should give the "Liked" town reputation (>= 1: Accepted, >= 15: Liked, >= 30: Idolized)

And killing an "evil" critter gives 2 rep points if the player deals the killing blow, so you have Gizmo, Izo, the raider taking Sinthia as hostage, Vinnie and three generic Skulz to kill if following the quests above (and no, killing Kenji doesn't give town rep), so you need to be quick/lucky enough in combat to deal the killing blow to those evil NPCs.

The rest of NPCs are pretty much "good" critters, including Doc Morbid (killing him give positive karma, but negative town rep).
