### ISSUE TITLE
Runs extremely slow

### ISSUE THREAD

**Issue by G-Creature** [rotators/Fo1in2#185]
The game is pemanently stuck in graphics mode 0 and I believe this might be causing it to run extremely slow, roughly 5 fps per second. None of the .ini files affect it.
![image](https://github.com/rotators/Fo1in2/assets/48366856/bf8e40dd-fadf-4e21-be27-d8e837710d92)

**Comment by Lexx2k** [comment]
Change graphic mode in ddraw.ini / f2_res.ini and not the ingame menu.

**Comment by G-Creature** [comment]
> Change graphic mode in ddraw.ini / f2_res.ini and not the ingame menu.

You can't change the graphics mode in the menu. I did it through the .ini files. It doesn't work.
![image](https://github.com/rotators/Fo1in2/assets/48366856/af2ef7c6-16af-488d-af35-433a6f7c52c3)
![image](https://github.com/rotators/Fo1in2/assets/48366856/d4fa8d7f-6a0d-4036-a1df-4099da38754a)

**Comment by Lexx2k** [comment]
I just checked ingame and I don't have the graphics menu anymore at all. Maybe switch to the Sfall hi-res patch instead.

**Comment by G-Creature** [comment]
> I just checked ingame and I don't have the graphics menu anymore at all. Maybe switch to the Sfall hi-res patch instead.

Same issue, it runs at single digit fps. I did a fresh install of both games and followed all installation instructions to the letter. It doesn't work.

**Comment by G-Creature** [comment]
It's like it doesn't recognize portions of the .ini files at all. I can change the resolution, but the DX9 or 7 or basic is not affected by any of the files. It also doesn't seem to recognize any of the sfall settings like highlighting corpses or containers.

**Comment by G-Creature** [comment]
Vanilla Fallout 1 and vanilla Fallout 2 appear to run just fine, btw. There is something strange happening with this specific mod.

**Comment by Lexx2k** [comment]
We are using various scripts to replicated Fo1 behavior. Dunno, maybe your hardware isn't up to it. Since you didn't mention any details, this could be whatever.

**Comment by G-Creature** [comment]
> We are using various scripts to replicated Fo1 behavior. Dunno, maybe your hardware isn't up to it. Since you didn't mention any details, this could be whatever.

What details do you need? Here is the basic rundown of the hardware:
![image](https://github.com/rotators/Fo1in2/assets/48366856/f65c769e-69ba-4213-bc8a-958d92d99801)

**Comment by Zek99** [comment]
Same issue. i7-9500k, RTX 2070. Using Xbox game pass Fallout 1 and 2.

When the game is started with Mash's hi-res mod thing the graphics menu can be chosen.

![image](https://github.com/rotators/Fo1in2/assets/1511039/4b0e6945-254a-4f6f-8476-ae2f3e233568)

When disabled it jumps straight to game settings.

Will continue poking around in configs.

**Comment by Zek99** [comment]
Set `GRAPHICS_MODE=1` or `GRAPHICS_MODE=0` in `Fallout1in2/f2_res.ini` and it doesn't run at 5fps.

**Comment by Zek99** [comment]
Also occurs for the GoG installs so its not unique to the Xbox game pass versions.

**Comment by NovaRain** [comment]
Have you checked if your graphics driver automatically set a fps limit to the game?
