### ISSUE TITLE
Exploding Garl break game (?)

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#186]
(From player which most likely don't have account here)

Planting bomb on Garl (2238 style!) might lead to game not responding to keypress [after early explosion](https://cdn.discordapp.com/attachments/1008018594359152662/1153672765203828868/rn_image_picker_lib_temp_e71e677a-a0df-4159-b8c2-a566512a6a1a.jpg) due to low skill.
After events seen on screen, player wasn't able to do anything using mouse/keyboard without restart.

v1.8 release, looked like proper install (judging by Shady Sands roofs)

**Comment by Lexx2k** [comment]
Need repro and savegame I guess, else nothing will come out of this.
