### ISSUE TITLE
Shady Sands buildings are all glitchy

### ISSUE THREAD

**Issue by suxel33** [rotators/Fo1in2#189]
Shady sands building are corrupted.  
![error](https://github.com/rotators/Fo1in2/assets/19918635/6d906591-706e-41d9-87e6-a4114f0637de)

**Comment by Lexx2k** [comment]
You did not follow the installation instructions correctly. https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/README.md#mod-installation

**Comment by suxel33** [comment]
god im stupid my apologies
