### ISSUE TITLE
Game crashes when delivering pulse grenades to Sophia

### ISSUE THREAD

**Issue by ThatGuyFromReZero** [rotators/Fo1in2#190]
So I take the quest to give Sophia pulse grenades, I give them to her and the game crashes with this error message. I even did a clean re-install and it still behaves this way.
Error message below:
![SophiaPulseGrenadeDeliveryBoSCrash](https://github.com/rotators/Fo1in2/assets/147804585/9a54e153-062b-4f26-ba22-9acf8c02106f)

**Comment by mz1193** [comment]
I can confirm this, I had the same thing happen. I thought it may have been a problem on my end at first, but this report seems to contradict that.

**Comment by ThatGuyFromReZero** [comment]
I'm glad I'm not the only one experiencing this issue. Is there a way to
make Fallout 2 tweaks to also work with this mod? I can't seem to figure
out what the problem is. I really want to give my character virtually
unlimited carry weight so I can take as much loot as possible from places
like the military base and the cathedral.

**Comment by NovaRain** [comment]
How about uploading a save before delivering the grenades?

**Comment by ThatGuyFromReZero** [comment]
I'll see what I can do. Oh wait, I can't upload saves. GitHub won't allow
me. I'll need an email for that.

**Comment by Greg1938** [comment]
I have the same bug. I've enclosed saved game files immediately before getting the grenades, and delivering them.
[Sophia Bug.zip](https://github.com/rotators/Fo1in2/files/13258608/Sophia.Bug.zip)
(I hope I did it right.)

**Comment by NovaRain** [comment]
OK, I found the cause. Replace `sophia.int` script with this one: [sophia_fix.zip](https://github.com/rotators/Fo1in2/files/13258774/sophia_fix.zip)

**Comment by ThatGuyFromReZero** [comment]
It works! Thank you so much! We just need it on the future versions and all will be well!

**Comment by Greg1938** [comment]
@NovaRain Cool.
