### ISSUE TITLE
Talking heads are black screens

### ISSUE THREAD

**Issue by lagerea** [rotators/Fo1in2#191]
Fresh install, GOG, followed by 1 in 2 the talking heads don't work either before or after disabling the mash hi-res patch. All I see is the text but not the head, only a blank black square for the area.

**Comment by NovaRain** [comment]
Try using DirectDraw7 graphics mode instead of DX9 set by default in 1in2.

**Comment by Lexx2k** [comment]
You dididn't follow the installation instructions correctly. 

https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/README.md#mod-installation
