### ISSUE TITLE
Steam Deck

### ISSUE THREAD

**Issue by cookoko** [rotators/Fo1in2#192]
Ok, so this is the third time reinstalling the game and making sure I've done everything correctly so Idk what's wrong. My 
character moves soooo slow. Not walking, but as if the player is moving at 1 fps. Any tips? Menus, videos, loads, etc are fine but as soon as I get in the game it's like the game goes to 1 fps. Any tips? Fallout 1 vanilla, fallout FIXT, fallout 2 vanilla, fallout 2 RP mod all run fine on my pc, just this mod is giving me performance issues. 

Also, Sorry GiHub is confusing to me don't know where to put this next question. It's not exactly an issue but I want to prevent a possible issue. I'm about to get wine for my Steam deck, do I need to install et tu on my steam deck OR since I already have my modded Fallout 2 (rpu and et tu) on a flashdrive can I just transfer them on the deck without worrying about doing the undat.sh thing in the installation instructions without wine? I'm not familiar with Linux but I would like to play these games on the go but I'm afraid to break something and not know what to do.

**Comment by NovaRain** [comment]
Try disabling DX9 graphics mode: `Mode=0` in [Graphics] section in ddraw.ini and `GRAPHICS_MODE=1` in f2_res.ini.
