### ISSUE TITLE
Amber teaches rude player instantly

### ISSUE THREAD

**Issue by Thrax-x** [rotators/Fo1in2#194]
Amber (cut character in Boneyard Library) should teach you Outdoorsman for 7 (kind choice) or 9 (rude choice) hours.
Rude choice takes no time, because the time is defined after the "game_time_advance" command.

Bug in file AMBER.ssl, lines 162-165, correct order should be:
LVar0 := 3600 * 9;
gfade_out(1);
game_time_advance(game_ticks(LVar0));
gfade_in(1);

All her other teach procedures (Amber8, Amber11, Amber12, Amber13, Amber14) have wrong command orders too, but without affecting gameplay.

**Comment by Lexx2k** [comment]
Uh, this NPC isn't even in the game or am I missing something.

**Comment by Thrax-x** [comment]
It's not in game, but I tried to add some cut characters.

**Comment by Lexx2k** [comment]
Well, I took one look at the script and dialog and I already know I'm not restoring this. :D

**Comment by Thrax-x** [comment]
Yes, most of them are crap, but this one looks functional.

**Comment by Lexx2k** [comment]
You can restore it in a mod if you want to. Chances that I will have time or motivation to rewrite this whole thing are pretty much zero at this point.
