### ISSUE TITLE
 Crash when re-entering Vault 15

### ISSUE THREAD

**Issue by Premik** [rotators/Fo1in2#195]
Was to Vault 15 first. Then went back for the rope and now each time I enter the underground  the game crashes.

![image](https://github.com/rotators/Fo1in2/assets/842962/df2d7dca-a296-419a-878e-3207aebd7299)

To reproduce just load the saved slot and enter the ladder.
[SLOT04.zip](https://github.com/rotators/Fo1in2/files/13370423/SLOT04.zip)

**Comment by NovaRain** [comment]
I tried your save in a fresh et tu installation on Windows, and nothing happened when entering the underground.
Here's the save right after using the ladder, see if it works in your game: [SLOT05.zip](https://github.com/rotators/Fo1in2/files/13371003/SLOT05.zip)

**Comment by Premik** [comment]
Your save does not crash on my game. 
So I narrowed it down and turned out to be the  `fo1_footprints` mod. I've disabled it and now even the original save doesn't crash..
Thanks!
