### ISSUE TITLE
Repeatable Crash in Lost Hills

### ISSUE THREAD

**Issue by gphoenix51** [rotators/Fo1in2#200]
I'm getting a repeatable crash when I try to deliver the EMP grenades to Sophia in the Lost Hills Bunker. I get the quest from Michael ok, then when I try to give them to Sophia, it crashes with this error.

![EMP Grenades Delivery Quest Crash](https://github.com/rotators/Fo1in2/assets/151857699/6b433653-1689-45e1-89a6-01aeca8b8a80)

I did already have a single EMP grenade in my inventory when I got the quest, but dropping one before I talk to Sophia still got the error crash. I reloaded an earlier save and dropped my grenade before even talking to Michael the first time, before I even got the quest from him, and it still crashed. Not sure what's going on.

**Comment by Lexx2k** [comment]
https://github.com/rotators/Fo1in2/issues/190

**Comment by gphoenix51** [comment]
Sorry,  I didn't know there were solved issues elsewhere.
