### ISSUE TITLE
Game Crash after upgrading weapons at the Gun Runners

### ISSUE THREAD

**Issue by gphoenix51** [rotators/Fo1in2#201]
This one is strange. When I first got to the Gun Runners I made a save, then I went in, turned in the "Killed all Deathclaws" quest, then went over to Zack to sell off all the crap I'd gotten from the Glow. Before I did that, I upgraded all the weapons I could, several assault rifles, hunting rifles, a laser pistol and rifle. Then sold everything and made another save. When I walked out of the Gun Runner screen, it immediately crashed.
![Leaving the Gunrunners Crash](https://github.com/rotators/Fo1in2/assets/151857699/fc8e5045-7d20-48cd-b88b-c865a74a41e0)
After a LOT of testing, I managed to narrow it down to something going wrong with the upgrade system. I can buy and sell all I want. But if I upgrade too many things in one go, it'll crash. I upgraded the rifle alone, and it was fine, then the pistol, then a couple rifles and it was ok if I only did a couple things at a time. I'm including my saves from before I talked to them, after I sold my guns, and after I upgraded everything at once. That last one will always crash.
[Gun Runner Crash Saves.zip](https://github.com/rotators/Fo1in2/files/13454735/Gun.Runner.Crash.Saves.zip)

**Comment by NovaRain** [comment]
Looks like you're using the footprint mod, did you edit `CorpseDeleteTime` in ddraw.ini?

**Comment by gphoenix51** [comment]
Yeah I put it at 12 hours. Which one is causing it? Because I'll happily get rid of the footprint mod, I didn't even remember I had it on till you mentioned it. I don't notice it.

**Comment by gphoenix51** [comment]
That might explain some other crashes I had. Like one in Junktown, never could reproduce it so I never mentioned it. It happened when I went to Gizmo's screen, after I had killed him.
