### ISSUE TITLE
Party Control - Hard-coded dialog?

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#21]
Dogmeat speaks english in the party member control panel: Clicking "use best weapon" or "use best armor" will pick a random dialog line from the proto.msg file (670 to 676).

The canine companions in Fo2 are using lines 677 and 678, but as this isn't set in script, I'm assuming this behavior is hardcoded (proto based?). Also couldn't find anything in the party.txt or ai*.txt files.

In any case, as of now I don't think I can fix this on my own.

**Comment by FakelsHub** [comment]
What is the bug?  Something I don’t see.
Perhaps you need to move the dog to a different prototype number to match F2.

**Comment by wipe2238** [comment]
`write_byte(0x444D10, 0x7a);`

**Comment by Lexx2k** [comment]
Fixed via https://github.com/rotators/Fo1in2/commit/e9fdba566bf25bbb031d8a143011f05bfb2ef2b1
