### ISSUE TITLE
Any plan on supporting mac?

### ISSUE THREAD

**Issue by alvarocastro** [rotators/Fo1in2#212]
Hi, is there any plan on supporting Mac OSX?

I saw there is both [Fallout 1](https://github.com/alexbatalov/fallout1-ce) and [Fallout 2](https://github.com/alexbatalov/fallout2-ce) community editions but they seem to be just a plain reimplementation of the original games. Would love to be able to play Fo1in2 with all the improvements it has.

**Comment by Lexx2k** [comment]
This is a thing that should probably be adressed to Sfall, since we don't have a hand in that. https://github.com/sfall-team/sfall

**Comment by NovaRain** [comment]
You should be able to use [Wine](https://www.winehq.org/) to run the game with sfall on newer MacOS.
