### ISSUE TITLE
General game speed is painfully slow

### ISSUE THREAD

**Issue by aud1cted** [rotators/Fo1in2#213]
Out of combat speed of the game is painfully slow. Running, animations, everything. Even the mouse is laggyish... I'm not talking about the black screen fade outs/ins, i've tweaked it with ddraw.ini. The speed issue wasn't the case with Unofficial Patch 1.3.6F. There was an option to increase the game speed by x1.5 while installing. How can i achieve this with this version?

**Comment by NovaRain** [comment]
Check `SpeedMultiInitial` setting in ddraw.ini.
If you want to use the speed combo key (Ctrl+numpad keys), make sure you disable the numlock.

**Comment by aud1cted** [comment]
Yeah i figured it out but my problem was something else entirely. NVIDIA Control panel applied VSYNC automatically, and that screwed up the game.

Using Ctrl + Numpad 2 key makes the game very fast.

;The speeds corresponding to each slot in percent. (i.e. 100 is normal speed)
SpeedMulti0=50
SpeedMulti1=100
SpeedMulti2=200
SpeedMulti3=300
SpeedMulti4=400
SpeedMulti5=500
SpeedMulti6=600
SpeedMulti7=700
SpeedMulti8=800
SpeedMulti9=900

These are the socket lines right? For example if i want the game at 1.5 speed, i change SpeedMulti2=150 and press Ctrl + 2 right ?

**Comment by Lexx2k** [comment]
> Unofficial Patch 1.3.6F

No idea what this is, but I'm pretty sure it has nothing to do with ettu.

**Comment by aud1cted** [comment]
> > Unofficial Patch 1.3.6F
> 
> No idea what this is, but I'm pretty sure it has nothing to do with ettu.

I was referring to the TeamX's Unofficial patch 1.3.6F for the vanilla fallout 1, to describe my problem clearer, sorry if it is misplaced. After disabling Vsync and frame limiters, game runs buttery smooth. Thanks for this amazing work.
