### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by kondors1995** [rotators/Fo1in2#215]
I tried to compile the release with GitHub actions and found out that the code is broken

![image](https://github.com/rotators/Fo1in2/assets/7190697/241d2395-9efe-48aa-adc2-4207feeb5699)

**Comment by kondors1995** [comment]
Okei. stupid question then but how do I compile mod from this repo?

**Comment by Lexx2k** [comment]
Download the files, download the modders pack, use Sfall Script Editor to compile stuff.
