### ISSUE TITLE
Crash after getting chemistry journals from Stapleton.

### ISSUE THREAD

**Issue by topdawg229** [rotators/Fo1in2#216]
Whenever I pay the 750 caps for the chemistry journals once I try to leave the area the game crashes. I will include a save file for testing. This is on the newest release.
[SLOT09.zip](https://github.com/rotators/Fo1in2/files/14077727/SLOT09.zip)

**Comment by NovaRain** [comment]
I had crashes on map exit after talking to her (even if just quit the dialogue right away) and right after exiting the dialogue. Somehow in one of my attempt I brought the book and can move to other maps as normal, here's one on the Hub entrance map:
[SLOT19.zip](https://github.com/rotators/Fo1in2/files/14078235/SLOT19.zip)

**Comment by NovaRain** [comment]
OK, the culprit is, for some strange reason the two .44 JHP in Stapleton's inventory don't stack in your save, and this leads to script procedure error.
If you steal them (should stack properly in your inventory) then plant them back, everything will work just fine.

**Comment by topdawg229** [comment]
That definitely worked! Is that something other players should be concerned about or it is a fluke that only happened to me?

**Comment by NovaRain** [comment]
For now I'd take this as an one-off issue, unless someone can find a way to reproduce the glitch (and even in different environments like Windows).
