### ISSUE TITLE
Repairing the Necropolis water pump before the attack doesn't give extra experience

### ISSUE THREAD

**Issue by Aussiemon** [rotators/Fo1in2#217]
According to the [wiki](https://fallout.fandom.com/wiki/Fix_the_Necropolis_water_pump), repairing the Necropolis water pump before the attack should give 2500 experience, and only 1000 experience afterwards. In Fallout Et Tu, it always gives 1000 experience.

**Comment by Lexx2k** [comment]
I don't see any 2500 exp in the original code. https://rotators.fodev.net/wipe/ssl/fo1.vanilla.ReDefine/NH2OPUMP.ssl

**Comment by Aussiemon** [comment]
I've found some other results saying the wiki is wrong. Thanks for the source link!
