### ISSUE TITLE
Mother deathclaw has male crit messages

### ISSUE THREAD

**Issue by Aussiemon** [rotators/Fo1in2#218]
Crit message refers to her as "him":

![image](https://github.com/rotators/Fo1in2/assets/13663574/7927e121-bb43-4b38-a289-2bd2d8e3da0c)

but she has female inspect dialogue:

![image](https://github.com/rotators/Fo1in2/assets/13663574/0abc790e-1a05-45a4-a522-d89d81a7b7e5)

**Comment by NovaRain** [comment]
Some of the critical hit messages of Deathclaws are shared with "Men" critter type and don't have separate lines for different genders.
