### ISSUE TITLE
[Debug] Force specific encounter

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#22]
Don't really care how it would be enabled, i just need something to repeat specific encounter(s) over and over again on runs with debug stuff enabled. Both fluff and non-fluff should be supported.

**Comment by Lexx2k** [comment]
Well, if it's not about special encounters, then you just have to edit the encounter map scripts. The _table procedures determine which encounter will be chosen, so you can just override the variable in them and it'll always pick the encounter you want to test.
