### ISSUE TITLE
Wine - Extremely slow gameplay

### ISSUE THREAD

**Issue by Cambysses** [rotators/Fo1in2#220]
The game launches and seems fine up until the actual gameplay starts, it drops down to single-digit FPS rate. 

I've messed around with various options in `ddraw.ini` and `f2_res.ini`, setting `MODE` and `GRAPHICS_MODE` in each respectively to every possible combination, but it makes no difference.

I'm launching the .exe through Wine on Nobara Linux 39 with this terminal command: `WINEDLLOVERRIDES='ddraw.dll=n,b' wine fallout2.exe`. 

Tried running it through Proton compatibility as well but when doing that it just loads as Fallout 2 instead of 1.

**Comment by NovaRain** [comment]
See if there's a vsync or some FPS limiter being applied on the game and disable it.

**Comment by Cambysses** [comment]
Nvidia settings are more difficult to tweak on Linux but I did find this option and set it to false: 
![image](https://github.com/rotators/Fo1in2/assets/36931193/f232620e-b710-48dd-b570-c1f964751aca)

Unfortunately it doesn't seem to have made a difference. If there is any other factor limiting the framerate I don't know what it could be.

**Comment by Cambysses** [comment]
Well I'll be damned, the frame limiter worked. I installed MangoHud / GOverlay and set the frame limit to 60, immediately that fixed the slowness.

![Screenshot_20240221_185239](https://github.com/rotators/Fo1in2/assets/36931193/c68755b9-cee6-4362-96a5-3ee01044d886)

Here are my settings, for anyone in the future who stumbles onto this thread.

Much thanks. ✌️

**Comment by Cambysses** [comment]
Addendum: While the frame limiter _kinda_ worked, I was still having serious performance issues. However I discovered the true cause.

I had to **switch from Wayland to X11** for my Linux graphics engine. I have an Nvidia card and they do not play nice with Wayland at all. As soon as I switched, the game launched perfectly, butter-smooth, with no tweaks.
