### ISSUE TITLE
Installation instructions not clear for Linux or Wine, lacking the most important part (ddraw.dll override), lib requirements missing for Windows

### ISSUE THREAD

**Issue by WWWFWWW** [rotators/Fo1in2#225]
The installation instructions lack the most important part for running Fallout1in2 under Linux or Mac with Wine – setting a ddrawl.dll library override in Wine Config to native,builtin.

Without that step, Fo1in2 won't ever run properly under Wine, launching Fallout 2 data instead.

That very step might be known to somebody well accustomed to SFall as the mod authors are, but not to anybody new to Fallout 2 intricacies.

I suggest adding it to the instructions to make them complete.

Library requirements for actually running undat.exe or for dat2.exe command‑line usage are also missing. I gather some versions of VCRun or DotNet are required, but not mentioned and not installed purely by installing Fallout 1 or 2 either.

Installation instructions that already assume the presence of other, 3rd party libraries not installed by default are simply incomplete and misleading.

Please try to think like a person installing your mod on a completely new computer and OS when writing instructions, not like a dev with your dev environment already having all of them. Because when doing the latter, you will miss all the dependencies required and won't mention them.

**Comment by msegers** [comment]
@WWWFWWW  Thanks for your issue, I had no idea I needed to override a dll, finally got it to work.

**Comment by EcceGratum** [comment]
Any idea how to fix it when launching from steam on the Steam Deck ? as launch arguments maybe ?

**Comment by c10l** [comment]
For anyone coming here looking for how to do this in Steam, edit launch options as so:

```
WINEDLLOVERRIDES='ddraw.dll=n,b' %command%
```

**Comment by class101** [comment]
Adding to this a complete Steam guide, Wine is indeed unnecessary with Steam

https://steamcommunity.com/sharedfiles/filedetails/?id=3230745043

Feel free to try it, it is very easy to follow, no Linux skills required :)
