### ISSUE TITLE
A Trojan in the files

### ISSUE THREAD

**Issue by MishaGorb** [rotators/Fo1in2#227]
A trojan in drall.dll. My anti-virus was deleling this file every time i unzipped it so the whole thing was not working. I desabled the anti-virus and unzipped the files, the game started working but after few hours all the applications stopped opening, thankfully the anti-virus started to work again and it got rid of the virus and the drall.dll was gone again. Can somebody clean the file from the virus.

**Comment by NovaRain** [comment]
The `ddraw.dll` is [sfall](https://github.com/sfall-team/sfall) which is a critical component for et tu. Without it the whole et tu project wouldn't even exist. You should either whitelist the file or report it as false positive to the anti-virus company.
