### ISSUE TITLE
Unable to install properly in Epic Games version of the game without extra steps

### ISSUE THREAD

**Issue by LostandStranded** [rotators/Fo1in2#231]
Sorry; This doesn't work at all using the Epic Games version of the game. There is an error stating "Couldn't find/load text fonts" when trying to launch the Fallout2.exe Application after following the installation instructions.

**Comment by LostandStranded** [comment]
Note: I tried following a couple of reddit forums that suggested changing the reference location of some of the files to more accurately represent where they actually are, but to no avail. The issue occurs regardless of if I select yes or no to the question it asks on first launch regarding which Hi-Res texture pack should be used.

**Comment by Lexx2k** [comment]
"Couldn't find/load text fonts" means it can't find text files. Since you did give no information at all, my wild guess is that you are not using the english version of the game.

**Comment by explodingcows54** [comment]
i am using the english version and i had the same issue, funny its on the same day lol

**Comment by explodingcows54** [comment]
also i should add im using the steam version of the game and had the same issue

**Comment by Lexx2k** [comment]
And you are 100% sure that the file paths to your master.dat and critter.dat are correct? As I said, this error pops up if the game can't find the base game files.

**Comment by explodingcows54** [comment]
ok i tried reinstalling it, and it still is giving me the same error

**Comment by explodingcows54** [comment]
where are the file paths shown?

**Comment by NovaRain** [comment]
It would be easier to see what's wrong if you can post a screenshot of how your game folder is like currently.

**Comment by NovaRain** [comment]
Uh, did you extract the content of `Fallout1in2` folder in the release zip to your main Fallou2 folder?
You need to put the whole `Fallout1in2` folder, not just the content.

https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/README.md#mod-installation
* The folder structure must look like this:
  ```
  \Fallout2\Fallout1in2\Fallout2.exe
  ```

**Comment by explodingcows54** [comment]
oh! ok i did not do that

**Comment by LostandStranded** [comment]
I did follow that step properly myself, and I am using the English version of the game but my problem is likely related to how the Epic games version of the game does it's localization. Each language has it's respective files one folder down from root sorta like a mini root location for each language. I believe the files are not being properly referenced because they are in another folder in the root installation and not in the root themselves which is not what the mod expects. Here is a screenshot of a fresh install with no changes made. 
![Before edits](https://github.com/rotators/Fo1in2/assets/149903001/9790b991-412c-4d04-acab-5d9c5a9a3d2e)

The Fallout 1 folder from Epic Games is practically the same layout as Fallout 2.

**Comment by LostandStranded** [comment]
I tried removing the other language folders and extracting the contents of Fallout 2 English to the actual root folder, then changing the reference locations in the .ini (in the Fallout1in2 folder) to match but I still got the same error. I'm sure either I did something wrong or there is an issue with the mod's ability to interact with such heavily relocated files.

**Comment by russhdavid** [comment]
Hello I'm having the same issue with the Epic Game Store version of the game. After selecting the Master,dat file from: C:\Program Files\Epic Games\fallout\Fallout 1 English and running the Fallout2.exe I get the same error message.

**Comment by LostandStranded** [comment]
> Hello I'm having the same issue with the Epic Game Store version of the game. After selecting the Master,dat file from: C:\Program Files\Epic Games\fallout\Fallout 1 English and running the Fallout2.exe I get the same error message.

I got you since the devs do not seem to have an idea what is causing it. If your installation looks the same as mine above; What you need to do to get it working is to delete everything from Fallout 1 and Fallout 2 except for the Fallout1/2 English Folder. That way the only thing in Fallout 1 is "Fallout 1 English" and the only thing in Fallout 2 is "Fallout 2 English". After that you have one more step per folder. Take the contents from Fallout 1 English and bring them back one folder. Basically take them out of the "Fallout 1 English" folder so that they are in the "Fallout 1" folder instead. The same goes for Fallout 2. What you've just done is gotten rid of Epic Games Store's proprietary nonsense and now you are left with just the actual Fallout 1/2 base installations. If you follow the installation instructions from this mod from that point forward, it will work as intended right off the rip. I hope this was detailed enough to help.

**Comment by NovaRain** [comment]
Or maybe simply extract Fallout1in2 to `Fallout 2 English`? Basically Fallout1in2 must be in a subfolder to the main Fallout 2 (i.e. where `master.dat` and `critter.dat` locate).
TBH I have no idea why Epic packs the game in a different setup from Steam/GOG release.

**Comment by LostandStranded** [comment]
Its because they had different localizations of the game (Different languages) that were packed as their own separate game in the full install for some reason. For example if your primary language is German, it's installed entirely in German in the Fallout 1 German folder. It's VERY inefficient for storage purposes because you download the game 2-3 times its normal size because the localizations are all installed at once. Your suggestion to install Fallout 2 English doesn't work. That was my first thought and it backfired because the .ini can't reference the files properly since it calls to go back x amount of folders during its search. It's janky. 

I would also like to amend what I said. It's not that the mod doesn't work. It worked well. It's that it cannot dynamically locate the installation when faced with the Epic Games version (Not that it should be required to) but it would benefit from being able to do so for the benefit of people who are less apt to exploring folders to such an extent.

**Comment by LostandStranded** [comment]
Not me trying real hard to do a proper strikethough to correct the title

**Comment by NovaRain** [comment]
> Your suggestion to install Fallout 2 English doesn't work. That was my first thought and it backfired because the .ini can't reference the files properly since it calls to go back x amount of folders during its search. It's janky.

Hmm, I tried to create the same multi-layer folder structure as your Epic games, and et tu works just fine:
![subfoldery](https://github.com/rotators/Fo1in2/assets/8564973/757f840e-ef3f-4b4e-86ac-c0673841bb47)
![undat](https://github.com/rotators/Fo1in2/assets/8564973/40dc2a81-2d4f-40d4-8054-c1e291e354b1)
![scr00000](https://github.com/rotators/Fo1in2/assets/8564973/294dddc8-2bd9-4eeb-a717-0bb2240582d5)

**Comment by LostandStranded** [comment]
Strange. I would replicate and show my work, but I've already uninstalled the game, mod, and related files. I gave up on playing the first games in the series. Turns out much older games are just not for me. But if that does work for you and others then disregard me completely. This can just serve as a hail mary for anyone else who tried the EGS version and has any strangeness like myself and the other person did.

**Comment by russhdavid** [comment]
The fix is just moving the Fallout1in2 folder to the English folder in the Fallout2 installation. That fixed my issue. Thanks guys.

**Comment by russhdavid** [comment]
![image](https://github.com/rotators/Fo1in2/assets/26373771/09033510-0e45-48f3-be92-4a318a4ca0b8)

**Comment by ShadowTheLight** [comment]
> Or maybe simply extract Fallout1in2 to `Fallout 2 English`? Basically Fallout1in2 must be in a subfolder to the main Fallout 2 (i.e. where `master.dat` and `critter.dat` locate). TBH I have no idea why Epic packs the game in a different setup from Steam/GOG release.

i did this and it worked! thank you guys for figuring this out, many seem stumped by this online
