### ISSUE TITLE
ddraw.dll flagged as W32.Gamehack

### ISSUE THREAD

**Issue by KneeTattoos** [rotators/Fo1in2#232]
ddraw.dll has been flagged in Webroot. Put it into virus total and Kaspersky, Zone alarm, and Tehtris aren't happy about it either.  Could be a false positive but I thought I'd reach out just to let you guys know the findings.

**Comment by Lexx2k** [comment]
It's a false positive. Nothing we can do about that.

**Comment by NovaRain** [comment]
Please refer to https://github.com/rotators/Fo1in2/issues/227
