### ISSUE TITLE
Trying to reunite with Katja in the Mariposa Military Base crashes the game

### ISSUE THREAD

**Issue by HeksevilleHero** [rotators/Fo1in2#235]
After freeing Ian, Dogmeat and Tycho, talking them them shows a small line of text over their head before they resume following you, but if you talk to Katja, a text box appears, then the game has a high chance to crash, citing "The instruction at 004d6db5 referenced memory at 00000000. The memory could not be read from". Rarely, instead there is an option to select "Go on" in the text box, which avoids crashing the game.

This occurs on the latest version (v1.9.3324 as of typing this). Here is my save data if that helps at all.
[SLOT15.zip](https://github.com/rotators/Fo1in2/files/15159139/SLOT15.zip)

**Comment by NovaRain** [comment]
Try this script with test fix: [katja_prisoner_fix.zip](https://github.com/rotators/Fo1in2/files/15160095/katja_prisoner_fix.zip)
Extract `katja.int` to `mods\fo1_base\scripts` (better to backup the original one first). Now she should have a floating message just like other party members.
