### ISSUE TITLE
Unable to start game: Game initialization failed! - Can't open file for write sound\sfx\SNDLIST.LST

### ISSUE THREAD

**Issue by pascal-johann** [rotators/Fo1in2#236]
Hello,

I am playing with the GOG-Versions of Fallout 1 and 2 and wanted to try Fallout 1in2. But I currently can't get it to run properly.

I have a fresh installation of Fallout 1 and 2. After this I have installed Fallout 1in2. First I got some problems because I have a german installation. But after solving this I still have the `Game initialization failed!` error.

I have configured the ddraw.ini to get a debug log file:

```
Fade time is 219
Fade steps are 191
Chi squared is 23.817000, P = 36.420000 at 0.05
Sequence is random, 95% confidence.
>partyMember_init	soundInit: Setting primary buffer to: 16 bit, 2 channels, 44100 rate
soundInit: Primary buffer settings set to: 16 bit, 2 channels, 44100 rate
SFXLIST: Can't open file for write sound\sfx\SNDLIST.LST
>gsound_init	>initMovie		>gmovie_init	>moviefx_init	>art_init		>tile_init		>obj_init		>cycle_init		
 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **
>intface_init	>iso_init		>gmouse_init	
Error: Loading proto message files!Failed on proto_init
```

I have checked the folders an the file does exist and I can manually open and save it (`Fallout 2\Fallout1in2\mods\fo1_base\sound\sfx\SNDLIST.LST`)

**Comment by NovaRain** [comment]
The `sndlist.lst` has nothing to do with the initialization failed error, your problem should be from the last line `Error: Loading proto message files!Failed on proto_init`.

**Comment by pascal-johann** [comment]
Ok, I have rechecked the files and I got it working. Apparently there were problems with the zip file I downloaded. I had already tried to unpack it again, but only after a new download of the same release it worked.

Thanks for your help

**Comment by thomas001** [comment]
For the record, I saw the very same error message in the debug log file when the installed game language wasn't English.
