### ISSUE TITLE
High quality music mod and upscaled videos mod don't seem to work.

### ISSUE THREAD

**Issue by lavadrop** [rotators/Fo1in2#238]
Hi.
I'm running your mod in Linux. I installed those two mods  into the locations their readmes instruct to and modified ddraw.ini accordingly but neither work.
My system has wavpack, libwavpack1, flac, libflac12, gstreamer-plugins-good and gstreamer-plugins-good-32bit packages installed.
Setting the variable AllowDShowSound=0 plays the original music.

**Comment by egornovivan** [comment]
For music in formats other than .acm you need to set AllowDShowSound=2

**Comment by lavadrop** [comment]
Thanks for your input. The variable is set to 1. I also tried 2. No difference, I only hear sound fx. I also downloaded your version of the music from your repository and tried it and it didn't work. I also tried installing DirectShow inside the wine prefix with winetricks and it didn't work.

**Comment by egornovivan** [comment]
Do you have set dll overrides?: `WINEDLLOVERRIDES='ddraw.dll=n,b' wine fallout2.exe`

**Comment by Lexx2k** [comment]
Does the music work if you don't have the mod installed? Are you sure the file path to the music folder in the fallout2.cfg file is correct?

**Comment by lavadrop** [comment]
> Do you have set dll overrides?: `WINEDLLOVERRIDES='ddraw.dll=n,b' wine fallout2.exe`
> 
> > I also downloaded your version of the music from your repository
> 
> wma and Linux are very poorly compatible

Yes, both lutris and winecfg have ddraw.dll=n,b. F01in2 runs perfectly fine, but without music if I activate the "AllowDShowSound" variable.
I have no issues playing the wma lossless files in mplayer, vlc, ffmplay, etc.

**Comment by lavadrop** [comment]
> Does the music work if you don't have the mod installed? Are you sure the file path to the music folder in the fallout2.cfg file is correct?

The music works fine if I set AllowDShowSound=0, it plays the low sample rate ACM files.
This is the content of my fallout2.cfg file:

```
mode=environment
output_map_data_info=1
show_load_info=1
show_script_messages=1
show_tile_num=1

[preferences]
brightness=1.000000
combat_difficulty=1
combat_looks=0
combat_messages=1
combat_speed=50
combat_taunts=1
game_difficulty=1
item_highlight=1
language_filter=0
mouse_sensitivity=1.000000
player_speedup=0
running=1
subtitles=1
target_highlight=2
text_base_delay=3.500000
text_line_delay=1.000000
violence_level=3

[sound]
cache_size=448
debug=0
debug_sfxc=0
device=-1
dma=-1
initialize=1
irq=-1
master_volume=27530
music=1
music_path1=data\sound\music\
music_path2=..\data\sound\music\
music_volume=16458
port=-1
sndfx_volume=26183
sounds=1
speech=1
speech_volume=26782

[system]
art_cache_size=261
cdlock=G:\cdlock.dat
color_cycling=1
critter_dat=..\critter.dat
critter_patches=data
cycle_speed_factor=1
executable=game
free_space=20480
hashing=1
interrupt_walk=1
language=english
master_dat=..\master.dat
master_patches=data
scroll_lock=0
splash=3
times_run=5
```

**Comment by lavadrop** [comment]
I think I found the solution.
I installed `gstreamer-plugins-bad-32bit gstreamer-plugins-good-extra gstreamer-plugins-good-extra-32bit`
HQ music is playing now, the flac version by BGforgeNet.
If other linux users come looking for this, try all three versions of gstreamer plugins with their 32bit version.

**Comment by lavadrop** [comment]
Arrrghhh, spoke too soon. Now I have memory crashes...
I guess this might be an sfall issue?

**Comment by egornovivan** [comment]
> I have no issues playing the wma lossless files in mplayer, vlc, ffmplay, etc.

Well then wma will be preferable for the game, it has normalization ebur128. Options from bgforge without normalization

**Comment by lavadrop** [comment]
I found the culprit of my issue: the lutris website has a script to install the game and the Fo1in2 mod in one go. Unfortunately the script sets up a 64 bit wine prefix and the gstreamer plugins complain of wrong architecture when running. Manually installing in a fresh prefix is the solution.
If any other users are lost, do not install via the lutris script, you won't be able to use other mods that require 32-bit libraries.
