### ISSUE TITLE
Fallout2.exe not working Mac Crossover

### ISSUE THREAD

**Issue by barcag07** [rotators/Fo1in2#239]
I am using crossover and fallout 1 and 2 community editions using GOG, fallout1ce, and fallout2ce. I am following all the steps correctly and just can't get the Fallout2.exe in the fallout1in2 directory to work. I Keep getting an error and I don't know what the problem is. I am pretty sure everything is in the correct directory.

Can anyone please give me any tips on how I can get it to work? Is it even compatible with Mac. If any more information is needed I will be glad to give it. Here is a picture of the error I get when launching Fallout2.exe in crossover, and a program error details file
![Screen Shot 2024-05-07 at 5 11 51 PM](https://github.com/rotators/Fo1in2/assets/103973745/6671212e-5ecc-4b7c-b615-d7a360ddc127)
[backtrace.txt](https://github.com/rotators/Fo1in2/files/15241626/backtrace.txt)
. Thank you.

**Comment by ArkEvensong** [comment]
Hold up, aren't Fallout CE and Fallout 2 CE complete engine rewrites? Those aren't going to be compatible with (most/any?) mods based on the base version.

No experience with Mac, so dunno how much of a pain it is to get the regular versions working.

**Comment by Lexx2k** [comment]
Ettu at this point has nothing to do with the CE and there is also no compatibility. That's why it won't work on Mac like that.
