### ISSUE TITLE
Fight with Garl breaks Hero Appearance

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#24]
https://i.imgur.com/M39fZIg.png

Funny enough, skin restored after defeating Garl and saving... no, not save+load, saving alone :>

**Comment by Lexx2k** [comment]
Probably an issue with refreshing the graphics. Bit weird, because if I remember right, the armor is not removed. I also didn't notice this issue when playing with bald head dude.

Probably something in the Hero Appearance-mod itself, which we can't fix. Or rather, I wouldn't know how.

**Comment by ghost2238** [comment]
If we can find a way to reproduce it reliably first we can fix it.
