### ISSUE TITLE
Wrong Motion Sensor description 

### ISSUE THREAD

**Issue by Slagar80** [rotators/Fo1in2#240]
The Motion Sensor has the Fallout 2 description that states a 20% bonus Outdoorsman skill.

I assume this is wrong since the item didn’t give that bonus in Fallout and it also wouldn’t make much sense bc of the different effects the skill has in both games.

**Comment by Lexx2k** [comment]
True, but right now the motion sensor gives +20% Outdoorsman even in ettu. This is kept on purpose because else the item is lame and useless.

**Comment by Slagar80** [comment]
Ah ok.
That makes sense.
One of the main reasons I posted this issue was that once I figured out that this is not a feature of the Fallout sensor I was kinda annoyed why I carried it with me since aside of the effect I don’t see much use of it and didn’t wanted other players to be misleaded by the description.
I consider this thread closed.

**Comment by Slagar80** [comment]
Although it maybe would be a good idea to change the description so it doesn’t state that the sensor helps to avoid random encounters because thats not what outdoorsman does in Fallout and et tu if I’m not mistaken.
But thats just a small detail that shouldn’t have high priority, just wanted to point it out.

**Comment by Lexx2k** [comment]
This is exactly what the skill does. What else would it be used for?

**Comment by Slagar80** [comment]
According to the wiki in Fallout it lowers the negative impact of certain random encounters (dehydration and rockfalls).

https://fallout.fandom.com/wiki/Outdoorsman

In Fallout 2 it makes it possible to choose whether to engage in random encounters or not.

Since it was mentioned in the nma thread of et tu that the players doesn’t have the option whether to engage in encounters or not and I also never got such prompt, I was under the impression outdoorsman works like in Fallout.

https://www.nma-fallout.com/threads/fallout-et-tu-release-v1-9.218045/page-81

Although I wouldn’t mind outdoorsman to effect random encounter chance (I like the Fallout 2 implementation of the skill much more), I’m kinda confused now how the skill works in et tu.

**Comment by ArkEvensong** [comment]
> This is exactly what the skill does. What else would it be used for?

Travel speed. Maybe this should be opened as a different issue, but in base Fallout 1, Outdoorsman determines how much time passes while traveling. (And I'm very confused why it's not listed on the wiki.) Tested a bit, but that doesn't seem to be the case in Et Tu, nor in base Fallout 2.

From roughly the center of the map squares:

Fallout 1 - From V13 to V15 and back:
Outdoorsman 1%: ~19 days
Outdoorsman 31%: ~16 days
Outdoorsman 200%: ~9 days

Fallout Et Tu - same route:
Outdoorsman 1%: ~18 days
Outdoorsman 21%: ~18 days
Outdoorsman 200% ~18 days
(No effect on travel time, I'd say roughly on par with 10% in vanilla Fallout 1)

Fallout 2 - Arroyo to Klamath and back:
Outdoorsman 20%: ~10 days
Outdoorsman 100%: ~10 days
(No effect on travel time either)

**Comment by Lexx2k** [comment]
Travel time / mechanic has been rewritten.
