### ISSUE TITLE
Magnetic Personality perk

### ISSUE THREAD

**Issue by Slagar80** [rotators/Fo1in2#241]
I have a playthrough with fallout 2 party limit and the additional optional companions disabled and still can pick the magnetic personality perk which increases the party limit by 1.

This doesn’t seem right since there is no party limit in vanilla Fallout as you know.
I only mention this bc this maybe misleads some people that play with the same settings to pick the perk bc they think it’ll do something.

**Comment by NovaRain** [comment]
I think it's still useful for players with CH < 8 with FO2 party limit but no additional companions.
Unless you mean it should be removed if FO2 party limit is disabled to make sure people won't pick it for nothing.
