### ISSUE TITLE
Issues running Fallout1 in 2 on Fallout Collection (DVD)

### ISSUE THREAD

**Issue by tomodachi** [rotators/Fo1in2#242]
Is the Fo1in2 compatible with this release?

I've installed fallout1 and fallout2 and applying the patch following the README.

But when starting the  Fallout2/Fallout1in2/Fallout2.exe   I just get into a game  Fallout2
I notice something is off due to the bottom menu button not having any text  unlike the ordinary Fallout2 main menu

**Comment by NovaRain** [comment]
You didn't mention what system you're using, If you're running the game in Wine under Linux, you need to set DLL overrides for ddraw.dll to **"native, builtin"** in winecfg or use `WINEDLLOVERRIDES="ddraw=n,b"` to run Fallout from the command line.

**Comment by tomodachi** [comment]
I'm running Linux

Thanks for the suggestions possibly the DLL override will fix menu option.  But my REAL  issue is that following the README  no matter what I do I end getting a  fallout2 game rather than Fallout1 in the Fallout2 engine

**Comment by tomodachi** [comment]
I found a post on reddit of a person having the [exact same issue ](https://www.reddit.com/r/classicfallout/comments/m49z2g/im_having_trouble_getting_fallout_1_et_tu_to_run/)

Even down to the screenshot of the menu looking strange after applying the patch.

Is there any Linux user that can confirm that they actually got this working?

**Comment by tomodachi** [comment]
I found the solution to the issue.

One has to override  priorities of which DLL is used in this case when using wine for this project.

```bash
 WINEDLLOVERRIDES="ddraw.dll=n,b"  wine Fallout2.exe
```

I'll try to make an update to the install doc (if it's accepted) so it's easier for Linux / Steam deck users in the future.

**Comment by NovaRain** [comment]
> One has to override priorities of which DLL is used in this case when using wine for this project.

Isn't it the same as in my previous post?

**Comment by Lexx2k** [comment]
Updated the readme with that now. Let's hope people will read.
