### ISSUE TITLE
Caravan missions are busted

### ISSUE THREAD

**Issue by Merudiana177013** [rotators/Fo1in2#243]
Did a couple rounds of guarding the Far Go Trader's caravan and both times every random encounter was broken. We would arrive at an area filled with enemies, combat automatically starts, the other guards take a few steps, and the enemies just spontaneously die with no shots fired. Free caps, but would be more fun to be able to actually participate.

**Comment by Lexx2k** [comment]
You are playing with debug mode on. Disable debug mode and this stops happening.

**Comment by Merudiana177013** [comment]
Well, that's embarrassing. Sorry about that.
