### ISSUE TITLE
Frame rate / stuttering issues.

### ISSUE THREAD

**Issue by Issue-haver** [rotators/Fo1in2#244]
I have been experiencing some very severe framerate/stuttering issues with 1in2 so far, so much so that the mod runs worse than fallout 1 normally does. I am not sure what the cause of the issue is. I have changed settings in an attempt to fix it, but I haven't been successful. Windows 10 is my operating system. I launch the mod through file explorer. Fallout 1 & 2 are both installed outside of program files and program files (x86). My friend is able to run the mod fine on their laptop (operating system is windows 11).

**Comment by NovaRain** [comment]
Check if your graphics driver set a FPS limiter or Vsync on the game and disable them.

**Comment by Issue-haver** [comment]
Thanks, turning off Vsync fixed the issue. To someone with more experience this was probably an obvious fix, so thanks for taking the time to help. 
I have seen others struggle with the same issue, so it might be worth adding a note to the faq read me, as Vsync didn't cause this issue with fallout 2 for me.
Thanks again for your help and your work on the mod.

**Comment by NovaRain** [comment]
> adding a note to the faq read me

Actually there is already one:
https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/FAQ.txt#L88

> == Fallout is noticeably lagging in DX9 graphics modes ==
Make sure you don't have any FPS limiters or VSync enabled for Fallout. For example, the 'Max Frame Rate' option in NVIDIA Control Panel or the 'Adaptive/Smart VSync' in Intel Graphics settings.

**Comment by Issue-haver** [comment]
whoops, my bad.
