### ISSUE TITLE
"Game initialization failed" when using 3440x1440

### ISSUE THREAD

**Issue by chrsaltz** [rotators/Fo1in2#245]
As the subject line says, I am unable to launch the game when using this resolution. If I edit the resolution in f2_res.ini to something lower like 1280x960, it starts fine. I can then change to my desired resolution from the game's options in the GUI and it will continue running.

Then, when I go to re-launch the game later, it crashes again, with the "Game initialization failed" message in a pop-up window. I have tried running as administrator, many different permutations of settings in f2_res.ini and ddraw.ini, with the Mash hi-res patch disabled and enabled, reinstalled and uninstalled Et Tu many times, windowed, full screen, windowed full screen, scaling on and off, UAC aware on and off, different graphics modes, etc.

I'm using clean installs of the Steam versions of Fo1 and 2, on Windows 10 with a 3090 and 32GB RAM. Running the Fallout2.exe executable within SteamLibrary\steamapps\common\Fallout 2\Fallout1in2. All .ini files mentioned are also within SteamLibrary\steamapps\common\Fallout 2\Fallout1in2. All .ini values are the defaults except 

![image](https://github.com/rotators/Fo1in2/assets/48190611/34207588-0361-4cc9-af6f-19b1270f7aa3)

**Comment by BollitheBear** [comment]
Same problem as above. debuglog attached:
[debug.log](https://github.com/rotators/Fo1in2/files/15390853/debug.log)

Please help.

**Comment by NovaRain** [comment]
Your game couldn't load

> Same problem as above. debuglog attached: [debug.log](https://github.com/rotators/Fo1in2/files/15390853/debug.log)
> 
> Please help.

Maybe check https://github.com/rotators/Fo1in2/issues/236 ?
