### ISSUE TITLE
Sometimes no aggro between critters in random encounters

### ISSUE THREAD

**Issue by ArkEvensong** [rotators/Fo1in2#247]
Two examples:

Near Shady Sands:
[ `You encounter a traveler.` ]

- Lance from Shady Sands. ("You see a weary traveler" / "Human male dressed in protective leather clothing" ) 
- 4-5(6?) Mantises

Expected behavior: Lance and the Mantises are aggressive towards each other.

Bug: Frequently when triggering this encounter, the Mantises are initially only aggressive towards the PC, while Lance just stands there doing nothing. If you manage to lose aggro from the mantises and end combat, they _will_ initiate towards Lance, but not before.

I _have_ run into this encounter where the mantises _do_ starts by attacking Lance, and him attacking back, so it's not an always thing. I think roughly 1/3 of the time I've had this encounter it behaves as expected.

Example save file
[SLOT28 Passive Traveler.zip](https://github.com/rotators/Fo1in2/files/15325215/SLOT28.Passive.Traveler.zip)

And here's another example of no aggro between two groups, which could be the same underlying issue:

Near Vault 15 (maybe also other places): 
[ `You have stumbled into a fierce battle between radscorpions and mole rats.` ]

- 3 Radscorpions
- 2 Greater Mole Rats
- 3 Lesser Mole Rats

Except there's no battle - the encounter starts with the radscorpions opening combat towards the player, while the molerats are entirely passive until combat ends (or are attacked by the player.) In the attached save file, if you run upwards only two radscorpions follow. The third one is happy to chill out among the mole rats, doing nothing. _Unlike_ the Lance encounter, if you manage to end combat, the two groups will remain passive towards each other.

[SLOT26 Radscorpions and Molerats.zip](https://github.com/rotators/Fo1in2/files/15324126/SLOT26.Radscorpions.and.Molerats.zip)

Like with Lance and the mantises, I have also run into this encounter where it did behave as expected.

EDIT: This is playing with the current release version. (v1.9.3324)

**Comment by Lexx2k** [comment]
That's just how Fallout works. Not much we can do about that. If you are the first to aggro them, they will attack you and only your team.

**Comment by ArkEvensong** [comment]
Well, I certainly remember it occasionally being buggy like this way back when too. 

Seemed a little more common now, but maybe that's because I'm playing a bit more in "testing stuff mode" now.

**Comment by ArkEvensong** [comment]
Hm. The Lance encounter wasn't in the base game, I believe. Should explain why I didn't remember it being a problem in that instance before. 

I figure that encounter goes wrong about 2/3rds of the time though, and it's a pretty common one. Not sure what triggers the initial aggo, but any chance the issue could to mitigated by spawning the PC a little further away in that encounter, or changing some aggro settings, so it's more likely the mantises will attack the traveler first? (Or give the first turn to the traveler, who shouldn't be aggro towards the player anyway?)

**Comment by Lexx2k** [comment]
Can't.
