### ISSUE TITLE
[New Premade Characters Mod] New premades also start with base equipment.

### ISSUE THREAD

**Issue by ArkEvensong** [rotators/Fo1in2#248]
For the included `fo1_new_premades` mod, despite there being a script in the mod that's supposed to remove all the standard starting equipment, the premade characters start with their custom equipment _plus_ the base game's starting equipment.

Ken, for example, starts with **2** 10mm pistols, 4 flares, 8 stimpaks and 2 knives. 

--

Another entirely different mod related issue, but which is _so_ minor I dare not open a separate topic on it:

The `mods_order.txt` file doesn't come with an entry for the `InventoryAPcosts` mod that's included in the release. (All the other included optional mods are listed but commented out.)

**Comment by Lexx2k** [comment]
Already fixed on repo files.

**Comment by ArkEvensong** [comment]
Ah. Neat.

Hm, I though the Inventory AP Costs mod was interesting in the "no unlimited healing for 4 AP, which makes Super Stimpaks useful for the PC" kind of way, but thinking further on it, yeah, maybe that's about the _only_ thing it's good for?

I've certainly wasted some AP when being indecisive about which weapon to equip and forgetting I had that mod turned on.

[FAKE EDIT] Wait, can't you already use items from inventory with the use item on command anyway for less than 4 AP?
[LATER] Yup, you _can_ use a stimpak on yourself for 2 AP by using the right click->backpack option. Hrm. Well, so much for that then.
