### ISSUE TITLE
"Game initialization failed" on default settings

### ISSUE THREAD

**Issue by Leoat8** [rotators/Fo1in2#260]
I cannot for the life of me get this mod to work. I have installed it properly multiple times and I keep getting the same error when trying to start. I have tried changing the resolutions and such on my Windows 11 pc and it did not help. I also tried using the debugger, which gives me the following error code:
Fade time is 188
Fade steps are 223
Chi squared is 22.449000, P = 36.420000 at 0.05
Sequence is random, 95% confidence.
>partyMember_init	soundInit: Setting primary buffer to: 16 bit, 2 channels, 44100 rate
soundInit: Primary buffer settings set to: 16 bit, 2 channels, 44100 rate
SFXLIST: Can't open file for write sound\sfx\SNDLIST.LST
>gsound_init	>initMovie		>gmovie_init	>moviefx_init	>art_init		>tile_init		>obj_init		>cycle_init		
 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **

 ** String not found @ getmsg(), MESSAGE.C **
>intface_init	>iso_init		>gmouse_init	
Error: Loading proto message files!Failed on proto_init

Please help me out here, thx.

**Comment by Leoat8** [comment]
Changing the language of the base game to English eventually worked. I suggest adding this to the installation instructions since this seems to be a reoccuring problem with other players.

**Comment by Lexx2k** [comment]
Should not happen anymore with latest release.
