### ISSUE TITLE
Crash Entering The Hub Downtown

### ISSUE THREAD

**Issue by aaronvancuren** [rotators/Fo1in2#265]
[debug.log](https://github.com/user-attachments/files/15845028/debug.log)

Summary: I did a fresh install of the games and the mod. Started a new playthrough, changed some config settings, then ran into this crash when attempting to enter the downtown section of the Hub. Figured the issue was because I changed config setting after starting a game. I then did a fresh install of everything again, change config settings first, then started a new playthrough. Reached the same point and was hit with the same crash.

I'm looking into downloading the scripting tools so that I can look into the problem further but am hoping I can get some help faster here.

Debug file is attached. TLDR:
Script Error: scripts\gl_fo1mechanics.int: op_obj_pid: obj is NULL
Script Error: scripts\gl_fo1mechanics.int: op_obj_pid: obj is NULL
Script Error: scripts\deadguy.int: op_destroy_object: obj is NULL
Script Error: scripts\deadguy.int: op_critter_add_trait: obj is NULL
Script Error: scripts\deadguy.int: op_critter_add_trait: obj is NULL
Script Error: scripts\deadguy.int: op_tile_num: obj is NULL
Script Error: scripts\deadguy.int: op_critter_attempt_placement: obj is NULL
Error during execution: 
Stack underflow short.
Current script: scripts\deadguy.int, procedure start

Additional Testing: I loaded my save again. I travelled back to Junktown, entered the town, then travelled back to The Hub and attempted to enter the downtown area again. From this, I would say the error in specifically coming from the deadguy.int script because the NULL obj in the gl_fo1mechanics.int script seems to occur anytime I enter an area. I attached this debug file as well.

[debug_additional_testing.txt](https://github.com/user-attachments/files/15845081/debug_additional_testing.txt)

**Comment by Lexx2k** [comment]
Need your savegame for repro.

**Comment by aaronvancuren** [comment]
[SAVEGAME.zip](https://github.com/user-attachments/files/15849343/SAVEGAME.zip)

Here are all of my saves from this playthrough. Slot 6 is the most recent where I just got to The Hub

**Comment by Lexx2k** [comment]
Can't reproduce the crash. My savegame in Downtown:
[SLOT07.zip](https://github.com/user-attachments/files/15855287/SLOT07.zip)

Do you use any other mods?

**Comment by aaronvancuren** [comment]
I appreciate you looking into this issue. I cannot explain it. I am unable to reproduce the crash now too.

The only differences I could spot is that your save file has a file "sfallfs.sav" and some of the individual save files vary in size.
