### ISSUE TITLE
Followers of the apocalypse 

### ISSUE THREAD

**Issue by Slagar80** [rotators/Fo1in2#266]
So this is not really an issue, more of a suggestion:

I remember that you can talk to Nicole (the leader of the FotA) in the library and ask to get help to destroy the cathedral.
Once you habe done this and enter the cathedral map there will be 4 FotA scouts that follow you everywhere and of course are allied in combat.
But this makes disguising and infiltration of the cathedral impossible unless you kill those scouts since you have no way if telling them to stop following you and they blow your cover.
I read somewhere that one should just leave and reenter the cathedral map and the scouts would be gone but this never worked for me.
This was while playing a relatively new version of et tu so I guess it’s still that way.

So what I’m suggesting is to implement the option to tell these scouts to stop following you (and then maybe to follow you again if you want them in your party for combat) if that’s possible.

**Comment by Lexx2k** [comment]
There is already a dialog option which allows you to exit the dialog without having reinforcements show up at the Cathedral.

Besides, you *can* leave the map and return. Same with the paladins at Mariposa. It works for everyone.

**Comment by Slagar80** [comment]
Ok I could have sworn leaving and reentering the map did not make the scouts disappear.

I only wanted to bring this to your attention bc I remember beeing suprised by those scouts following me on the cathedral map but that was probably bc i didnt paid enough attention when speaking with nicole.

**Comment by Slagar80** [comment]
Also another things I came across just now:

when discovering traps (i am currently in the thieves lair in the hub) i get the "trap disarmed" message although they are very much not disarmed (i tested that XD), just becoming visible after being discovered
i guess it is supposed the give a "trap discovered" message 

![Screenshot (4)](https://github.com/rotators/Fo1in2/assets/169339713/72c00796-5367-45c6-ba9c-b38219b11122)

**Comment by Lexx2k** [comment]
> Ok I could have sworn leaving and reentering the map did not make the scouts disappear.

You have to enter another map first.

**Comment by Slagar80** [comment]
Should I open a different thread for trap message issue and close this one ?
