### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#27]
>I am running Fallout mods on my mac using crossover (...) Unfortunately I can't get past the installation step where I have to extract undat.exe (Command return 255 - no idea what this means....)

https://nma-fallout.com/goto/post?id=4361043#post-4361043

**Comment by ghost2238** [comment]
I have reached out to the user on the forum and gave him some suggestions and workarounds. 
Seems like undat.exe is not working via https://www.codeweavers.com/products/crossover-mac/ for some reason.

**Comment by ghost2238** [comment]
Response from the user: "No I couldn't use any undat programs on crossover. I will probably end up installing windows 10 with bootcamp on my mac... ".

Would be helpful if we could get feedback from other mac users.

**Comment by ghost2238** [comment]
Looks like he managed to get it running in some way, closing this since there's no actionable information.
