### ISSUE TITLE
Some suggestions for next versions

### ISSUE THREAD

**Issue by koznichki** [rotators/Fo1in2#270]
Hi. I have some suggestions for changes:

1. Unlike the original game, the total and current weight of the inventory doesn't show. There is no possibility to know how close I am to max capacity for example. It would be nice if you could retrieve this feature.
2. Before using the Et Tu mod I used Fixt, and in its embedded Sfall version by pressing the ctrl key it was possible to distinguish interactable things (like bookcases) that may contain items (and not just items on the ground). I think it would be great if you could add this feature.
3. Also in the Fixt there is a merchant on the right half of Shady Sands, but he is absent in the Et Tu. I understood that Fixt added some dead-end quests and characters that were cut out from the final version of the game. Why don't you include him too?

**Comment by Lexx2k** [comment]
1. This is not a feature of the original game but a mod. That said, you can just enable the ShowLootWeight-mod to get the same effect.

2. change settings in sfall-mods.ini file in /mods/ folder.

3. Enable it in fo1_settings.ini file.

**Comment by koznichki** [comment]
Thank you for the very quick reply.
1. I don't know this mod. where can I find it, please? Is it an add-on that I should install on the Et-Tu mod or it should be installed instead of Et-Tu?
2. I don't have a programming background. What exactly I should change in the sfall-mods.ini file, please?
3. Good to know. In that case, I prefer to stick with the original game content. Thank you.

**Comment by Lexx2k** [comment]
1. Mentioned in the readme https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/README.md#additional-content
2. You don't need programming background. Find the file, open it, read the content, change the values to how you want them to be.

**Comment by koznichki** [comment]
1. Cool, I really just had to remove the ; sign, and the weight number was on.
2. I didn't understand although I read the readme. When trying to edit the sfall-mods.ini this is what I see:

[Highlighting]
; DX scancode of a key to press to highlight items on the ground
;  42 - SHIFT key
;  29 - LCntrl
Key=29

; Set to 1 to also highlight containers
Containers=0

; Set to 1 to also highlight lootable corpses
Corpses=0

; Set to 1 to also highlight critters, with the same rules as in combat
Critters=0

; Set to 1 to only highlight objects in the player's line-of-sight
CheckLOS=1

; Set the color of outlines for items, corpses, and containers; available colors:
; 1 - glowing red
; 2 - red
; 4 - grey
; 8 - glowing green
; 16 - bright yellow
; 32 - dark yellow
; 64 - purple
; You can set a custom color from the game palette by multiplying the color index value by 256 (in 4.2.7 or later)
OutlineColor=16

; Motion Scanner mode:
; 0 - ignored
; 1 - requires Motion Sensor to be present in the player's inventory to activate highlighting
; 2 - requires Motion Sensor and consumes 1 charge on every use (depleted sensor will not work anymore)
MotionScanner=0


[CombatControl]
;Allows you to control other critters directly in combat
;Set to 0 to disable
;Set to 1 to control all critters in combat (allowed only in sfall debugging mode)
;Set to 2 to control all party members
;Set to 3 to let you use the command cursor to specify targets for party members to attack in combat
Mode=3
;If you want to control only specific critters, uncomment the PIDList line and set a comma-delimited list of PIDs
; Ian, Tycho, Katja, Tandi, Dogmeat, Mr.Handy, Floating Eye, Rae, Vasquez
PIDList=76,210,302,63,122,313,345,346,347

;Set a comma-delimited list of perk IDs for perks to be inherited from the player during the combat control
PerksList=0,73

;Set to 1 to allow the player to gain a positive reputation when killing NPCs while controlling other critters
GainReputation=0

;Choose a notification box to display the name of the controlled critter above the interface bar
;Must be between 5 and (4 + the value of BoxBarCount in ddraw.ini)
;For sfall 4.1.6+ the number for the notification box is set automatically, so just use any value
;Set to 0 to disable
DisplayName=1

;Set the color of display name, available colors:
;0 - green
;1 - red
;2 - white
;3 - yellow
;4 - dark yellow
;5 - blue
;6 - purple
;7 - dull pink
DisplayNameColor=0

Wher should I add the /mods/ folder please?

**Comment by koznichki** [comment]
Awesome. Thank you guys very very much.
Please, last question for a while - For some reason, unlike the original game and the Fixt mod, Ian decides to come as close as possible to the enemies (and sometimes tries to hit them although he has a gun), instead of shooting from afar. This is very difficult to handle when fighting scorpions. Might you know what should I change for him would fight the standard way?

**Comment by Slagar80** [comment]
Yellow means you can’t target them like if there around a corner etc. if I’m not mistaken.
Can’t tell you anything about the Ian issue though.

**Comment by koznichki** [comment]
If that's ok I can keep reporting bugs and errors.
After I returned Tandi to Shady Sands, Seth kept thanking me for the radscorpions and not for Tandi.

**Comment by Lexx2k** [comment]
Just tell Ian to keep his distance and use companion control options.. did you never play Fo2 before?

**Comment by Slagar80** [comment]
Yeah I guessed he already did this 
Sometimes if you’re companions run out of ammo they will obviously go into melee

**Comment by koznichki** [comment]
I will try it, thank you. No, I haven't played FO2 yet, but plan to play it after completing FO1. I first played FO long ago when it was sold at stores in a box...

He didn't run out of ammo for sure, but I'll try to understand and implement companion control.

Another thing missing is that after I persuaded Trish to stay with Saul there is no XP gain.
