### ISSUE TITLE
Problem with Russification

### ISSUE THREAD

**Issue by praverz** [rotators/Fo1in2#271]
Hello, the problem is the following, I want to make russification of dialogs in your game, for this I used Dat Explorer II to extract dialog files from master.dat faloout1, I translated several files while maintaining the necessary encoding (ANSI, as I read in the guide) . I decided to test if my translation works and using the same dat explorer II I replaced the original Aradesh text file with my translated Russian one, then ran undat.exe and got an error the file is not a valid master.dat from Fallout 1.

**Comment by NovaRain** [comment]
You shouldn't repack your translated msg files into FO1 `master.dat`.
For the translation, you can check how `fo1_lang_german` and `fo1_lang_french` set up in the "mods" folder. You will also need new font files for displaying Cyrillic (can grab them from [UPU](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/tree/master/translations/russian)).

**Comment by praverz** [comment]
Thanks a lot

**Comment by praverz** [comment]
Solved

**Comment by praverz** [comment]
I apologize again, figured out how to add my own text. I decided to take as a basis the folder with the French package and change there files to Russian, the only thing I do not understand how to fix this error. As I realized NovaRain sent a link to the fonts but I do not understand where to insert them, I put them in the folder with the French translation. For clarity replaced only the dialog with Ardaesh, everything else left in French. Maybe I should create a new folder?
![Untitled](https://github.com/user-attachments/assets/d17fc04c-12d9-49d7-9ca9-130db0e8ba09)

**Comment by praverz** [comment]
> > Hello, the problem is the following, I want to make russification of dialogs in your game, for this I used Dat Explorer II to extract dialog files from master.dat faloout1, I translated several files while maintaining the necessary encoding (ANSI, as I read in the guide) . I decided to test if my translation works and using the same dat explorer II I replaced the original Aradesh text file with my translated Russian one, then ran undat.exe and got an error the file is not a valid master.dat from Fallout 1.
> 
> привет. вы делаете ручной или машинный перевод?

Ручной
