### ISSUE TITLE
Error initializing video mode 960x540 on startup with Steam versions

### ISSUE THREAD

**Issue by dpcollier128** [rotators/Fo1in2#273]
My desired settings are 1920x1080, Windowed, scaled x2.

Please help. I don't know where to begin fixing this.

**Comment by NovaRain** [comment]
If your desktop resolution is 1920x1080, try these settings for a windowed fullscreen game with 960x540 pixels:
```ini
; in ddraw.ini
[Graphics]
Mode=6
; in f2_res.ini
SCR_WIDTH=960
SCR_HEIGHT=540
SCALE_2X=0
```
If you have a higher desktop resolution (e.g. 2K/4K) and specifically want a 1920x1080 window:
```ini
; in ddraw.ini
[Graphics]
Mode=5
GraphicsWidth=1920
GraphicsHeight=1080
; in f2_res.ini
SCR_WIDTH=960
SCR_HEIGHT=540
SCALE_2X=0
```
Yes, there is _no need_ of SCALE_2X.

**Comment by dpcollier128** [comment]
Oh. Okay. Simple enough.
