### ISSUE TITLE
Griffith Spawning in a Wall

### ISSUE THREAD

**Issue by Settyness** [rotators/Fo1in2#275]
I talked to Griffith in Necropolis and agreed to watch his bike. I wasn't able to find him, so I searched online. I've seen that a few people have had similar issues as me and I may have found a culprit and I wanted to contribute my findings.

I was suspicious of this blip on the underground ghouls map.

![Screenshot_2024-10-19_14-35-34](https://github.com/user-attachments/assets/52926790-21b8-4eac-a052-0bf19b99039d)

Sure enough, the albino rat (and presumably Griffith's corpse) have spawned in a wall.

![Screenshot_2024-10-19_14-36-02](https://github.com/user-attachments/assets/3b3dc1ea-032b-4ece-872b-778e69cb7959)

Luckily, I think I have a save from not too far back. Is there a console or anything that this could be rectified with?

**Comment by Lexx2k** [comment]
He should be spawning on this hex:
![grafik](https://github.com/user-attachments/assets/3fa16b16-5831-4a43-a0d3-6397239d82a6)

You can actually see the body in your screenshot.

**Comment by Settyness** [comment]
Ah, you're right. I ended up reloading a save before talking to Griffith and everything worked out fine. I have since installed fo2tweaks, whose enhanced highlight feature would've helped me discover this. Still, I think worth reporting for the stuck albino rat.
