### ISSUE TITLE
LORI CHARISMA OP

### ISSUE THREAD

**Issue by LunaticLoL** [rotators/Fo1in2#277]
Hi i can no longer see the option to enable the Lori Charisma operation and sex. Has the option been moved from fo1_settings.ini, if so where was it moved.

PS:sorry english is my second language

Thanks

**Comment by Lexx2k** [comment]
It has been deleted because it was bad. The options are no longer available.

**Comment by LunaticLoL** [comment]
Thanks for the quick response lex

**Comment by LunaticLoL** [comment]
CLOSE
