### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by LunaticLoL** [rotators/Fo1in2#278]
The github page for the lossless music for fallout 2 says to set [AllowDShowSound=2] to 2 in ddraw.ini, but the comment in ddraw.ini says i should set it to 1 for the lossless music to work. 
Can someone please clear up the confusion.
Thanks
![Screenshot 2024-12-23 194841](https://github.com/user-attachments/assets/60ed96e1-3995-48e1-8ac5-5b2f61a43e5c)
![image](https://github.com/user-attachments/assets/0c97dfb6-8d37-4fdf-a3b5-a48cd59609c9)

Ps: sorry for mz bad english

**Comment by NovaRain** [comment]
Setting 1 or 2 doesn't matter as newer sfall merged the two modes.
