### ISSUE TITLE
Crash when trying to take over Adytum with Blades

### ISSUE THREAD

**Issue by ccrtnsp** [rotators/Fo1in2#31]
I am experiencing a reproducible crash/memory corruption when accepting to assist Blades/Razor with the Adytum takeover and the actual fight starts. Sometimes the crash occurs right away, sometimes after some NPCs making their moves. Might be just a regular FO2 engine bug, but reporting here anyway. If I take the route of NOT assisting Blades, everything seems to work just fine.

Version is release v1.0.1700. FO2 version is the GOG/EU one, if that matters. I am playing under Linux, with Wine 4.0.3 (Debian package).

I've not encountered any other issues with Fo1in2 yet, very impressive work :1st_place_medal: 

Savegame attached right before the choice to talk to with Razor -> help with fight.

[f1in2_v1.0.1700_adytum_fight_crashes_SLOT01.zip](https://github.com/rotators/Fo1in2/files/4174458/f1in2_v1.0.1700_adytum_fight_crashes_SLOT01.zip)

**Comment by ghost2238** [comment]
Thanks for the crash report, the save was very helpful, I managed to get the crash too.
Looks like a null pointer crash in the stat_get_base_direct, we'll have to investigate more.

I extracted this manually from my debugger:

EXCEPTION_ACCESS_VIOLATION on 0x4AF46A in stat_get_base_direct_

Callstack:
fallout2.sub_4AEF52+55 from fallout2.stat_get_base_direct_
fallout2.0042BA2F from fallout2.stat_level_
fallout2.0042BC8C from fallout2.is_within_perception_
fallout2.00424DBC from fallout2.combatai_notify_onlookers_
fallout2.combat_anim_finished_+B4 from fallout2.apply_damage_
ddraw.sfall::AnimCombatFix+3A from ???
fallout2.tile_refresh_rect_+17 from ???
fallout2.dude_stand_+1F4 from fallout2.tile_refresh_rect_
ddraw.sfall::anim_set_end_hack+6 from ddraw.sfall::AnimCombatFix
fallout2.anim_set_end_+24B from ddraw.sfall::anim_set_end_hack
fallout2.anim_set_continue_+41 from fallout2.anim_set_end_
fallout2.00417E81 from fallout2.anim_set_continue_
ddraw.sfall::onCombatLoop

**Comment by Lexx2k** [comment]
Here is a workaround: Return to Adytum once, before talking to Razor. Then go back to Razor and the attack shouldn't crash anymore.

Problem is the caravan that is still in Adytum and gets deleted when combat starts - this produces a null ptr error and the game goes belly up.

**Comment by Lexx2k** [comment]
Well, should be fixed now.
