### ISSUE TITLE
New tool: Merge maps / swap elevations

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#33]
Need a small new tool: Merge / Swap map elevations in a map file.

Map files can be saved and loaded in .txt format. Merging is possible to do manually, but it's a real bitch, because the file can become really, really long and it's easy to lose track.

The merge tool doesn't need to be complicated. I'm thinking about:
1. Load map A
2. Load map B
3. Define if copy to elevation 0, 1, 2 
4. New .txt file is created that can be used in the BIS mapper.

Swapping elevations in the same map file is even easier. Just have to rename `elev: 0` etc. with a simple search&replace. Having this feature available in the same tool would be a tad more convenient, though.

More details about merging here:
https://falloutmods.fandom.com/wiki/Merging_maps

Example map file (huge, takes a while to load):
https://fodev.net/pastebin/?p=73

Obviously this would also be useful for other Fo2 mods.

**Comment by ghost2238** [comment]
Implemented with https://github.com/rotators/mappet/commit/4ed89fadeb7fcb101c51768c0c32e7ceb9e7cb40 - keeping the issue open for a while in case there are any annoying bugs.

**Comment by wipe2238** [comment]
It's not like we can use mappet repo for issues or anything :>

**Comment by ghost2238** [comment]
> 
> 
> It's not like we can use mappet repo for issues or anything :>

Suuure, let's close it.
