### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by FakelsHub** [rotators/Fo1in2#36]
https://github.com/rotators/Fo1in2/blob/f3440b5fc8e42261d299025cdc868ef712c5359c/Fallout2/Fallout1in2/mods/fo1_classic_worldmap/scripts/gl_classic_wm.ssl#L32
https://github.com/rotators/Fo1in2/blob/f3440b5fc8e42261d299025cdc868ef712c5359c/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_fo1mechanics.ssl#L78

fix to 
```
if sfall_rotators then begin
...
end
```

**Comment by Lexx2k** [comment]
Done [here](https://github.com/rotators/Fo1in2/commit/fd0eaee7426d7976d4e1eb85871df2242047ca46) and [here](https://github.com/rotators/Fo1in2/commit/5979c50114a1bedd0525ba49889387c67b14926e).
