### ISSUE TITLE
Armor Destroy Mod keeps failing

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#38]
For whatever reasons, the global script ([gl_destroy_armor.ssl](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_destroy_armor.ssl)) keeps failing at times, and won't destroy armor of killed critters. I have no idea why, and don't know how to make it 100% fool proof.

My idea is to simply delete the mod + edit critters in all maps and remove their armors the easy way... just delete them and call it a day. 

These armors aren't good for the game anyway. They ruin the game balance within the first few hours, the player will swim in money, and never has to buy any set of armor in the first place. 
In a way, it's worse than the Turbo Plasma Rifle.

Thoughts?

**Comment by FakelsHub** [comment]
You should stick as close as possible to the F1 mechanics, so the script should be enabled/disabled depending on the player's preferences.
The same applies to prices in stores they should be as F1, not as in F2.

**Comment by Lexx2k** [comment]
Store items can be toggled.

gl_destroy_armors.ssl exists to allow players to turn it on / off, but it doesn't work correctly.

**Comment by FakelsHub** [comment]
This is because it is misspelled.
Here is an [example](https://github.com/FakelsHub/sFall-Extended/blob/4402d936914c929a954ae5ce595e6908238b09c5/artifacts/mods/gl_sfall-mods.ssl#L57) of how I implemented the correct drop of weapons (remove armor for your case) from the hands at the death of an NPC

**Comment by FakelsHub** [comment]
I will test this script.

**Comment by FakelsHub** [comment]
were there many cases of non-removal of armor or was it 1 in 100 ?

**Comment by Lexx2k** [comment]
I never saw it myself, but some people reported it. So it's more like 1 in 100.

**Comment by Lexx2k** [comment]
People reported that this raider here is dropping armor often: https://www.nma-fallout.com/attachments/scr00010-jpg.14627/ (04raiders\toyla.ssl)

He doesn't for me, though. Also there is a regulator in Adytum that drops armors.... but not for me. In the mapper I can't see anything being different with these critters, the scripts aren't anything fancy anyway. tl;dr - I just can't reproduce it, or maybe I just didn't kill them often enough to experience it myself.

**Comment by burner1024** [comment]
> My idea is to simply delete the mod + edit critters in all maps and remove their armors the easy way... just delete them and call it a day.

That seems like a serious overkill for handling a 1 out of 100 case. Even if proper hook solution isn't found, I'd just leave it at that.

**Comment by Lexx2k** [comment]
Well, I'm getting constant reports about "bug, armor dropped!" and it annoys the hell out of me.

**Comment by burner1024** [comment]
True, I didn't think of that.

**Comment by FakelsHub** [comment]
>Wild guess:
>As soon as you knock down / knock out a critter so that you are able to loot their inventory, the >armor is "unworn" into the critters inventory, and the player is able to pick it up. This is why the >armor destroy mod is failing.

It can be, I'll check it.

**Comment by FakelsHub** [comment]
> Tolya just dropped armor for me. I knocked him out in unarmed combat, then he died.
As soon as you knock down / knock out
 
For me, this works fine with other NPCs, the armor is deleted under any death conditions.
The only armor can be picked up if the NPC lost turn or is knockout. (this is a bug with respect to armor).
Do you have a save from f1? so that I specifically check this "Tolya"

**Comment by Lexx2k** [comment]
No I don't. In Fo1 armors drop always, so not sure what you would want to test there?

**Comment by FakelsHub** [comment]
I mean f1inf2

**Comment by Lexx2k** [comment]
Try this: [SLOT01.zip](https://github.com/rotators/Fo1in2/files/4214930/SLOT01.zip)

**Comment by FakelsHub** [comment]
Fixed script: [gl_destroy_armor.ssl](https://github.com/rotators/Fo1in2/files/4215479/gl_destroy_armor.ssl.txt)

**Comment by Lexx2k** [comment]
The problem with `HOOK_ONDEATH` is that it won't fetch armors dropped by explosion death, etc. The armor item is dropped before the hook kicks in. This is why I switched to `HOOK_DEATHANIM2`.

Also you can still steal armors from knocking critters unconscious now. :p

The way I see it, the only solution would be to delete armor either on map enter, or when the a critter gets damaged.

**Comment by FakelsHub** [comment]
> The problem with HOOK_ONDEATH is that it won't fetch armors dropped by explosion death, etc.

Are you sure? I checked this,  blowing up a few the NPCs, in their remains there was no armor left.

>Also you can still steal armors with knocking critters unconscious now. :p

there is some bug in the engine, equipped items can not be taken from the NPC - this will be fixed. (armor can't be picked up for sure.)

**Comment by NovaRain** [comment]
> 
> > Also you can still steal armors with knocking critters unconscious now. :p
> 
> there is some bug in the engine, equipped items can not be taken from the NPC - this will be fixed. (armor can't be picked up for sure.)

So you're treating "equipped items go into inventory" for knocked out critters as a bug now?
I think it's reasonable that I can take the weapon/item from one's hands when knocked out, but strip off one's armor (just like clothes) should be probably only available on death.

**Comment by FakelsHub** [comment]
> So you're treating "equipped items go into inventory" for knocked out critters as a bug now?

The engine removes all equipped items before showing the inventory, and I have not yet found out why these items (armor) remain in the inventory.

> The problem with HOOK_ONDEATH is that it won't fetch armors dropped by explosion death,

it seems there is a difference in the runs of the hook when you have, and no party members.
It seems that if there is a party member, then the hook is performed before dropped items from the explosion. :\

**Comment by Lexx2k** [comment]
I've changed it to a map_enter variant now. That means, armor gets deleted the moment player is in a new map... this should solve all issues.

**Comment by FakelsHub** [comment]
> That means, armor gets deleted the moment player is in a new map... this should solve all issues.

Now check their armor modifiers to see if they were broken after you removed their armor.

**Comment by Lexx2k** [comment]
Oh right, I totally forgot that this was a possible issue .... I'll check it once I'm back home.

**Comment by NovaRain** [comment]
I tested the script in New Reno (since Salvatore's men are wearing metal armor). Their armor stats got dropped when I enter the map for the first time, only after reloading the map (re-enter or save&load) their armor stats return to normal.

**Comment by FakelsHub** [comment]
this was expected.
later, I will write you a script in combined hook variant with the fix of the take armor in knockout.

**Comment by NovaRain** [comment]
> 
> 
> this was expected.
> later, I will write you a script in combined hook variant with the fix of the take armor in knockout.

There's a version using multiple hooks in previous commit.

**Comment by Lexx2k** [comment]
Guess this issue can be closed then.
