### ISSUE TITLE
Gizmo's sign stops rotating on quicksave

### ISSUE THREAD

**Issue by burner1024** [rotators/Fo1in2#39]
Reload or re-entering map fixes it.
![Captura de pantalla de 2020-02-17 23-01-37](https://user-images.githubusercontent.com/1279852/74669384-98b56800-51d9-11ea-806b-976f5e1e23b9.png)

**Comment by Lexx2k** [comment]
It's using the same code as any other animated object (example: animfrvr). It's just map_update being the way it is.

**Comment by burner1024** [comment]
[SLOT10.zip](https://github.com/rotators/Fo1in2/files/4215025/SLOT10.zip)
A save for the reference.

**Comment by Lexx2k** [comment]
For me it looks good now. Couldn't make animated objects stop anymore.
