### ISSUE TITLE
"Tell me about" dialog function

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#4]
~This feature is not impossible to implement, but also requires advanced skills to pull off.~ 

~We started experimenting with it, but so far nothing serious has been accomplished.~ 
~At this point it's not very likely to happen anytime soon (or at all), though.~

**Status:**
- [x] the "tell me about"-button appears too early / is visible too long.
- [x] lowercase / uppercase characters should not matter when comparing keywords.
- [x] move keys / letters to .ini file for multi-language support.
- [x] using dialog options to enter the barter screen breaks the TMA function when returning to dialog mode.
- [x] the "input box" fake obviously has no text appearing in it
- [x] the barter button needs to be disabled while the input box is open.
- [x] Pressing the "switch hands" button on the main interface will open the barter interface. 
- [x] the ok/cancel buttons on the input box fake will be moved to the background after clicking anywhere on the fake image.
- [x] the buttons aren't correctly aligned, because of the damn window rounding issue (the fake input box graphic has 512px width and works because of that).
- [x] can't delete text. Only refresh the input with hitting enter-key, or pressing the ok-button.
- [x] would be good to somehow fetch the last used Reply() from the critter, so that it can be printed again after the input box has been closed (like it happens in Fo1). Maybe a new _get_dialog_message_?

**Comment by FakelsHub** [comment]
I would not advise you make this feature. :-) 
But if there is a desire, then its implementation lies entirely through the by sfall engine, need adding new functions for processing.

**Comment by Lexx2k** [comment]
Yeah, we started reversing some Fallout stuff for it, but it's kinda stuck now. Not sure if it will ever happen, but who knows...

**Comment by Lexx2k** [comment]
Anything that gets this a step closer would be awesome.

**Comment by Lexx2k** [comment]
Current status: ([Screenshot](https://i.imgur.com/M9YqVfO.png))

Remaining issues:
- need to convert string from .msg to uppercase to compare it with player input (or rewrite all strings to uppercase in the .msg file directly, whatever is easier to do, I guess)
- the "input box" fake obviously has no text appearing in it
- the ok/cancel buttons on the input box fake will be moved to the background after clicking anywhere on the fake image
- obviously the text you can type in is rather limited, because it's just a shitty test-hack right now
- would be good to somehow fetch the last used Reply() from the critter, so that it can be printed again after the input box has been closed (like it happens in Fo1)

Obviously a real input box would be the way to go, but the garbage I cooked works for some early prototype testing.

The way of how the critter text source is chosen (either special defined critter or by current map) is crap as well... but works for now.
It would be better to put a variable / macro / array directly into the critter script talk_p_proc. This would give a lot more control over who's able to print what text message. It's a lot work, but would only need to be done once. After that it's highly flexible.

**Comment by FakelsHub** [comment]
It is possible to make the input text in your window in text bar, the only problem is the script keys Done and Cancel (when you enter text they will not be processed by Enter and Esc).

**Comment by FakelsHub** [comment]
> (or rewrite all strings to uppercase in the .msg file directly, whatever is easier to do, I guess)

I will add a case-insensitive comparison function.

**Comment by FakelsHub** [comment]
> the ok/cancel buttons on the input box fake will be moved to the background after clicking anywhere on the fake image.

You did not correctly create the buttons, they should be created for the current window, not for a separate window.

**Comment by Lexx2k** [comment]
> You did not correctly create the buttons, they should be created for the current window, not for a separate window.

I did it like that before, but must have done something wrong, because the buttons didn't appear at all in that case. I'll investigate again.

**Comment by Lexx2k** [comment]
Alright, latest commit fixes and tweaks some more stuff. Guess I'm pretty much at the end of my skills now. Everything else that's still required to be done lies outside of my programming expertise.

What I could still do is changing how the reply data is fetched (setting variables or something in critter script talk_p_proc), but this is a lot work and I don't really see a reason to do that right now. Better to tweak/ rewrite this stuff when everything else is working.

**Comment by FakelsHub** [comment]
> PS: I noticed there is a bug with the barter button. When starting up the dialog screen, it won't switch between up/down images. 

this is a bug of the engine, I came to the conclusion that it is not necessary to fix it, as it will require code changes in many places.

**Comment by Lexx2k** [comment]
I noticed this for the first time now after all these years, so yeah, it isn't really important.

**Comment by FakelsHub** [comment]
Maybe a new get_dialog_message?

Ок. get_last_reply

**Comment by Lexx2k** [comment]
Thanks.

I noticed an interesting issue with string_split(). If I press enter in my tma script, it works perfect, but if I press the ok button which calls the generate_reply procedure, string_split only returns 0 and thus none of the keywords will work. I have no idea why this is happening - it makes no sense to me.

**Comment by Lexx2k** [comment]
Alright, thanks to your help, this feature is almost complete. As far as I can tell right now, only one thing is left to do: We need to be able to convert string to uppercase, for easier comparison. For the generic keywords this isn't an issue, but sadly the name-related responses won't work: `input == obj_name(critter)` 
^ input will never be critter name, unless the name is written in all caps.

**Comment by FakelsHub** [comment]
I already wrote above that I will add a comparison function without case.
Also need to add a function that returns the width of the text and an additional game mode of the animation interface.

**Comment by FakelsHub** [comment]
> Fixed the bottom right grey line with changing create_win("tellme_interface", (Scr_Width - 320), Scr_Height, 640, 190); << it was 641 before (on purpose?)

wanted to clarify once again. the fix on 640px doesn't cause you to crash the game?

**Comment by Lexx2k** [comment]
No crash. Works fine and looks perfect.

**Comment by FakelsHub** [comment]
**Unfortunately, we cannot add the case-insensitive text comparison function, as this will not work for text in languages other than English.**

**Comment by Lexx2k** [comment]
How about a toggle button then?

I understand the reasoning, but as it stands right now, there are no languages other than english for this mod, and considering the track record of Fallout mod translations, I'm highly pessimistic about there ever going to be more.

The way TMA work right now / will work in the future, it'll require more than a simple search&replace of language strings. You'll have to go over everything and there's going to be a lot more that needs manual translations.

**Comment by FakelsHub** [comment]
> I'm curious, why exactly does it not work with other languages? Is it because some languages don't have lower/uppercase characters? 

Something like this, the function simply does not know which characters are lowercase.
This is valid only for national characters, within the codes 128-255.

Well ok I'll add a function.

**Comment by Lexx2k** [comment]
> Well ok I'll add a function.

Thanks! 

The project is open source, so if there really will be another translation in the future, it shouldn't be a problem to adjust the scripts accordingly.

**Comment by Lexx2k** [comment]
string_compare works perfect. Thanks again.

get_text_width is a bit confusing, probably because I don't know how exactly width is calculated. 
With checking for < 240, it seems to stop correctly when writing WWWWWWWW... but as soon as I write WWWWW...Wfff it fucks up and goes beyond 240px.

**Comment by FakelsHub** [comment]
> Regarding "using dialog options to enter the barter screen breaks the TMA function when returning to dialog mode."

I tested the script so I did not understand what the problem is, "Unset TMA data." it happens only when you leave/exit the dialogue.

**Comment by Lexx2k** [comment]
Everything works when using the button on the interface. For me it happens as soon as I enter the barter mode via dialog option.

**Comment by Lexx2k** [comment]
Here's a video of it in action:
https://www.youtube.com/watch?v=6FCJmVKRyY0&feature=youtu.be

**Comment by FakelsHub** [comment]
why do you testing the game without enabled debugging window?. Enable debugging and see what happens during the transition to barter mode.
give me your saving I did try.

> PS: Another tiny issue that isn't very important but still exists. I've added a _

OK. I'll watch it.

**Comment by Lexx2k** [comment]
> give me your saving I did try.

You just have to start a new game, teleport to Hub Downtown and talk to Mitch. Same happens to Mrs. Stapleton (here the TMA button doesn't even get created), as well as Beth. 

The only merchant that worked so far is the one in Shady Sands east side (this is how I found out about the gdialog_mod_barter() above).

**Comment by FakelsHub** [comment]
I haven't played Fallout 1 in 20 years you want me to find a trader in Shady Sands it won't be an easy task))

**Comment by Lexx2k** [comment]
He is near the green exit grid. :p
His script is \02shady\barter.ssl

PS: Maybe you should replay Fallout 1. :>

**Comment by FakelsHub** [comment]
I found it) Everything is OK with it when going into barter mode from the dialog and clicking the "Tell" button again. I'll record a video. 
Do add a check on `dialog_obj` if this is causing you a problem.
But it would be necessary to understand why you have such a problem, and I do not have it.

**Comment by FakelsHub** [comment]
>  I've added a _ as a typing indicator. 

```
procedure do_up_ok begin
   ButPres := false;
   play_sfx(SoundR);
   if (input != "") then begin
      call ClearInputBox;
      Format("_", 200, 102, 240, 14, justifyleft);  <<<<<<<<<<<<<< ADD
      ShowWin; // redraw tellme interface
      call GenerateReply;
   end
end
```

**Comment by Lexx2k** [comment]
I could swear I've tried exactly the same and it didn't work. Welp, it works now, so yay I guess.

**Comment by FakelsHub** [comment]
> For me it happens as soon as I enter the barter mode via dialog option. This breaks TMA - either the button doesn't get created anymore, or clicking the button doesn't do anything (because the array is cleared).

Does anyone else have the same problem as you?

**Comment by Lexx2k** [comment]
Doesn't work for me. I posted on NMA and asked others to check. So far no response, though.

**Comment by FakelsHub** [comment]
OK. wait response.

**Comment by Lexx2k** [comment]
Did you recompile the script or test with the *.int from repo? Maybe it's a compiler settings issue?

**Comment by FakelsHub** [comment]
Recompile in sfall script editor.
I tried disabling the -s option, but that also didn't cause me a problem.

**Comment by Lexx2k** [comment]
[Bug was confirmed](https://www.nma-fallout.com/threads/fallout-et-tu-beta-release.218045/page-15#post-4352314):
> Yes, I can confirm this bug, tested all three of the mentioned NPCs. Funny thing: When I tried Mitch, the TMA button at least had the click animation and sound. With the other two, the TMA button wasn't even clickable.

**Comment by FakelsHub** [comment]
Paste this debugging code after this line and send a log.
https://github.com/rotators/Fo1in2/blob/009c2c43aca67afdb35bb27931dae473e79b341e/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_tellmeabout.ssl#L98

```
tmp := get_sfall_arg;
debug_msg(”=========");
debug_msg(”p.mode" + get_sfall_arg + "/" + prev_mode);
debug_msg(”mode" + game_mode);
```

**Comment by Lexx2k** [comment]
[Here is the debug.log file](https://pastebin.com/xkxZ678q).

**Comment by FakelsHub** [comment]
This bug appeared in the current dev version sfall.

**Comment by Lexx2k** [comment]
Thanks for the update. It's working now as intended. Couldn't find any other bug, so I'd say we can consider this ticket closed. :1st_place_medal: 

There is still one thing that annoys me - if you enter the barter interface and return to dialog, the $x caps number in the left window disappears. But this isn't on TMA, it's a default Fo2 thing.

**Comment by Lexx2k** [comment]
Ok, I actually did find another issue with the TMA button.

If you talk to potential party members for the first time, the button gets created. If they now join your party, the button is still visible in the dialog -> party dialog transition. I'm assuming this isn't covered by the "SPECIAL" game_mode?

**Comment by FakelsHub** [comment]
>  If they now join your party, the button is still visible in the dialog -> party dialog transition.

???
After joining there is an automatic exit from the dialog system.

**Comment by Lexx2k** [comment]
Not in (all) Fo1 party members. :) Some end in another dialog option.
I guess I could remove that. It's not like players would notice.

**Comment by FakelsHub** [comment]
Yes I see a bug, the button is not removed during the animation.

**Comment by FakelsHub** [comment]
fucking button & fucking function!!!

**Comment by Lexx2k** [comment]
It's working now. Thanks once more!

**Comment by FakelsHub** [comment]
> - Miles Power Armor dialog would prevent the creation of the TMA-button (dialog starts at Message(x) reply which seems to be the cause of problems again)

Again fucking button?

> - Also, why the hell is the player money counter changing it's position by 1px randomly? Changing it in gl_tma seems to work... for a while. Then at some point it stops and is shifted by 1px again. Seems like this only affects the money counter and nothing else.

Don't get hung up on little things.

**Comment by FakelsHub** [comment]
It seems that again I broke the dialog mode)
I'll fix it tomorrow.

**Comment by Lexx2k** [comment]
>Don't get hung up on little things.

The little things are what differentiates a simple mod from a professional project. :p 
I'm wondering if this is happening due to disabled window rounding. It's interesting that it doesn't appear randomly after game start. Sometimes it works for hours and then out of nowhere it doesn't anymore. Weird.

**Comment by FakelsHub** [comment]
This is the alignment of the text in the center relative to the width of the text field.

**Comment by Lexx2k** [comment]
Does the width of the text field change dynamically? If not then I don't understand why it would change position at some point. I tested this in different dialogs once the "shifting" happens, and it was the same everywhere.

**Comment by FakelsHub** [comment]
The width of the field does not change, the width of the text changes from the amount money.

**Comment by Lexx2k** [comment]
You're right, this seems to be the issue. Ugh, annoying.
I mean, there's still a possible workaround... could make the window smaller again and keep showing the original money counter, then it for sure won't happen. I will think about how much this will annoy me.

**Comment by FakelsHub** [comment]
Perhaps you need to choose a different field width for the text (I didn’t do this, I just chose a guess value)

**Comment by FakelsHub** [comment]
I'll see in the engine what value is used for the width there.

**Comment by FakelsHub** [comment]
` Format("$" + dude_caps, 3, 36, 70, 15, justifycenter);`
try replace code to
```
text := "$" + dude_caps;
w := text_width(text);
if w > 60 then w := 60;
Format(text, 38 - (w / 2), 36, w, 15, justifycenter);
```
so is used in engine.

**Comment by Lexx2k** [comment]
The second version works perfect, thanks once more! :>
Kinda weird how complicated BI made this, instead of just fixed width + center text.

**Comment by FakelsHub** [comment]
there is nothing complicated, the value 38 is the position by X. 
X is the center.

**Comment by wipe2238** [comment]
Turns out TMA is throwing `EXCEPTION_ACCESS_VIOLATION` when game is running with debugger attached (and only then), at least when using x32dbg

From this line...
https://github.com/rotators/Fo1in2/blob/77da35055c8ed1c045e240e2ec62790ef28137e5/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_tma.ssl#L230
...game goes to `deleteWindow_`, and at `0x4b7927` tries to `call dword ptr ds:[_deleteWindowFunc]` (aka `0x00672D84`, which at the time is just a bunch of zeroes)

It can be "fixed" with scripted BlockCall, which seems to work fine so far...
```pascal
write_int( 0x4B7927, 0x90909090 );
write_short( 0x4B792B, 0x9090 );
```
...but i have no bloody idea will it lead to new bugs or not, and is it safe to commit.

**Comment by FakelsHub** [comment]
The problem is in the script, the window has already been deleted.
Make a checking of the deleted windows.

**Comment by FakelsHub** [comment]
The problem is in the script, the window has already been deleted.
Make a checking of the deleted windows.

**Comment by FakelsHub** [comment]
Checking for zeros in the engine is available.

**Comment by Lexx2k** [comment]
I've added a new check, but I'm not sure if that's really the case here. `delete_button` always only gets called when tellme_button condition is true.
