### ISSUE TITLE
Flavour text missing

### ISSUE THREAD

**Issue by NefariusBredd** [rotators/Fo1in2#40]
Just started a new play-through and noticed the text that appears in your display monitor re large amounts of rat faeces in the second cave of the starting area doesn't appear.

Also the door control is described as destroyed when hovering over it, not w/e the blurb is in FO1.

**Comment by Lexx2k** [comment]
Fixed the V13 door terminal.

Ratpit message shows up correctly for me. Keep in mind that it has a perception roll - you might have just failed it.

**Comment by NefariusBredd** [comment]
Yeah, my bad. Just rolled a 10 PE guy and I got it.
