### ISSUE TITLE
Vanilla sfall compatibility

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#41]
- [x] Create comfy codecave(s) for custom asm
  While using `_defam` is safe now, it _still_ requires rfall and custom hooks to prepare/restore that memory area. Once we have a better place for all of our stuff, we can move on to other points.

- [x] Port `VirtualProtect` stuff to codecave(s)
  This is currently written to `___begtext` during rfall initialization, and used by at least one of voodoo macros, so it has to be done sooner or later.

- [x]  Tweak existing voodoo macros to use codecave(s) instead of `_defam`
  With sfall-asm this shouldn't take much time, i think; minor edits to some of patchfiles, regenerate macros/procedures and update voodoo header. Once this point is done, mod should be vanilla-friendly already. Features which still needs rfall are experiments and does not affect gameplay in any way.

- [ ] Re-visit voodoo macros and officially ask sfall team to support required features :)
  This one is _kinda_ optional - even if we fail all speech checks here, previous points will ensure that mod will continue to work with vanilla sfall without loosing any of our beloved features.

  - Features which are not a part of sfall
    - [x] `VOODOO_location_discover_radius` phobos2077/sfall@e7e5da866a45bd55a8eb482aa6c6d56f0becd92b
    - [x] `VOODOO_fill_w` phobos2077/sfall@eddefd6bd5afe43c64523bd06134551ed9cc8c82
    - [x] `VOODOO_dialog_money_fix` -- phobos2077/sfall@4487bbfeba88b402d7e8ecf7484f7fa51ddf228a
    - [ ] `VOODOO_display_win_redraw` (phobos2077/sfall#282)
    - [x] `VOODOO_CAVE` -- [rejected](https://github.com/phobos2077/sfall/issues/285#issuecomment-589597459)
    Should be requested as `write_byte(address, value, lenght)`
  - Features which should stay as part of voodoo.h
    - `VOODOO_disable_YouEncounter_message`
    - `VOODOO_rest_till0600`
    - `VOODOO_dogmeat_pm_dialog`
    - `VOODOO_remove_circle_name`

I'm setting milestone for this one to v1.2 as v1.1 is around the corner i wouldn't want to delay it if we won't be able to finish all what's needed before deadline, for w/e reason. So battleplan is:
- v1.1 releases as planned, with ingame fixes/features already in place and rfall requirement
- v1.2 focus on making mod work with vanilla sfall; for a most part this shouldn't need Lexx's attention (except final tweaks and testing), so he can work on his other project in peace without distractions... unless he decides to jump in on his own :>

I consider vanilla compatibility important enough to justify separate release, even if it won't introduce anything visible to players. Feel free to [disagree](https://www.xkcd.com/386/).

**Comment by wipe2238** [comment]
For a good start, we're stealing memzone occupied by few `main_selfrun` functions from rich exe and give that to poor mod. These functions are responsible for ingame recording, and are called after pressing CTRL+R on main menu. This is a new home for our voodoo stuff.

As hotkey is blocked from scripts, that means feature is **still** available until first start/load game. If anyone still want to record selfruns (dunno why anyone would want that, whole feature is broken), game needs to be restarted. Acceptable price.

This area gives us whooping 438 bytes of memory which can be used for whatever stuff we need. After blocking hotkey, engine never uses cleared functions and there's near-zero chance sfall will ever touch that zone - unless sfall team decides to fix it (it's horribly broken as of today), which is probably more work than it's worth; feature is _**so popular**_ i had no idea it exists until week or two ago.

**Comment by FakelsHub** [comment]
CTRL+R is used for testing.

**Comment by Lexx2k** [comment]
What exactly do you test in selfrun record mode?

**Comment by fedprod** [comment]
You don't need to record anything, leave it empty and warp to any map to test scripts?

**Comment by Lexx2k** [comment]
You don't do this with CTRL+R, that's why we have other dev-tools with far more power.

**Comment by ghost2238** [comment]
Did some work on this now and retested the functionality with new versions of patches which were generated from the patch sources in https://github.com/ghost2238/sfall-asm - I hope I didn't break anything.

As Wipe found, we didn't need to port VirtualProtect, it was already a known symbol inside fallout2.exe that I've overlooked in some rush to complete the radius fix patch.

**Comment by wipe2238** [comment]
Oright, closing this one as we already achieved ~~nirvana~~ vanilla sfall compatibility, and only thing left on list is actually HRP bug.
Fix we have, even if crappy, can break only on HRP update, so don't do that folks 😉
