### ISSUE TITLE
Caleb Dialog Bug

### ISSUE THREAD

**Issue by fedprod** [rotators/Fo1in2#42]
Caleb's Dialog (Chief Guards in Adytum) has some wrong references after one spoke to Zimmerman.
Since the dialogue file is literally the same as vanilla, I smell a script bug? Hopefully it's one of  the very last scripts to fix for LA, at least an easy one, I know how... "wild" the scripts for LA where originally ^^"

### In short:
Line 1 references: {140} answer {145}, should be: {142} answer {145}
Line 2 references: {141} answer {146}, should be: {143} answer [146}
Line 3 references: {142} end dialog, should be: {144}
See also [Screenshot w/ german translation applied](https://i.imgur.com/YoPL0gy.png)

### In detail:
Line 1 references line ***{140}{}{Alright, I get the picture. I'll go talk to Zimmerman.}***, wich is the PC End Dialog option before talking with Zimmerman, but answers with ***{145}{}{They're all to the north of here. You won't be able to miss their stench. Anything else?}***, wich is the answer to ***{142}{}{Where are the Blades?}***

Line 2 references ***{141}{}{So, Zimmerman gave you the scoop on the Blades. Whatever. I'm sure he'll want to know when you've done the job.}***, wich is his greeting after speaking with Zimmerman, but answers with ***{146}'Cause its a waste of our time. I got better things to do than get out there and kill a few skags. Take more time showerin' up afterwards than dealin' with them. Anything else?***, wich is the answer to ***{143}{}{Why haven't you guys taken care of it yourself?}***

Line 3 references ***{142}{}{Where are the Blades?}***, which is the PC End Dialog line, which should be ***{144}{}{Yeah, I'll be back when the job's done.}***

**Comment by Lexx2k** [comment]
Looks like this is still a vanilla bug that survived till today.
Till today.
