### ISSUE TITLE
Cannot get high resolution on fresh new install of Fo1, Fo2 and this mod

### ISSUE THREAD

**Issue by kafka2000** [rotators/Fo1in2#54]
Very excited to start using what looks a fabulous work, however cannot start playing Fallout 1 with the InterfaceUpscaled mod (infamous `warning` message appears).

My screen resolution is `1920 x 1080` but the game appears to be `800 x 680`.

The steps i did were:
* Install Fallout 1 and 2 from the Steam `Fallout Classic Collection`
* Downloaded, unzip and installed the `v1.1.1946` release (by starting`UNDAT.EXE`, etc. as described in the instructions)
* Modify `ddraw.ini` to uncomment the `PatchFile4=mods\InterfaceUpscaled` line

However as soon as the game starts with my character on the screen i get a warning message saying the resolution is too low. When i looked in the file `f2_res.ini` i could see that i got the following parameters:
```
GRAPHICS_MODE=2
```
```
; Set the Fullscreen resolution here.
SCR_WIDTH=1280
SCR_HEIGHT=720
```
Note that i have Windows 10, i.e. native DirectX 12

Any help would be greatly appreciated.

**Comment by kafka2000** [comment]
Ok i could solve it by installing [this Windows DX package](https://www.microsoft.com/en-us/download/details.aspx?id=35), however now the mouse cursor is severely lagging, and i have no idea how to prevent this very slow effect.

**Comment by Lexx2k** [comment]
The interface upscaled mod needs at least a 890x720px resolution. If you run the game with less than that, it won't work.

**Comment by kafka2000** [comment]
Thank you @Lexx2k for the feedback, the issue was the Direct X additional package to install on Windows 10. Now for the problem of the mouse being very slow and lagging it seems to be a general problem of Vsync which cannot be disabled on Windows 10.

I did not have to change anything in `f2_res.ini` (although i tried many things) so no i did not have `SCALE_2X=1` in it (just the default `SCALE_2X=0`). I could find a first solution by setting the graphics mode to 5 (DX9 windowed) in `ddraw.ini` and a resolution of `1920x1080`. The issue is that it adds an annoying top bar (red arrow on pic 1 attached), which in turns hide the bottom part of the screen (orrange arrow on pic 1).  Somehow i figured the height of this bar was 24 pixels so i set the resolution to `1920x1056` and now everything seems fine (pic 2 attached).

If anyone knows how to hide this top bar or run fullscreen without any mouse lag that would be ideal. Meanwhile i can live with what i got.

![pic1](https://user-images.githubusercontent.com/62185794/76692080-b7304700-6651-11ea-9f7d-d32aa19db26c.jpg)
![pic2](https://user-images.githubusercontent.com/62185794/76692096-e9da3f80-6651-11ea-8c77-a1ccefd1840d.png)

Below the relevant sections of my current `ddraw.ini`:
```
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[ExtraPatches]
;This section allows you to set multiple paths to folders containing mods or patches that will be loaded by the game
;The priority of read files will be higher than the files in patchXXX.dat
;If DataLoadOrderPatch is enabled, the data load order will be:
;master_patches > critter_patches > PatchFile99 - PatchFile0 > patchXXX.dat > ...
;Paths to folders and Fallout .dat files are supported. The available range for PatchFile option names is from 0 to 99
;The greater numbers take precedence over lesser numbers
;fo1_robodog needs to be after fo1_german, because of the modified text!
PatchFile0=mods\fo1_base
PatchFile1=mods\fo1_interface
PatchFile2=mods\fo1_classic_worldmap
PatchFile3=mods\Anim_ImprovedSMutantDeath
PatchFile4=mods\InterfaceUpscaled
;PatchFile5=mods\fo1_barter_formula
;PatchFile6=mods\fo1_german
;PatchFile7=mods\fo1_robodog

;Path to the folder in which the game will automatically search and load custom .dat files
;The data load order of the .dat files in the folder will be in reverse alphabetical order of the filenames
;The .dat files specified in the PatchFileXX options will have higher priority than others
;Uncomment the option to specify a different folder path. The default path is <GameRoot>\mods\
;AutoSearchPath=mods

;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[Graphics]
;Set to 0 for 8 bit fullscreen
;Set to 4 for DX9 fullscreen
;Set to 5 for DX9 windowed
;A DX9 mode is required for any graphics related script extender functions to work (i.e. fullscreen shaders)
;Modes 1, 2 and 3 are no longer supported
Mode=5

;If using a DX9 mode, this changes the resolution
;The graphics are simply stretched to fit the new window; this does _not_ let you see more of the map
;If set to 0, use Fallout's native resolution
GraphicsWidth=1920
GraphicsHeight=1056
;GraphicsWidth=1280
;GraphicsHeight=720
;GraphicsWidth=0
;GraphicsHeight=0

;Set to 1 to do the palette conversion on the GPU
;Set to 2 to do the palette conversion on the CPU
;Set to 0 to pick automatically
;GPU is faster, but requires v2.0 pixel shader support
GPUBlt=0

;Set to 1 to allow using 32-bit textures for talking heads
;The texture files should be placed in art\heads\<name of the talking head FRM file>\ (w/o extension)
;The files in the folder should be numbered according to the number of frames in the talking head FRM file (0.png, 1.png, etc.)
;See the text file in the modders pack for a detailed description
;Requires DX9 graphics mode and v2.0 pixel shader support (see GPUBlt option)
Use32BitHeadGraphics=0

;Set to 1 to automatically search for alternative avi video files when Fallout tries to play the game movies
;Requires graphics mode 4 or 5
AllowDShowMovies=0

;Fade effect time percentage modifier
;Default is 100. Decrease/increase this value to speed up/slow down fade effects
FadeMultiplier=100
```

**Comment by Lexx2k** [comment]
Yeah, you've set the game to window mode (5, as written in the comments above it), which is why you see the game title bar. You should set it to 4 for fullscreen OR you set it to 0 and instead set GRAPHICS_MODE=2,as well as WINDOWED=1 and WINDOWED_FULLSCREEN=1 in the f2_res.ini file. You have to play around with these settings.

**Comment by kafka2000** [comment]
Thanks gain @Lexx2k for your help on this. Just as a feedback for those having the same issues:
* The resolution was too high with the solution of `Mode=0` in `ddraw.ini` (whatever resolution i then choose in `ddraw.ini` or `f2_res.ini` it would always be my screen resolution of `1980x1024` which would display my character way too small)
* The best compromise was therefore my original settings of `Mode=5` with the custom resolution to avoid missing the bottom most image border (cf post above)
* I still had a big issue with combats during which i would miss all the character action turns with instead the Windows "spinning circle" appearing during each action turn. I could solve this by setting `EXTRA_WIN_MSG_CHECKS=1` in `f2_res.ini` (this was a lifesaver)
Hopefully this could be useful to others.
