### ISSUE TITLE
Suggestion of FIXT configuration if only a few options chosen

### ISSUE THREAD

**Issue by kafka2000** [rotators/Fo1in2#55]
I am interested in having a very few options from `FIX`. From what i read the `Fo1in2` mod already takes care of all the bugs corrected by `FIXT` and even takes care of the bugs introduced by `FIXT` so i would like to absolutely avoid re-introducing bugs.

I am interested in activating the following options:
```
[FIXT]
; Does Agatha exist in Shady Sands?
GVAR_AGATHA_IS_ENABLED=1

; Able to have intimate relations with Lorri?
GVAR_BOS_LORRI_SEX_ENABLED=1

; Do the "active" hookers exist in The Hub's Downtown?
GVAR_ENABLE_HOOKERS=1
```
But it is indicated that "Most of [these] settings will only work if `GVAR_FIXT_ENABLED=1` (cf below), which may reintroduce bugs i'm afraid. So what is the best way to activate the options above? Put `GVAR_FIXT_ENABLED` to 0 or to 1? Or should none of the options above be activated to avoid bugs?

```
[FIXT]
; Enable / Disable all Fixt additions?
; Most of the following settings will only work if this is set to 1!
GVAR_FIXT_ENABLED=0
```

**Comment by Lexx2k** [comment]
The effect of GVAR_FIXT_ENABLED=1 isn't that dramatic. It'll enable some of the following settings + some other minor stuff here and there. Don't really remember the details right now, In any case, it barely has influence and I wouldn't worry about bugs, because I fixed everything I was able to find.

**Comment by kafka2000** [comment]
Excellent, thank you very much @Lexx2k
