### ISSUE TITLE
First mission in Shady Sands not accessible [bug?]

### ISSUE THREAD

**Issue by kafka2000** [rotators/Fo1in2#56]
I talked with Seth about the Radscorpions and after doing various things in Shady Sands i no longer have the options to go to the Radscorpions cave, how is this possible?

Attached the associated saved game (please let me know if more info is needed).
[SLOT03.zip](https://github.com/rotators/Fo1in2/files/4334428/SLOT03.zip)

**Comment by kafka2000** [comment]
Ok so actually the bug is not in Seth's dialogue but about the PipBoy not listing Radscorpions Cave (it appears as a circle but on the list on the right). At least i assume it had to be listed, maybe it didn't

**Comment by Lexx2k** [comment]
Small circles never appear in the location list, it's kinda intended.
