### ISSUE TITLE
No background music

### ISSUE THREAD

**Issue by kafka2000** [rotators/Fo1in2#57]
Apologies if I am missing something out but I have no music background or virtually none (I think I heard some in Shady Sands once or twice randomly).

How to activate the background music? Could there be an issue with the music files path?

Is there maybe even a music mod addressing this issue?

For example in the Hub everything completely silence except for the random bird noise. I just arrived in Necropolis and complete silence again.

**Comment by Lexx2k** [comment]
One of the GOG or Steam releases has the music files in the wrong folder. The background music you are hearing the are tracks from Fo1 that aren't in Fo2. 
Check your Fallout 2 folder for \music\ and move the files to the \data\sound\music\ folder. If the folders don't exist, create them.

**Comment by kafka2000** [comment]
Thanks a bunch for the prompt feedback! Ok i just did that and the only files in common were `akiss.acm` (which seems different, different file size) and `12junktn.acm` (which seems the same, same file size). I kept the two files which were originally in `Fallout 2\Fallout1in2\data\sound\music`. The 19 new music files should solve the problem! I was a bit late to react but glad i didn't play the whole game without music thanks to your help.

**Comment by Lexx2k** [comment]
akiss.acm is the Maybe song from Fo1. It's renamed to override Fo2's credits song.
Not sure about 12junktn.acm - probably thought it wasn't in Fo2 and put it into the files as well.

**Comment by brussell1** [comment]
I've think this really should be addressed in the readme.
