### ISSUE TITLE
JunkTown dialogues not matching accomplished quests

### ISSUE THREAD

**Issue by kafka2000** [rotators/Fo1in2#58]
Likely not a bug from this mod itself , but coming back to JunkTown later in the game (after killing Gizmo, etc.) is as if no JunkTown citizen remember the Vault Dweller. The dialogues even include an option to ask who is Gizmo, when everyone should actually know that it is the Vault Dweller who killed him.

**Comment by kafka2000** [comment]
A similar issue happened in Boneyard. After getting talking with Razor (the head of the Blades) and getting rid of all the Regulators for her, when i see her back she asks me who i am. Then the she's like "Oh you got rid of the regulators, that's a great coincidence that's what we wanted". I now remember that one of the only thing which almost put me off fallout 1 when i first played it was this complete "amnesia" of the game NPCs which destroyed the atmosphere (these kinds of bugs inconsistencies completely break the game immersion). Again, not a bug from this mod but of the original game.

**Comment by kafka2000** [comment]
To investigate this more easily, attached an associated savegame (just before going talking with Razor). I'd assume going to JunkTown within this savegame would also show the amnesia problem from Killian and Lars:
[SLOT05_amnesia.zip](https://github.com/rotators/Fo1in2/files/4387712/SLOT05_amnesia.zip)

**Comment by Lexx2k** [comment]
Yes, that's vanilla Fo1. Don't know if I will ever do something about it, because it requires some serious script rewrites.

**Comment by kafka2000** [comment]
Sure i understand. At least the savegame will be there if anyone would ever want to have a look at it.

This was the one bug I found massively off putting about the game: the player would be forgotten by the main NPCs, or as bad, the main player actions would be completely ignored / forgotten by the core NPCs.
