### ISSUE TITLE
Economy / Barter formula

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#6]
The current Fo1 barter formula is working as intended, but the problem is... it's highly flawed. 

Prices are easily fucked up, and it's pretty common to be able to buy items cheap and re-sell it at the same merchant for a higher prices. Best example for this is Mitch in the Hub: You can buy a Geiger Counter for ~500 caps and sell it back for up to 650 caps. 
This is a big no-no.

The question now is: 
- Will we tweak the Fo1 barter formula to prevent this, or ...
- ... will we revert back to the Fo2 formula and instead add stronger barter modifiers?

At the end of the day, the price calculation will not be "vanilla Fo1" anymore. It's just a matter of how to best approach this issue.

**Comment by Lexx2k** [comment]
Making it optional could be done, but I've been thinking about it for a while now and considering the vanilla Fo1 barter prices are inherently broken, I don't think we should keep it. Most players probably wouldn't even notice if it's gone.

I'm not too much a fan of a toggle option between Fo1/Fo2 calculation in this case either, because it means more files need to be touched. We can't _just_ enable/disable gl_z_fo1barter.int, because we also have to change / tweak the barter modifiers for each merchant NPC.

**Comment by FakelsHub** [comment]
think that the formula should correspond to F1 or have its modification as a fixes.

**Comment by burner1024** [comment]
I would just use FO2 formula and be done with it.

**Comment by Lexx2k** [comment]
I have reverted to the Fo2 formula for now, because I seriously have no motivation to deal with it at the moment.

My problem with the Fo2 formula is that it feels like the barter skill isn't really worth it in lower % ranges. With the Fo1 formula you feel a noticeable difference between 20% and 80% - it's really worth it to put points into the skill.
With the Fo2 formula you have to sink in a lot more skill points, which is a bit of a problem in Fo1, as you can only gain 21 levels and usually the game is over between level 15 and 18.

**Comment by Lexx2k** [comment]
I have added a new mod that reverts all barter changes to Fo1 vanilla. https://github.com/rotators/Fo1in2/commit/f1eb640afd6212ecccf3b337a3aa9292712d905a

I don't advice on using it, but hey, it actually wasn't hard to make, so there's that.
