### ISSUE TITLE
Cannot repair water pump in Necropolis?

### ISSUE THREAD

**Issue by Sajjon** [rotators/Fo1in2#60]
Hello! Not sure this is an issue with Fo Et Tu, but maybe?

I have an item with the exact image as ["Junk"](https://fallout.fandom.com/wiki/Junk_(Fallout)) (that I found in the Deathclas section in the LA Boneyard, I think), however, for me the item is called "Pump Parts", not "Junk". **I have not found any parts/junk in the sewers of Necropolis**. Inspecting the "Pump parts", gives instruction "These parts could probably be used by Miles to fix the hydroponic farms". So is it the wrong item?

Standing in front of the broken water pump in Necropolis, I want to repair it. I'm bad at repair, only 17% according to skilldex. I have [Tool](https://fallout.fandom.com/wiki/Tool).

When I try:
1. Equip "Pump Parts" and try "use on" (yellow crosshair) on the pump results in message: "This item cannot be used on the pump"
2. Equip "Tools" on right hand, with "Pump parts" equipped in left hand, and "using Tools" on pump results in message: "This item cannot be used on the pump"
3. Using tools, but with "Pump parts" not equipped (but in inventory) results in same message: "This item cannot be used on the pump"
4. Using repair skill (yellow crosshair) often results in "You fail to repair the water pump", but sometimes results in "You fail to repair the water pump. It might need a new fuse". and sometimes 
"You cannot repair the water pump without a replacement vacuum pump"
5. Right clicking on the water pump and selecting inventory (identical to equipping and "use on"???) results in "this item cannot be used on the pump".

Sooo.... hmm... what am I doing wrong? Do I have the wrong item? Should the item be named "Junk", but unfortunately they share the same image, and unfortunately this incorrect item has the misleading name "pump parts" (which really sounds promising, right?).

Or is it a bug in Fo Et Tu?

I downloaded the version "Fallout1in2 v1.1.1946" from Github.

**Comment by Lexx2k** [comment]
The Boneyard Pump Parts are only for the Boneyard quest. They will not work in Necropolis. You have to find the correct item in the Necropolis sewers.

**Comment by Sajjon** [comment]
@Lexx2k OK sorry for the confusion! I was just pretty sure it was the correct item, hehe, the name indicated so much. 

I will take another look through the sewers then, thanks!
