### ISSUE TITLE
Game crash in Adytum

### ISSUE THREAD

**Issue by mjjhat** [rotators/Fo1in2#61]
There is an issue with storming Boneyard with the help of the Blades gang after outfitting them with laser guns and combat armour. When the first of the blade members shoots a Regulator the whole game crashes every time. There is no way around it that I can see.

**Comment by Lexx2k** [comment]
Did you recently arrive with a caravan by chance?

Enter Adytum without the Blades, then exit the map. Try attacking with the Blades now.

https://github.com/rotators/Fo1in2/issues/31

**Comment by mjjhat** [comment]
Hello,

I did enter with a caravan. I eventually had to let the blades do the
attack without me. Not the best outcome, but better than not being able to
move forward in the plot line.

**Comment by Lexx2k** [comment]
Probably should have tried what I wrote, because I am sure it fixes it.

**Comment by mjjhat** [comment]
I did the "let them do it" option before I received your email, which had I
waited I would have had your answer not lot before my original posting:
next time I will be sure to try out your suggestion (and wait if I have an
issue)- thanks for your help.

**Comment by Lexx2k** [comment]
I think it's fixed. At least nobody else reported it anymore. Can open the ticket again if the issue comes back.

**Comment by gphoenix51** [comment]
I ran into something that I think was similar. I had my motorcycle on the Adytum screen and it kept crashing after I helped the Blades kill the Regulators. But after reading this, I moved my bike to the Blades hangout screen and it worked out fine. I have Fallout1in2 v1.9.3324.

**Comment by Aussiemon** [comment]
@Lexx2k I have this issue in both the latest release version and the latest commit of the master branch:
[SLOT02.zip](https://github.com/rotators/Fo1in2/files/14188356/SLOT02.zip)

1. Arrived in Adytum by caravan.
2. Took mentants and leveled up.
3. Killed the deathclaws and deathclaw mother.
4. Told Razor I'd talk to Zimmerman.
5. Waited 4 days for mentat debuff to expire.
6. Returned to Razor without leaving the area and chose to fight without talking to Zimmerman.
7. Crash occurs whenever I try to reload the save (before 6) after starting the regulator fight. It's usually a hard freeze, but sometimes a "memory referenced unexpected location" popup.

Leaving the area and returning unfortunately triggers the missing Razor bug (I believe Vanilla).
