### ISSUE TITLE
Crashing using german installations

### ISSUE THREAD

**Issue by brussell1** [rotators/Fo1in2#64]
After following the installation procedure using german versions of Fallout 1 and 2, it crashes while showing the "Get Ready" splash screen.
Crash message: "An integer divide by zero was encountered at address 006fe75c"

Using both english versions works fine.

Also, how do you use Fallout1in2 with your Uncut patch (http://fallout-files.de/index.php?c=details&f_id=8). Or is it not necessary?

**Comment by Lexx2k** [comment]
Just installing the uncut patch as usual should work fine.

The crash could be because language=english in the fallout2.cfg file while your master.dat is from the german version. It's trying to access files that aren't there and thus crashes.

**Comment by brussell1** [comment]
The crash was indeed caused by the language setting.  I think it would be appropriate to add this info to the readme for all the german players out there.

**Comment by fedprod** [comment]
did I forget to makle the uncut stuffs available?^^" Ooops

**Comment by Lexx2k** [comment]
Well, the uncut intro was never added. The animation files would be useless, because players can simply install the bloodpatch like always.
