### ISSUE TITLE
Gizmo corpse issue

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#69]
Gizmo corpse phase 2 is a container object with animation (flies around the decomposing body). 

The game sees this animation as "open/close" and thus will open/close the "container" constantly, which makes it impossible for the player to access the loot interface.

A workaround for this currently is to instead use the stealing skill on the container to access the loot window. Need to find some effective way to fix this (preferably something that doesn't involve making an extra fly-animation).

**Comment by wipe2238** [comment]
I feel like allowing stateless containers to play animation could be a nice sfall feature.

**Comment by Lexx2k** [comment]
Not really sure how it works, but forcing a container to be open at all times would mean the player can never open the loot interface (use action would try to close the container). Forcing a container to be closed at all times ~could~ maybe work, but it might also result in the player not being able to open the loot interface because mechanic-wise the container will always be closed. Really depends on how the engine handles this stuff.

**Comment by FakelsHub** [comment]
in use_p_proc, you should:
1. stop the animation.
2. set the current frame to 0: `set_object_data({ObjectPtr obj}, OBJ_DATA_CUR_FRM, 0);`
3. after the closed of the interface to start the animation.

**Comment by Lexx2k** [comment]
>     1. stop the animation.

How? `reg_anim_clear(self_obj);` ?

**Comment by FakelsHub** [comment]
Try all the functions, some should interrupt the eternal animation. perhaps just the set_object_data function will suffice.

I would use a separate fly animation object and place it above the gizmo table. and no problems.

**Comment by FakelsHub** [comment]
Unfortunately nothing will help you except this
> I would use a separate fly animation object and place it above the gizmo table. and no problems.

or make support for an animated container.

**Comment by Lexx2k** [comment]
Fuck it, I've just added a new flies object and spawn it over the container. https://github.com/rotators/Fo1in2/commit/0f6016fb5614d9bc5da1fe5ddad75fef794ce5ac
