### ISSUE TITLE
Punching bag animation issue

### ISSUE THREAD

**Issue by Lexx2k** [rotators/Fo1in2#70]
[ZSPNCHBG](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/GENERIC/ZSPNCHBG.ssl) currently plays the hand animation (use object) and then the attack animation.

Tried overwriting the "use object" animaton via `useanimobj` hook script:
```
procedure useanimobj_handler begin
   variable
      critter := get_sfall_arg,
      target := get_sfall_arg,
      use_anim := get_sfall_arg;

   if (obj_pid(target) == PID_PUNCHING_BAG) then begin
      if (get_script(target) == SCRIPT_ZSPNCHBG) then begin
         set_sfall_return(-1);
      end
   end
end
```
This works, but only the first time unless the player moves move away after running the code. Standing on the same hex next to the object and "using" it again will now play no animation at all.

**Comment by Lexx2k** [comment]
Yeh. For the punching bag issue I've decided to just [force one of the unarmed attack animations](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_fo1mechanics.ssl#L225) instead of the magic hands, and then do the same again for actually using the object. This now results in the player attacking the object twice instead of just once. However, it still looks better than if he would "use" the object first.

About playing magic hands when using something - you could just add the animation into the object script. I'm doing that with a few objects in ettu (repairing power generators, using key cards on the glow doors, etc).

**Comment by burner1024** [comment]
> About playing magic hands when using something - you could just add the animation into the object script. I'm doing that with a few objects in ettu (repairing power generators, etc).

I am doing it in object script (door). Or you mean the object in inventory? But the items with scripts don't stack, do they?

**Comment by Lexx2k** [comment]
I mean the scenery object (door, etc).

**Comment by burner1024** [comment]
Hm, could you link an example?
Maybe the difference is whether the inventory item has the "use" flag.

**Comment by Lexx2k** [comment]
This is the Necropolis waterpump: https://ci.appveyor.com/api/projects/rotators/sfall/artifacts/ddraw.dll?job=Configuration:%20ReleaseXP&branch=develop&pr=false

In vanilla Fo1 using the junk item on it will not play the magic hands animation.

**Comment by burner1024** [comment]
Thank. My code is pretty much the same. I think it'll have to be solved in sfall at some point.

**Comment by Lexx2k** [comment]
I got used to the current approach and would consider this solved for now.
