### ISSUE TITLE
Can't reveal the location of Necropolis label:bug

### ISSUE THREAD

**Issue by Dudejo** [rotators/Fo1in2#75]
I'm running the latest v1.3

Talking to Killian Darkwater or downloading Ms. Stapleton's holodisk no longer reveals the location of Necropolis on the world map.

**Comment by Lexx2k** [comment]
Killian seems to be an oversight. Can't find anything about the Vault disk revealing Necropolis in the scripts, though. Will have to check ingame later.

**Comment by Dudejo** [comment]
I booted up Fallout 1 (vanilla v1.1) to see for myself and no, her Holodisk still didn't reveal Necropolis' location. Sorry 'bout that, I haven't played the original in a long time.

Maybe it was a Fixt addition?

**Comment by Lexx2k** [comment]
Possible. Fixt did LOTS of smaller changes which aren't documented anywhere.
