### ISSUE TITLE
Issue with Brotherhood paladins in random encounters

### ISSUE THREAD

**Issue by Player701** [rotators/Fo1in2#80]
I've been doing a playthrough of this mod (pulled from the repo as of commit https://github.com/rotators/Fo1in2/commit/75ff5e771922a5ee8d1d2134206d0ba066ef4f8e), and while travelling on the world map somewhere near the Brotherhood bunker, I encountered a group of Brotherhood paladins fighting a large crowd of raiders. For some reason, the paladins were hostile to me, even though I had already completed the quest to become a Brotherhood initiate and could access the bunker freely (and even if I hadn't done that, I highly doubt that they were supposed to shoot me).

Having reloaded from a save file, I wandered a bit more and encountered another group of paladins fighting mutants. This time, the paladins did not attack me, although they seemed to not attack the mutants either. It seems to me that these encounter types are somewhat bugged. If necessary, I can provide a save file of my current playthrough to help reproduce these issues.

**Comment by Lexx2k** [comment]
Do you have a savegame of that by chance? I've checked exactly these encounters extensively due to one of the most recent fixes and never had issues with them. 

The only thing that can happen is that the paladins will attack you if they accidentally hit you for some reason. This is an engine thing and out of my control.

**Comment by Player701** [comment]
I have no save file of the encounter itself, but I made a save at the bunker entrance, from where they can be triggered relatively easily. It looks like all the save data is here: [SLOT01.zip](https://github.com/rotators/Fo1in2/files/5844112/SLOT01.zip). Please tell me if you need anything else.

> The only thing that can happen is that the paladins will attack you if they accidentally hit you for some reason.

Are you sure this isn't a typo? They will attack me if **they** accidentally hit **me**? If this is indeed the case (and not the other way around), then it's quite unfortunate, considering that 99% of the time the game puts my party right in between the opposing forces, and since some of those paladins wield miniguns, they have a very high chance of hitting me or one of my companions during the fight.

**Comment by Lexx2k** [comment]
Not a typo, it's an engine thing in Fo2 (and likely Fo1 as well, though I can't 100% confirm right now). If a critter "Ooops"'d you they will keep engaging you. This is a common issue with Killian and his guards, as example: https://github.com/rotators/Fo1in2/issues

**Comment by Player701** [comment]
Oh, well. Then I guess it's probably not a bug, according to what you're saying. Though you could still test it with my save file if you want... I'm new to the Fallout series and I have never actually played Fallout 2 before, so I'm not particularly aware of its engine quirks. Sorry about that.

**Comment by Lexx2k** [comment]
This is fixed with the latest Sfall.
