### ISSUE TITLE
Only 2 of the 3 crack assault paladins enter the military base

### ISSUE THREAD

**Issue by Player701** [rotators/Fo1in2#81]
Hello again. I have convinced the Brotherhood to send an assault team to help me take the military base, but when I enter the first indoors area, only 2 of the 3 paladins enter with me. Is this supposed to happen? The wiki says they aren't supposed to follow the player inside at all, I guess this is considered a bug and this mod fixes that... but not completely? Here's a save file made at the base entrance (the companions are not in the party and won't follow me inside, but the paladins will): [SLOT03.zip](https://github.com/rotators/Fo1in2/files/5851254/SLOT03.zip)

**Comment by Lexx2k** [comment]
Not a bug. And yes, in vanilla Fo1 they do not follow you inside. This is a Fixt change, which I kept.

**Comment by Player701** [comment]
I played Fixt too, before I started this playthrough. I'm pretty sure that I had all three paladins follow me inside the base during the assault. Although with the lack of the ability to tell them to move aside, they proved to be more of a nuisance than actual help - it's a good thing that this mod, or the FO2 engine, fixes that.

**Comment by Lexx2k** [comment]
I'm too lazy to check on it right now, but I'm 90% sure only 2 will follow you inside. There is a technical reason for that - unless Fixt somehow workarounded it.

And yes, they will most likely block your way on the lower levels. This is another reason why I kept the "only 2 will follow" -- to make them less annoying, even though Fo2 has a native push-function.

**Comment by Player701** [comment]
OK, I suppose I could be wrong about Fixt, even though I played it only a few days ago. Thanks for the clarification, I only reported this because it looked weird and no in-game explanation was provided (for example, having one of the two paladins say that the third one agreed to stand guard outside, or something similar to that, would've removed all my doubts).

**Comment by Lexx2k** [comment]
I thought that would be a bit obvious. :p
