### ISSUE TITLE
SCALING X2 stops working?

### ISSUE THREAD

**Issue by LoydMongo** [rotators/Fo1in2#82]
After a fresh install Fallout1in2 (or Et Tu) runs fine. I don't even touch the modifiable files, but the next time I start it up, X2 scaling doesn't work. It's checked in Screen Settings and the Graphic Mode has turned from 2 to 0 for some reason. f2_res.ini still has it set to 2 and ddraw.ini to Mode=4. Quite strange, can you help? And this the newest release Fallout1in2 v1.5.2288. Thank You!

**Comment by Lexx2k** [comment]
Sorry, not really. This is part of the High-Res patch and we don't have insight on its workings. However, if the setting is correctly set in the .ini file I think it's safe to assume that it works (personally I never use the ingame menu).

**Comment by LoydMongo** [comment]
I wouldn't have bothered you otherwise but this is the first time this has happened with any Fallout 1 or 2 mod, even the earlier versions of 1in2. Pretty sad, guess I'll go play Fallout 2 RPU. Thanks anyway!

**Comment by Lexx2k** [comment]
Why do you need x2 scaling anyways? You can just set your wanted resolution and the game does the rest.

**Comment by LoydMongo** [comment]
Yeah, tried that too, nothing works. It's all in my Windows 10 2560x1440 resolution for some reason. Can't read anything...

**Comment by LoydMongo** [comment]
RPU in the next folder over for example works just fine, I have no idea what is going on.

**Comment by Lexx2k** [comment]
You can try to copy over the f2_res.ini and f2_res.dll files and see if something happens.

**Comment by LoydMongo** [comment]
Will do, sorry and thanks.
