### ISSUE TITLE
Running in borderless windowed mode doesn't allow cursor moving to 2nd monitor

### ISSUE THREAD

**Issue by konjski-tramvaj** [rotators/Fo1in2#83]
Have run both Fallout 1 and 2 in borderless windowed mode with high resolution patch only and can successfully move mouse to other monitor why is this not possible in Fallout et tu?

**Comment by Lexx2k** [comment]
I have no idea. We are using the exact High-Res patch. Check the ddraw.ini and f2_res.ini files, other than that I can't really help.

**Comment by konjski-tramvaj** [comment]
> 
> 
> I have no idea. We are using the exact High-Res patch as everyone else. Check the ddraw.ini and f2_res.ini files, other than that I can't really help.

Found it, in ddraw.ini:


[Graphics]
;Set to 0 for 8 bit fullscreen
;Set to 4 for dx9 fullscreen
;Set to 5 for dx9 windowed
;A dx9 mode is required for any graphics related script extender functions to work (i.e. fullscreen shaders)
;Modes 1, 2 and 3 are no longer supported
Mode=0


when mode is set to 0 you can move to another screen with mouse but alt-tabbing will not show fallout icon to return to, using other modes and alt-tabbing works but mouse cursor is confined to screen(possible to alt-tab and then change window).

**Comment by Lexx2k** [comment]
The Alt+Tab thing is a Win10 issue. 

Also check f2_res.ini for graphic mode and window setting.
Other than that you might have to ask [here](https://www.nma-fallout.com/threads/hi-res-patches-for-fallout1-2-the-bis-mapper.181743/). I can't help with the issue.

**Comment by konjski-tramvaj** [comment]
> 
> 
> The Alt+Tab thing is a Win10 issue.
> 
> Also check f2_res.ini for graphic mode and window setting.
> Other than that you might have to ask [here](https://www.nma-fallout.com/threads/hi-res-patches-for-fallout1-2-the-bis-mapper.181743/). I can't help with this problem.

Thank you Lex.
