### ISSUE TITLE
Killed the Skullz ganger before Neal and bugged turns

### ISSUE THREAD

**Issue by PxHC** [rotators/Fo1in2#88]
Right after he hit Trish I opened combat and killed the 3 of them, combat ended and then Neal did his shooting animation and we all got stuck like waiting for the rest to happen, had to exit through Alt F4.

(tho I tried doing it again and didn't bug the second time)

**Comment by Lexx2k** [comment]
My guess is that because you killed the leader of the group, Neal's script got blocked. I've added a failsafe to that scene, in the hopes it won't happen again.
