### ISSUE TITLE
Standalone mods as additional release assets

### ISSUE THREAD

**Issue by wipe2238** [rotators/Fo1in2#9]
So i was thinking... maybe we could take some **standalone** mini-mods, pack them, and attach to releases? None of optional mods is bigger than 1MB, yet to get mini-mod _only_ you need whole repo/package or download files one-by-one - that's stupidity on wheels.

Sure they can be packed by hand etc., but they'll be much easier to find/link (even if they don't get any updates) than digging in modding board.

**Comment by wipe2238** [comment]
Standalone = working with any Fallout2 install,

**Comment by burner1024** [comment]
I'm not sure which mods are being discussed here, but anyway, modularization is generally considered a good practice in software development. If stuff is kept together, eventually it turns into a monolith spaghetti monster... I much prefer to divide and conquer.

For example, in RPU the components are [separated](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/components). Releases contain a single zip with multiple dats.
In fact, with [Hero Appearance](https://github.com/BGforgeNet/Fallout2_Hero_Appearance) I went further and put it into a separate repo. RPU release script just downloads latest Hero Appearance release and adds it to the package. Keeps the repo smaller and me happier.
