### ISSUE TITLE
Old saves crash on load

### ISSUE THREAD

**Issue by NikoofDeath** [rotators/Fo1in2#93]
Perhaps this is expected behavior, in which case this can be disregarded, but I didn't see any mention of incompatibility in the release notes. Updating to the latest version pushed to master (so 1.5.2634), my previous save files (from March of last year) now crash when I try to load them, with error "The instruction at 004f11db referenced memory at 00000010. The memory could not be read from". Here is my latest save slot for testing purposes. 
[SLOT84.zip](https://github.com/rotators/Fo1in2/files/6620172/SLOT84.zip)

**Comment by Lexx2k** [comment]
The next release version (v1.6 / latest repo files) will require a new game. If you want to keep playing your savegame, you'll have to revert to the version you used before updating.

It's not in the release notes yet, because there is no official release yet. :>
