### ISSUE TITLE
Game is running marginally slower than usual. 

### ISSUE THREAD

**Issue by Userluke222** [rotators/Fo1in2#94]
I can't pin point why. I've been playing with Et Tu for days and it worked fine until now, I noticed the slower movement instantly. If I reload a save it works fine for a minute or so and then the slower movement comes back. Stumped at the moment.

**Comment by Lexx2k** [comment]
Just to make sure: You don't accidentally press the speed modifier keys? :>

Other than that I would have no idea what would cause "slower movement". Might be good if you could show a video.

**Comment by Userluke222** [comment]
There are speed modifier keys? uhhhh, do you happen to know what they are lol?

**Comment by Lexx2k** [comment]
The settings are in the ddraw.ini file under [Input]. SpeedModKey by default is CTRL.

**Comment by RandDenner** [comment]
I have just played fixt and Fo1in2 back to back to see the difference.
I noticed that Fo1in2 was definitely a bit sluggish with the cursor, button presses, and critter anims as compared to fixt in the exact same areas.
Fixt was really sluggish until I changed the renderer from the default to dx9, and I was surprised that Fo1in2 seems to use the same one, but runs a little less well on it.

**Comment by Lexx2k** [comment]
You can't compare Sfall for Fo1 with Sfall for Fo2. It's really a different beast.

Dunno what you mean with "sluggish with the cursor" etc, as the game runs exactly the same everywhere for me.

**Comment by Userluke222** [comment]
> Just to make sure: You don't accidentally press the speed modifier keys? :>
> 
> Other than that I would have no idea what would cause "slower movement". Might be good if you could show a video.

Hey again, validating steam files appears to have fixed this, though I am still not sure what the issue is. I updated my Nvidia drivers and the issue has come back. Here is a video showcasing my problem, it's not mine, uploaded by someone else. https://youtu.be/qO4T7yBdd-Y
My issue isn't that severe, the game just feels a bit sluggish than usual. Oh and the travelling across the map is very slow, the maker takes it's sweet time when travelling from let's say vault 13 to vault 15. Compared to Fallout Fixt, it was way faster.

**Comment by Lexx2k** [comment]
If this is vanilla Fo1, then it seems to be an issue unrelated to ettu. Sorry, we can't help with that - no idea. An issue ticket on the [Sfall repo](https://github.com/phobos2077/sfall) might help more.
