### ISSUE TITLE
Original Junktown endings?

### ISSUE THREAD

**Issue by burner1024** [rotators/Fo1in2#97]
The ones where Killian stiffs the town, and Gizmo makes it prosper. Will they be restored (as an option, I guess)?

**Comment by Lexx2k** [comment]
Nah, they don't have voiced lines and "silent" ending slides are uncool.

**Comment by Kokokokoka** [comment]
could they stay optional? This way, one who likes content can play with silent endings.

**Comment by Dark-Jaguar** [comment]
Uncool or no, I'd be fine with it, as well as an added option to simply let all the slides play without voiceovers.

**Comment by Owyn** [comment]
what?? ppl actually cared about having voiceovers??

+1

**Comment by Anarcho-Bolshevik** [comment]
For whatever it’s worth, voice synthesization technology has been improving noticeably lately (deepfakes, anyone? lel) and I could [make a request to somebody](https://15.ai/contribute) to include the _Fallout_ narrator’s voice as an option. The biggest problem would be waiting for the delivery, which could most well take several years thanks mostly to the author’s huge workload.

**Comment by kondors1995** [comment]
We could use https://elevenlabs.io/voice-cloning or https://speechify.com/voice-cloning/ or any model from hugging face

**Comment by Dark-Jaguar** [comment]
> > Nah, they don't have voiced lines as far as I am aware and "silent" ending slides are uncool.
> 
> Can you post the full text that accompanies the cut slide? I'd like to try my hand at generating the VO using AI.

For what it's worth, I don't like using AI to replace real workers, but for small free fan projects it's an ideal solution that I have no real moral qualms with.

**Comment by burner1024** [comment]
> Can you post the full text that accompanies the cut slide? I'd like to try my hand at generating the VO using AI.

https://fallout.fandom.com/wiki/Fallout_endings#Gizmo_alternate_version

**Comment by agris-codes** [comment]
Both the Killian and Gizmo alternate endings are here: https://drive.google.com/drive/folders/1UFfL73EqTuHaUlxAMz_3EOATJOQOQitA?usp=sharing

I've provided the raw .wav as well as the ACM files. I made sure that the levels / dynamic range matched the other VOs by Perlman.

I used Eleven Labs. It got very very close, I only had to edit the files a bit.

**Comment by agris-codes** [comment]
> Now it just needs the different ending slide images.
> 
> Seems the ACM is encoded wrong. Sound plays at 50% speed.

I used SND2ACM, what do you use to make ACMs?

**Comment by Lexx2k** [comment]
Haven't converted files to ACM in a billion years. Also don't have any such tools on this pc at the moment at all, so can't do any of that. If I remember right, you have to change the bitrate of the wav file before coverting.

**Comment by burner1024** [comment]
https://github.com/BGforgeNet/ipsdoc

**Comment by agris-codes** [comment]
I’ll check out burners tool. I made the wav files with the exact characteristics of the files produced by acm2wav, pcm 16 bit mono 22050 hz. Maybe i needed to tell snd2acm that the wavs were mono, all I did was tell it source was wav

**Comment by burner1024** [comment]
Why settle for 22 when you can have 44.

**Comment by Lexx2k** [comment]
https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/mods/fo1_alternative_Junktown_Endings

The results are pretty good. Maybe the same can be applied to the ai generated lines for the expanded ending slides option? 
https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/mods/fo1_expanded_Endings_RonPerlman

**Comment by agris-codes** [comment]
> [`master`/Fallout2/Fallout1in2/mods/fo1_alternative_Junktown_Endings](https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/mods/fo1_alternative_Junktown_Endings?rgh-link-date=2024-04-26T06%3A10%3A50Z)
> 
> The results are pretty good. Maybe the same can be applied to the ai generated lines for the expanded ending slides option? [`master`/Fallout2/Fallout1in2/mods/fo1_expanded_Endings_RonPerlman](https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/mods/fo1_expanded_Endings_RonPerlman?rgh-link-date=2024-04-26T06%3A10%3A50Z)

so the ACM files in the alternative Junktown endings folder play at the correct speed?

for the "expanded endings" mod, where is the text of the expanded endings?

**Comment by agris-codes** [comment]
> Yes, I used the fixed snd2acm from the modders pack to convert it.
> 
> All expanded ending lines can be found here with EXP_N_... [`master`/Fallout2/Fallout1in2/mods/fo1_base/text/english/cuts](https://github.com/rotators/Fo1in2/tree/master/Fallout2/Fallout1in2/mods/fo1_base/text/english/cuts?rgh-link-date=2024-04-26T12%3A24%3A38Z)
> 
> They have duplicates of the vanilla lines, because I had them rerecorded completely back then.

got it. so the text that needs to be generated goes with EXP_N_[10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 31, 32, 34, 35, 36, 37, 40, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64 ]?

**Comment by Lexx2k** [comment]
Yes, but minus whatever already exists in the base game. Can't crosscheck right now.

**Comment by agris-codes** [comment]
The expanded (new) endings are 50 - 64, none of the original endings were tweaked. 

Long shot: anyone know the english pronunciation of Adytum? I never could stomach all the post-Fallout 2 fallout media, so I've never head it pronounced before. I expect it's either Add-Ee-Tum or Add-Ee-Tom.

**Comment by agris-codes** [comment]
Expanded ending slides VO is here: https://drive.google.com/drive/folders/1UFfL73EqTuHaUlxAMz_3EOATJOQOQitA?usp=sharing

You'll see a "fixed txts" subfolder, please use those versions of the EXP_N_#.txt files as I fixed several minor typos (10, 13), while tweaking the text slightly in 50 & 52 to sound better when spoken.

I was able to find a spoken reference for Adytum, Vargas from FNV https://www.youtube.com/watch?v=U8zJ2rtovlc&t=1550s
Ah-de-tum. I got the AI to say it correctly fairly consistently, although it is not perfect.

You will need to turn these into ACMs, but the wavs are all edited for correct pacing and levels.

**Comment by Lexx2k** [comment]
Pretty sure Nicole says it as well.

Replaced all files with the new ai generated ones. Not 100% perfect, primarily the "cave" effect doesn't really shine through, but all in all not bad, I'd say. At least acceptable for the mod, especially since even vanilla narrator voice lines have varying quality from ending slide to ending slide.

**Comment by kondors1995** [comment]
> Pretty sure Nicole says it as well.
> 
> Replaced all files with the new ai generated ones. Not 100% perfect, primarily the "cave" effect doesn't really shine through, but all in all not bad, I'd say. At least acceptable for the mod, especially since even vanilla narrator voice lines have varying quality from ending slide to ending slide.

do you have build of mod with these changes
